import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/app/components/Header";
import { AIR_FRYER_GUIDE_2026 } from "@/lib/air-fryer-guide-2026";
import AirFryerFilters from "./AirFryerFilters";
import styles from "./page.module.css";

export const metadata: Metadata = { title:"Guide Air Fryer 2026 : modèles, capacités et prix", description:"Comparez des Air Fryer 2026 par marque, capacité et format. Prix datés, modèles Ninja, Moulinex, Philips, Bosch et Tefal.", alternates:{canonical:"https://bonsplansmania.fr/guide-air-fryer-2026"}, openGraph:{title:"Guide Air Fryer 2026",description:"Modèles, capacités et prix vérifiés des friteuses sans huile.",url:"https://bonsplansmania.fr/guide-air-fryer-2026",type:"website"} };
export default function AirFryerGuidePage(){const schema={"@context":"https://schema.org","@type":"ItemList",name:"Guide Air Fryer 2026",numberOfItems:AIR_FRYER_GUIDE_2026.length,itemListElement:AIR_FRYER_GUIDE_2026.map((item,index)=>({"@type":"ListItem",position:index+1,name:`${item.brand} ${item.name}`,url:`https://bonsplansmania.fr${item.articleHref}`}))};return <><Header activePage="/guide-air-fryer-2026"/><main className={styles.main}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className={styles.hero}><div className="container"><p className={styles.eyebrow}>Guide d’achat · prix datés</p><h1>Quel Air Fryer choisir en 2026 ?</h1><p className={styles.intro}>Comparez les capacités, les formats et les prix des friteuses sans huile déjà vérifiées sur Bons Plans Mania.</p><p className={styles.updated}>{AIR_FRYER_GUIDE_2026.length} modèles référencés · sélection enrichie au fil des offres</p></div></section><section className={`container ${styles.section}`}><h2>Comparatif rapide des Air Fryer</h2><div className={styles.tableWrap}><table><thead><tr><th>Modèle</th><th>Capacité</th><th>Pour qui ?</th><th>Prix constaté</th></tr></thead><tbody>{AIR_FRYER_GUIDE_2026.map(item=><tr key={`${item.brand}-${item.name}`}><td><Link href={item.articleHref}><strong>{item.brand}</strong><br/>{item.name}</Link></td><td>{item.capacity}<small>{item.types.join(" · ")}</small></td><td>{item.household}</td><td><strong>{item.price}</strong><small>le {item.checkedAt}</small></td></tr>)}</tbody></table></div></section><section className={`container ${styles.section}`}><h2>Trouver un Air Fryer par marque ou format</h2><AirFryerFilters/></section><section className={`container ${styles.guide}`}><h2>Mono-cuve ou double zone ?</h2><p>Un modèle mono-cuve prend généralement moins de place. Une double zone permet de cuire deux préparations avec des réglages différents. La capacité utile et l’encombrement comptent davantage que le nombre de programmes.</p><p><Link href="/article/meilleur-airfryer-friteuse-sans-huile-2026">Lire notre comparatif détaillé des meilleures friteuses sans huile</Link></p></section></main></>}
