export type AdventCalendar2026 = {
  brand: string;
  name: string;
  price: string;
  value?: string;
  contents: string;
  status: string;
  checkedAt: string;
  image: string;
  imageAlt: string;
  articleHref: string;
  merchantHref: string;
  imageIsEditorial?: boolean;
  universes?: string[];
  audiences?: string[];
};

export const ADVENT_CALENDARS_2026: AdventCalendar2026[] = [
  {
    brand: "Adopt Parfums",
    name: "La Maison de Noël",
    price: "36,95 €",
    contents: "1 photophore + 23 mini bougies · 24 senteurs",
    status: "Disponible en avant-première",
    checkedAt: "7 septembre 2026",
    image: "/images/articles/calendrier-avent-adopt-maison-noel-2026.jpg",
    imageAlt: "Calendrier de l'Avent Adopt La Maison de Noël 2026 à 36,95 euros",
    articleHref: "/article/calendrier-avent-adopt-maison-noel-2026-24-bougies",
    merchantHref: "https://lb.affilae.com/r/?p=678fab80242409f9262715e4&af=65&lp=https%3A%2F%2Fwww.adopt.com%2Ffr%2Fcalendrier-de-l-avent-la-maison-de-noel-3701429860332-fr.html%3Futm_source%3Daffilae%26utm_medium%3Dcodes-promos%26utm_campaign%3Dbonsplansmania",
  },
  {
    brand: "Adopt Parfums",
    name: "Échappée sur la Seine Étoilée",
    price: "74,95 €",
    value: "Valeur annoncée : 160,75 €",
    contents: "23 parfums 10 ml + 1 parfum 30 ml + 1 carte cadeau",
    status: "Disponible",
    checkedAt: "7 septembre 2026",
    image: "/images/articles/calendrier-avent-adopt-seine-etoilee-2026.jpg",
    imageAlt: "Calendrier Adopt Échappée sur la Seine Étoilée 2026 à 74,95 euros",
    articleHref: "/article/calendrier-avent-adopt-seine-etoilee-2026-24-parfums",
    merchantHref: "https://lb.affilae.com/r/?p=678fab80242409f9262715e4&af=65&lp=https%3A%2F%2Fwww.adopt.com%2Ffr%2Fcalendrier-de-l-avent-echappee-sur-la-seine-etoilee-3701429856007-fr.html%3Futm_source%3Daffilae%26utm_medium%3Dcodes-promos%26utm_campaign%3Dbonsplansmania",
  },
  {
    brand: "Adopt Parfums",
    name: "Rendez-vous au Jardin d'Hiver",
    price: "94,95 €",
    value: "Valeur annoncée : 214,75 €",
    contents: "14 parfums 10 ml + 10 parfums 30 ml + 1 carte cadeau",
    status: "Disponible",
    checkedAt: "7 septembre 2026",
    image: "/images/articles/calendrier-avent-adopt-jardin-hiver-2026.jpg",
    imageAlt: "Calendrier Adopt Rendez-vous au Jardin d'Hiver 2026 à 94,95 euros",
    articleHref: "/article/calendrier-avent-adopt-jardin-hiver-2026-24-parfums",
    merchantHref: "https://lb.affilae.com/r/?p=678fab80242409f9262715e4&af=65&lp=https%3A%2F%2Fwww.adopt.com%2Ffr%2Fcalendrier-de-l-avent-rendez-vous-au-jardin-d-hiver-3701429856779-fr.html%3Futm_source%3Daffilae%26utm_medium%3Dcodes-promos%26utm_campaign%3Dbonsplansmania",
  },
  {
    brand: "Adopt Parfums",
    name: "24 Shades of Him",
    price: "99,95 €",
    value: "Valeur annoncée : 226,75 €",
    contents: "12 parfums 10 ml + 12 parfums 30 ml + 1 carte cadeau",
    status: "Disponible",
    checkedAt: "7 septembre 2026",
    image: "/images/articles/calendrier-avent-adopt-24-shades-of-him-2026.jpg",
    imageAlt: "Calendrier de l'Avent homme Adopt 24 Shades of Him 2026 à 99,95 euros",
    articleHref: "/article/calendrier-avent-adopt-homme-24-shades-of-him-2026",
    merchantHref: "https://lb.affilae.com/r/?p=678fab80242409f9262715e4&af=65&lp=https%3A%2F%2Fwww.adopt.com%2Ffr%2Fcalendrier-de-l-avent-24-shades-of-him-3701429856083-fr.html%3Futm_source%3Daffilae%26utm_medium%3Dcodes-promos%26utm_campaign%3Dbonsplansmania",
  },
  {
    brand: "Adopt Parfums",
    name: "Flânerie dans la Galerie Dorée",
    price: "159,95 €",
    value: "Valeur annoncée : 346,75 €",
    contents: "24 parfums et brumes de 30 à 200 ml + 1 carte cadeau",
    status: "Disponible",
    checkedAt: "7 septembre 2026",
    image: "/images/articles/calendrier-avent-adopt-galerie-doree-2026.jpg",
    imageAlt: "Calendrier Adopt Flânerie dans la Galerie Dorée 2026 à 159,95 euros",
    articleHref: "/article/calendrier-avent-adopt-galerie-doree-2026-parfums-formats",
    merchantHref: "https://lb.affilae.com/r/?p=678fab80242409f9262715e4&af=65&lp=https%3A%2F%2Fwww.adopt.com%2Ffr%2Fcalendrier-de-l-avent-flanerie-dans-la-galerie-doree-3701429856069-fr.html%3Futm_source%3Daffilae%26utm_medium%3Dcodes-promos%26utm_campaign%3Dbonsplansmania",
  },
  {
    brand: "L'Occitane",
    name: "Calendrier de l'Avent Édition Classique",
    price: "99 €",
    value: "Valeur annoncée : 198 €",
    contents: "24 cases · soins visage, corps, mains, cheveux et parfum",
    status: "Disponible",
    checkedAt: "17 août 2026",
    image: "https://fr.loccitane.com/dw/image/v2/BCDQ_PRD/on/demandware.static/-/Sites-occ_master/default/dw6cc66f4b/RECT/10CACLA26.avif?sw=880&sh=1110&sm=fit&sfrm=png",
    imageAlt: "Calendrier de l'Avent L'Occitane 2026 Édition Classique",
    articleHref: "/article/calendriers-avent-loccitane-2026-classique-prestige",
    merchantHref: "https://fr.loccitane.com/cadeaux/recherche/calendriers-de-l-avent?eaf-publisher=affilae&eaf-name=affilae-fil_rouge&eaf-creative=all&eaf-creativetype=all&utm_source=affilae&utm_medium=roiAffiliate&utm_campaign=affilae-fil_rouge&utm_term=bonsplansmania&eseg-name=bonsplansmania&eseg-item=474&ae=474",
  },
  {
    brand: "L'Occitane",
    name: "Calendrier de l'Avent Édition Prestige",
    price: "169 €",
    value: "Valeur annoncée : 270 €",
    contents: "24 cases · formats généreux et soins premium",
    status: "Disponible",
    checkedAt: "17 août 2026",
    image: "https://fr.loccitane.com/dw/image/v2/BCDQ_PRD/on/demandware.static/-/Sites-occ_master/default/dw07ae1e06/RECT/10DECAL26.avif?sw=880&sh=1110&sm=fit&sfrm=png",
    imageAlt: "Calendrier de l'Avent L'Occitane 2026 Édition Prestige",
    articleHref: "/article/calendriers-avent-loccitane-2026-classique-prestige",
    merchantHref: "https://fr.loccitane.com/cadeaux/recherche/calendriers-de-l-avent?eaf-publisher=affilae&eaf-name=affilae-fil_rouge&eaf-creative=all&eaf-creativetype=all&utm_source=affilae&utm_medium=roiAffiliate&utm_campaign=affilae-fil_rouge&utm_term=bonsplansmania&eseg-name=bonsplansmania&eseg-item=474&ae=474",
  },
  {
    brand: "LOOKFANTASTIC",
    name: "Calendrier de l'Avent Beauté 2026",
    price: "140 €",
    value: "Valeur annoncée : 771 €",
    contents: "25 cases · 27 produits · 19 grands formats",
    status: "Précommande ouverte · expédition au plus tard le 22 septembre",
    checkedAt: "3 septembre 2026",
    image: "/images/articles/calendrier-avent-lookfantastic-beaute-2026.webp",
    imageAlt: "Calendrier de l'Avent Beauté LOOKFANTASTIC 2026 violet avec 25 cases",
    articleHref: "/article/calendrier-avent-lookfantastic-beaute-2026-27-produits",
    merchantHref: "https://www.awin1.com/cread.php?awinmid=7496&awinaffid=990397&ued=https%3A%2F%2Fwww.lookfantastic.fr%2Fp%2Fbeauty-box%2Fle-calendrier-de-l-avent-beaute-d-une-valeur-de-plus-de-771%2F17691366%2F",
  },
  {
    brand: "LOOKFANTASTIC",
    name: "Calendrier de l'Avent Homme 2026",
    price: "105 €",
    value: "Valeur annoncée : plus de 544 €",
    contents: "25 cases · 27 soins et accessoires · 15 grands formats",
    status: "Précommande ouverte · expédition au plus tard le 22 septembre",
    checkedAt: "6 septembre 2026",
    image: "/images/articles/calendrier-avent-homme-lookfantastic-2026-25-cases-105-euros.jpg",
    imageAlt: "Calendrier de l'Avent Homme LOOKFANTASTIC 2026 avec 25 cases et 27 produits",
    articleHref: "/article/calendrier-avent-homme-lookfantastic-2026-25-cases-105-euros",
    merchantHref: "https://www.awin1.com/cread.php?awinmid=7496&awinaffid=990397&ued=https%3A%2F%2Fwww.lookfantastic.fr%2Fp%2Fbeauty-box%2Fle-calendrier-de-l-avent-homme-d-une-valeur-de-plus-de-544%2F17691389%2F",
  },
  {
    brand: "Marie Claire",
    name: "Calendrier de l’Avent Beauté 2026",
    price: "74,99 €",
    value: "Valeur annoncée : 701,35 €",
    contents: "24 surprises · 15 soins · 8 produits maquillage et cheveux · 1 bijou",
    status: "Disponible · édition limitée",
    checkedAt: "10 septembre 2026",
    image: "/images/articles/calendrier-avent-marie-claire-2026-24-surprises.jpg",
    imageAlt: "Calendrier de l’Avent beauté Marie Claire 2026 à 74,99 euros",
    articleHref: "/article/calendrier-avent-marie-claire-2026-24-surprises-74-99-euros",
    merchantHref: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23249991&url=https%3A%2F%2Fmybeautyfactory.fr%2Fbox%2F1507-calendrier-avent-102026.html",
  },
  {
    brand: "Cottage",
    name: "Calendrier de l’Avent Corps et Cheveux 2026",
    price: "36,90 €",
    contents: "24 soins de 50 ml · douche, corps et cheveux",
    status: "Disponible",
    checkedAt: "3 septembre 2026",
    image: "/images/articles/calendrier-avent-cottage-2026.webp",
    imageAlt: "Calendrier de l’Avent Cottage 2026 avec 24 soins corps et cheveux",
    articleHref: "/article/calendrier-avent-cottage-2026-24-soins-corps-cheveux",
    merchantHref: "https://www.amazon.fr/Cottage-Calendrier-de-lavent-2025/dp/B0FVXW5XW8?linkCode=ll2&tag=lebrunnathali-21&linkId=be83b2e5aa528264515d118d1687d4fe&ref_=as_li_ss_tl",
  },
  {
    brand: "Maybelline New York",
    name: "Calendrier de l’Avent Maquillage 2026",
    price: "Voir le prix actuel",
    contents: "24 cases · 18 produits Maybelline · 3 soins Garnier · 3 accessoires",
    status: "Disponible sur Amazon",
    checkedAt: "3 septembre 2026",
    image: "/images/articles/calendrier-avent-maybelline-2026-24-produits.webp",
    imageAlt: "Calendrier de l’Avent Maybelline New York 2026 rouge avec 24 surprises beauté",
    articleHref: "/article/calendrier-avent-maybelline-new-york-2026-24-produits",
    merchantHref: "https://www.amazon.fr/MAYBELLINE-NEW-YORK-Calendrier-Maquillage/dp/B0H37K91VN?linkCode=ll2&tag=lebrunnathali-21&linkId=5f79abb48513a3603fcb3b061f401883&ref_=as_li_ss_tl",
  },
  {
    brand: "Revolution Beauty",
    name: "Calendrier de l’Avent Beauté 2026",
    price: "Voir le prix actuel",
    value: "Valeur annoncée : plus de 100 €",
    contents: "24 cases · 10 grands formats · 8 miniatures · 6 accessoires",
    status: "Disponible sur Amazon",
    checkedAt: "3 septembre 2026",
    image: "/images/articles/calendrier-avent-revolution-beauty-2026.webp",
    imageAlt: "Calendrier de l’Avent Revolution Beauty 2026 rose avec 24 produits et accessoires",
    articleHref: "/article/calendrier-avent-revolution-beauty-2026-24-produits",
    merchantHref: "https://www.amazon.fr/Revolution-calendrier-lAvent-beaut%C3%A9-coffret/dp/B0H38V8YHY?linkCode=ll2&tag=lebrunnathali-21&linkId=9c1ba770d1fed872129450b12d9e315b&ref_=as_li_ss_tl",
  },
  {
    brand: "MiiN Cosmetics",
    name: "Calendrier de l’Avent K-Beauty 2026",
    price: "119,99 €",
    value: "Valeur annoncée : 410 €",
    contents: "24 produits K-beauty · routine coréenne complète",
    status: "À venir · inscription à l’alerte ouverte",
    checkedAt: "3 septembre 2026",
    image: "/images/articles/calendrier-avent-miin-cosmetics-kbeauty-2026.webp",
    imageAlt: "Visuel officiel du calendrier de l’Avent K-Beauty MiiN Cosmetics 2026",
    articleHref: "/article/calendrier-avent-miin-cosmetics-kbeauty-2026-24-produits",
    merchantHref: "https://www.awin1.com/cread.php?awinmid=29885&awinaffid=990397&ued=https%3A%2F%2Fmiin-cosmetics.fr%2Fcontent%2F458-calendrier-avent-2026-countdown",
  },
  {
    brand: "Essence",
    name: "Baked With Love 2026",
    price: "29,99 €",
    contents: "24 produits · maquillage, soins et accessoires",
    status: "Stock limité chez Atida · disponibilité à vérifier",
    checkedAt: "3 septembre 2026",
    image: "/images/articles/calendrier-avent-essence-baked-with-love-2026-atida.webp",
    imageAlt: "Calendrier de l’Avent Essence Baked With Love 2026 contenant 24 produits",
    articleHref: "/article/calendrier-avent-essence-2026-baked-with-love-24-produits-cosmechic",
    merchantHref: "https://nwq.atida.fr/?P512F8957CD2D1F1&redir=https%3A%2F%2Fwww.atida.fr%2Fessence-calendrier-de-l-avent-baked-with-love-24-unites.html%3FqueryID%3Ddee9ebcaeb4457cbdc0462fce96b9802%26objectID%3D313578%26indexName%3Datida_fr_pro_fr_products",
  },
  {
    brand: "Blissim",
    name: "Calendrier de l'Avent 2026",
    price: "Prix à venir",
    contents: "Produits inédits en box · marques cultes et nouvelles découvertes",
    status: "Sortie annoncée le 9 septembre",
    checkedAt: "28 août 2026",
    image: "/images/articles/calendrier-avent-blissim-2026.jpg",
    imageAlt: "Aperçu officiel du calendrier de l'Avent Blissim 2026",
    articleHref: "/article/calendrier-avent-blissim-2026-sortie-9-septembre",
    merchantHref: "https://www.awin1.com/cread.php?awinmid=15574&awinaffid=990397&ued=https%3A%2F%2Fblissim.fr%2Fteasing-edition-limitee-calendrier",
  },
];
