export type AirFryerGuideProduct = {
  brand: string; name: string; price: string; checkedAt: string; capacity: string;
  types: string[]; household: string; programs: string; image: string; imageAlt: string;
  articleHref: string; merchantHref: string;
};

export const AIR_FRYER_GUIDE_2026: AirFryerGuideProduct[] = [
  { brand: "Bosch", name: "Série 6 XXL MAF671C0", price: "129,00 €", checkedAt: "17 août 2026", capacity: "7,2 L", types: ["Mono-cuve", "Grande capacité"], household: "Famille", programs: "7 programmes", image: "/images/articles/bon-plan-amazon-bosch-air-fryer-xxl-7-2l-7-programmes-juin-2026.png", imageAlt: "Bosch Air Fryer Série 6 XXL 7,2 litres", articleHref: "/article/bon-plan-amazon-bosch-air-fryer-xxl-7-2l-7-programmes-juin-2026", merchantHref: "https://www.amazon.fr/dp/B0FWKGDJLD?th=1&linkCode=ll2&tag=lebrunnathali-21&linkId=de7dde474ef72ff19f1e82bbbabce028&ref_=as_li_ss_tl" },
  { brand: "Moulinex", name: "Easy Fry Mega", price: "69,99 €", checkedAt: "29 juin 2026", capacity: "7,5 L", types: ["Mono-cuve", "Grande capacité"], household: "Jusqu’à 8 personnes", programs: "8 programmes", image: "/images/articles/moulinex-easy-fry-mega-air-fryer-7-5l-amazon.png", imageAlt: "Moulinex Easy Fry Mega air fryer 7,5 litres", articleHref: "/article/moulinex-easy-fry-mega-air-fryer-7-5l-amazon", merchantHref: "https://www.amazon.fr/dp/B0DGLFBT67?tag=lebrunnathali-21" },
  { brand: "Moulinex", name: "Multicook & Fry", price: "99,99 €", checkedAt: "1er juillet 2026", capacity: "Multicuiseur", types: ["Multicuiseur", "Polyvalent"], household: "Famille", programs: "12 programmes", image: "/images/articles/bon-plan-amazon-moulinex-multicook-fry-multicuiseur-air-fryer-12-programmes-juillet-2026.png", imageAlt: "Moulinex Multicook and Fry multicuiseur et air fryer", articleHref: "/article/bon-plan-amazon-moulinex-multicook-fry-multicuiseur-air-fryer-12-programmes-juillet-2026", merchantHref: "https://amzn.to/3SzbvCF" },
  { brand: "Ninja", name: "CRISPi portable 4-en-1", price: "109,00 €", checkedAt: "17 août 2026", capacity: "3,8 L", types: ["Cuve en verre", "Compact"], household: "1 à 3 personnes", programs: "4 modes", image: "/images/articles/ninja-crispi-friteuse-sans-huile-3-8l-4-en-1-amazon-promo-2026.png", imageAlt: "Ninja CRISPi friteuse sans huile portable 3,8 litres", articleHref: "/article/ninja-crispi-friteuse-sans-huile-3-8l-4-en-1-amazon-promo-2026", merchantHref: "https://www.amazon.fr/dp/B0F99KSRL5?tag=lebrunnathali-21" },
  { brand: "Ninja", name: "Air Fryer MAX PRO", price: "109,99 €", checkedAt: "29 juin 2026", capacity: "6,2 L", types: ["Mono-cuve"], household: "Famille", programs: "Cuire, rôtir et frire", image: "/images/articles/ninja-air-fryer-max-pro-6-2l-amazon.png", imageAlt: "Ninja Air Fryer MAX PRO 6,2 litres", articleHref: "/article/ninja-air-fryer-max-pro-6-2l-amazon", merchantHref: "https://www.amazon.fr/dp/B0DSK843XY?tag=lebrunnathali-21" },
  { brand: "Ninja", name: "Foodi FlexDrawer AF500EU", price: "164,99 €", checkedAt: "23 juin 2026", capacity: "10,4 L", types: ["Double zone", "Grande capacité"], household: "Grande famille", programs: "7 fonctions", image: "/images/articles/bon-plan-ninja-foodi-flexdrawer-airfryer-dual-zone-af500eu-165-euros.png", imageAlt: "Ninja Foodi FlexDrawer AF500EU double zone", articleHref: "/article/bon-plan-ninja-foodi-flexdrawer-airfryer-dual-zone-af500eu-165-euros", merchantHref: "https://www.amazon.fr/dp/B0CJVNGMFL?tag=lebrunnathali-21" },
  { brand: "Philips", name: "Airfryer Série 1000 NA150", price: "119,99 €", checkedAt: "4 août 2026", capacity: "7 L", types: ["Double zone", "Grande capacité"], household: "Famille", programs: "Panier flexible", image: "/images/articles/bon-plan-cdiscount-philips-na150-friteuse-sans-huile-airfryer-serie-1000-7l-juillet-2026.png", imageAlt: "Philips Airfryer Série 1000 NA150 7 litres", articleHref: "/article/bon-plan-cdiscount-philips-na150-friteuse-sans-huile-airfryer-serie-1000-7l-juillet-2026", merchantHref: "https://www.awin1.com/cread.php?awinmid=6948&awinaffid=990397&ued=https%3A%2F%2Fwww.cdiscount.com%2Felectromenager%2Fpetits-appareils-de-cuisson%2Ffriteuse-sans-huile-philips-na150-00-airfrye%2Ff-1102002-auc1736123018677.html" },
  { brand: "Tefal", name: "Easy Fry XL FW4018", price: "97,99 €", checkedAt: "18 juillet 2026", capacity: "XL", types: ["Mono-cuve", "Grande capacité"], household: "Famille", programs: "Grande surface de cuisson", image: "/images/articles/tefal-easy-fry-xl-air-fryer-amazon.png", imageAlt: "Tefal Easy Fry XL air fryer FW4018", articleHref: "/article/tefal-easy-fry-xl-air-fryer-amazon", merchantHref: "https://www.amazon.fr/dp/B0DGGST2B4?tag=lebrunnathali-21" },
];
