import type { BrandDef } from "@/app/components/BrandFilter";

// Liste manuelle propre pour /categorie/bon-plan et /bons-plans-en-cours
// (validée par l'utilisateur, ajustée le 29 mai 2026).
export const BON_PLAN_BRANDS: BrandDef[] = [
  // Marketplaces & sites
  { key: "amazon", label: "Amazon", keywords: ["amazon"] },
  { key: "cdiscount", label: "Cdiscount", keywords: ["cdiscount"] },
  { key: "yesstyle", label: "YesStyle", keywords: ["yesstyle"] },
  { key: "lookfantastic", label: "Lookfantastic", keywords: ["lookfantastic"] },
  { key: "bebeboutik", label: "Bebeboutik", keywords: ["bebeboutik", "bébéboutik"] },
  { key: "showroom-prive", label: "Showroom Privé", keywords: ["showroom privé", "showroom prive", "showroom-prive", "showroomprive"] },
  { key: "greenweez", label: "Greenweez", keywords: ["greenweez"] },
  { key: "private-sport-shop", label: "Private Sport Shop", keywords: ["private sport shop", "private-sport-shop"] },
  { key: "zooplus", label: "Zooplus", keywords: ["zooplus", "zoo plus"] },
  { key: "mano-mano", label: "Mano Mano", keywords: ["mano mano", "manomano", "mano-mano"] },
  { key: "darty", label: "Darty", keywords: ["darty"] },
  // Cashback (catégorie large)
  { key: "cashback", label: "Cashback", keywords: ["cashback", "igraal", "ebuyclub", "poulpeo"] },
  // Beauté
  { key: "loreal", label: "L'Oréal", keywords: ["l'oréal", "l oreal", "loreal", "l'oreal", "loreal-paris", "l'oréal paris"] },
  { key: "garnier", label: "Garnier", keywords: ["garnier"] },
  { key: "maybelline", label: "Maybelline", keywords: ["maybelline"] },
  { key: "ghd", label: "GHD", keywords: ["ghd"] },
  { key: "dr-pierre-ricaud", label: "Dr Pierre Ricaud", keywords: ["dr pierre ricaud", "dr-pierre-ricaud", "pierre ricaud", "pierre-ricaud"] },
  { key: "lea-nature", label: "Léa Nature", keywords: ["léa nature", "lea nature", "lea-nature", "léa-nature"] },
  { key: "loccitane", label: "L'Occitane", keywords: ["l'occitane", "l occitane", "loccitane", "occitane"] },
  { key: "clarins", label: "Clarins", keywords: ["clarins"] },
  { key: "beauty-success", label: "Beauty Success", keywords: ["beauty success", "beauty-success", "beautysuccess"] },
  // Famille / bébé
  { key: "puericulture", label: "Puériculture", keywords: ["puériculture", "puericulture"] },
  { key: "pampers", label: "Pampers", keywords: ["pampers"] },
  // K-Beauty (catégorie)
  { key: "kbeauty", label: "K-Beauty", keywords: ["k-beauty", "kbeauty", "k beauty"] },
  // Tech
  { key: "philips", label: "Philips", keywords: ["philips"] },
  { key: "samsung", label: "Samsung", keywords: ["samsung"] },
  { key: "dyson", label: "Dyson", keywords: ["dyson"] },
  { key: "oral-b", label: "Oral-B", keywords: ["oral-b", "oral b", "oralb"] },
  // Ajouts utilisateur
  { key: "thalgo", label: "Thalgo", keywords: ["thalgo"] },
  { key: "adopt", label: "Adopt'", keywords: ["adopt", "adopt-parfums", "adopt parfums", "adopt'"] },
  { key: "weleda", label: "Weleda", keywords: ["weleda"] },
  { key: "beaba", label: "Béaba", keywords: ["béaba", "beaba"] },
  { key: "stylvana", label: "Stylvana", keywords: ["stylvana", "stylevana"] },
  { key: "miin", label: "MiiN Cosmetics", keywords: ["miin", "miin cosmetics", "miin-cosmetics", "miin cosmetic"] },
  { key: "les-createurs-bio", label: "Les Créateurs Bio", keywords: ["les créateurs bio", "les createurs bio", "les-createurs-bio", "createurs bio", "createurs-bio"] },
  { key: "magnifaik", label: "Magnifaïk", keywords: ["magnifaïk", "magnifaik"] },
  { key: "atelier-du-sourcil", label: "L'Atelier du Sourcil", keywords: ["atelier du sourcil", "l'atelier du sourcil", "atelier-du-sourcil"] },
  { key: "pranarom", label: "Pranarôm", keywords: ["pranarôm", "pranarom"] },
  { key: "le-rouge-francais", label: "Le Rouge Français", keywords: ["le rouge français", "rouge français", "le-rouge-francais", "rouge-francais", "le rouge francais"] },
  { key: "mademoiselle-bio", label: "Mademoiselle Bio", keywords: ["mademoiselle bio", "mademoiselle-bio"] },
  { key: "rakuten", label: "Rakuten", keywords: ["rakuten"] },
  { key: "famille-mary", label: "Famille Mary", keywords: ["famille mary", "famille-mary"] },
  { key: "afibel", label: "Afibel", keywords: ["afibel"] },
  { key: "beaute-produit", label: "Beauté Produit", keywords: ["beauté produit", "beaute produit", "beaute-produit", "beauteproduit", "beaute-produit.com"] },
  { key: "daxon", label: "Daxon", keywords: ["daxon"] },
  { key: "laboratoire-biarritz", label: "Laboratoire Biarritz", keywords: ["laboratoire biarritz", "laboratoire-biarritz", "labo biarritz"] },
  { key: "news-parfums", label: "News Parfums", keywords: ["news parfums", "news-parfums", "newsparfums"] },
  { key: "blanche-porte", label: "Blanche Porte", keywords: ["blanche porte", "blanche-porte", "blancheporte"] },
  { key: "gemo", label: "Gémo", keywords: ["gémo", "gemo"] },
  { key: "damart", label: "Damart", keywords: ["damart"] },
];

// Hub /bons-plans-ninja : on filtre par gamme de produits Ninja
export const NINJA_BRANDS: BrandDef[] = [
  { key: "foodi", label: "Ninja Foodi (airfryer)", keywords: ["foodi", "ninja-foodi", "airfryer", "friteuse-sans-huile"] },
  { key: "creami", label: "Ninja CREAMi (glaces)", keywords: ["creami", "ninja-creami", "sorbetiere", "sorbetière"] },
  { key: "slushi", label: "Ninja SLUSHi (granités)", keywords: ["slushi", "ninja-slushi", "granité", "granite"] },
  { key: "crispi", label: "Ninja CRISPi (verre)", keywords: ["crispi", "ninja-crispi"] },
  { key: "blast", label: "Ninja Blast (blender)", keywords: ["blast", "ninja-blast", "blender"] },
  { key: "thirsti", label: "Ninja Thirsti (boissons)", keywords: ["thirsti", "ninja-thirsti"] },
  { key: "speedi", label: "Ninja Speedi (multicuiseur)", keywords: ["speedi", "ninja-speedi"] },
];

// Hub /bons-plans-tech
export const TECH_BRANDS: BrandDef[] = [
  { key: "apple", label: "Apple", keywords: ["apple", "macbook", "ipad", "airpods", "apple-watch", "iphone"] },
  { key: "samsung", label: "Samsung", keywords: ["samsung", "galaxy", "galaxy-watch", "galaxy-buds"] },
  { key: "google", label: "Google", keywords: ["google", "pixel", "pixel-watch", "pixel-buds"] },
  { key: "xiaomi", label: "Xiaomi / Redmi", keywords: ["xiaomi", "redmi", "mi-watch", "poco"] },
  { key: "huawei", label: "Huawei", keywords: ["huawei"] },
  { key: "oneplus", label: "OnePlus", keywords: ["oneplus", "one plus"] },
  { key: "sony", label: "Sony", keywords: ["sony", "playstation", "ps5"] },
  { key: "jbl", label: "JBL", keywords: ["jbl"] },
  { key: "bose", label: "Bose", keywords: ["bose"] },
  { key: "shokz", label: "Shokz", keywords: ["shokz"] },
  { key: "amazon", label: "Amazon (Kindle/Echo)", keywords: ["kindle", "echo", "amazon-echo", "fire-tv"] },
  { key: "lg", label: "LG", keywords: ["lg"] },
  { key: "asus", label: "ASUS", keywords: ["asus", "rog"] },
  { key: "dell", label: "Dell", keywords: ["dell"] },
  { key: "hp", label: "HP", keywords: ["hp", "hewlett"] },
  { key: "lenovo", label: "Lenovo", keywords: ["lenovo"] },
  { key: "alienware", label: "Alienware", keywords: ["alienware"] },
  { key: "microsoft", label: "Microsoft", keywords: ["microsoft", "surface", "xbox"] },
  { key: "nintendo", label: "Nintendo", keywords: ["nintendo", "switch"] },
  { key: "logitech", label: "Logitech", keywords: ["logitech"] },
  { key: "razer", label: "Razer", keywords: ["razer"] },
  { key: "insta360", label: "Insta360", keywords: ["insta360", "insta 360"] },
  { key: "gopro", label: "GoPro", keywords: ["gopro", "go-pro"] },
  { key: "anker", label: "Anker / Soundcore", keywords: ["anker", "soundcore"] },
];

// Hub /bons-plans-maison (incl. cuisine)
export const MAISON_BRANDS: BrandDef[] = [
  { key: "ninja", label: "Ninja", keywords: ["ninja", "foodi", "creami", "slushi", "crispi"] },
  { key: "philips", label: "Philips", keywords: ["philips"] },
  { key: "dyson", label: "Dyson", keywords: ["dyson"] },
  { key: "rowenta", label: "Rowenta", keywords: ["rowenta"] },
  { key: "tefal", label: "Tefal", keywords: ["tefal", "t-fal"] },
  { key: "moulinex", label: "Moulinex", keywords: ["moulinex"] },
  { key: "seb", label: "SEB", keywords: ["seb"] },
  { key: "krups", label: "Krups", keywords: ["krups"] },
  { key: "magimix", label: "Magimix", keywords: ["magimix"] },
  { key: "kitchenaid", label: "KitchenAid", keywords: ["kitchenaid", "kitchen aid"] },
  { key: "bosch", label: "Bosch", keywords: ["bosch"] },
  { key: "delonghi", label: "De'Longhi", keywords: ["delonghi", "de'longhi", "de longhi"] },
  { key: "lavazza", label: "Lavazza", keywords: ["lavazza"] },
  { key: "nespresso", label: "Nespresso", keywords: ["nespresso"] },
  { key: "vorwerk", label: "Vorwerk / Thermomix", keywords: ["thermomix", "vorwerk"] },
  { key: "samsung-elec", label: "Samsung (électroménager)", keywords: ["samsung"] },
  { key: "lg-elec", label: "LG (électroménager)", keywords: ["lg"] },
  { key: "hisense", label: "Hisense", keywords: ["hisense"] },
  { key: "irobot", label: "iRobot / Roomba", keywords: ["irobot", "roomba"] },
  { key: "roborock", label: "Roborock", keywords: ["roborock"] },
  { key: "shark", label: "Shark", keywords: ["shark"] },
  { key: "rotomatic", label: "Rotomatic", keywords: ["rotomatic"] },
  { key: "calor", label: "Calor", keywords: ["calor"] },
  { key: "lego", label: "LEGO", keywords: ["lego"] },
];

// Hub /bons-plans-jardin (incl. outdoor, piscine)
export const JARDIN_BRANDS: BrandDef[] = [
  { key: "bosch-jardin", label: "Bosch", keywords: ["bosch"] },
  { key: "stihl", label: "Stihl", keywords: ["stihl"] },
  { key: "husqvarna", label: "Husqvarna", keywords: ["husqvarna"] },
  { key: "karcher", label: "Kärcher", keywords: ["kärcher", "karcher"] },
  { key: "worx", label: "Worx", keywords: ["worx"] },
  { key: "ryobi", label: "Ryobi", keywords: ["ryobi"] },
  { key: "makita", label: "Makita", keywords: ["makita"] },
  { key: "dewalt", label: "DeWalt", keywords: ["dewalt"] },
  { key: "einhell", label: "Einhell", keywords: ["einhell"] },
  { key: "gardena", label: "Gardena", keywords: ["gardena"] },
  { key: "segway", label: "Segway (Navimow)", keywords: ["segway", "navimow"] },
  { key: "mammotion", label: "Mammotion", keywords: ["mammotion"] },
  { key: "ecovacs", label: "Ecovacs", keywords: ["ecovacs"] },
  { key: "intex", label: "Intex", keywords: ["intex"] },
  { key: "bestway", label: "Bestway", keywords: ["bestway"] },
  { key: "weber", label: "Weber", keywords: ["weber"] },
  { key: "campingaz", label: "Campingaz", keywords: ["campingaz"] },
  { key: "tefal-bbq", label: "Tefal", keywords: ["tefal"] },
  { key: "broil-king", label: "Broil King", keywords: ["broil king", "broil-king"] },
  { key: "aiper", label: "Aiper", keywords: ["aiper"] },
  { key: "beatbot", label: "Beatbot", keywords: ["beatbot"] },
  { key: "wybot", label: "WYBOT", keywords: ["wybot"] },
  { key: "zodiac", label: "Zodiac", keywords: ["zodiac"] },
  // Animaux / animalerie
  { key: "feandrea", label: "Feandrea", keywords: ["feandrea"] },
  { key: "tractive", label: "Tractive", keywords: ["tractive"] },
  { key: "kippy", label: "Kippy", keywords: ["kippy"] },
  { key: "zooplus", label: "Zooplus", keywords: ["zooplus"] },
  { key: "edgard-cooper", label: "Edgard & Cooper", keywords: ["edgard cooper", "edgard-cooper"] },
  { key: "royal-canin", label: "Royal Canin", keywords: ["royal canin", "royal-canin"] },
  { key: "purina", label: "Purina", keywords: ["purina", "pro plan", "pro-plan"] },
  { key: "pawhut", label: "PawHut", keywords: ["pawhut"] },
  { key: "gitelsnour", label: "Gitelsnour", keywords: ["gitelsnour"] },
  { key: "petkit", label: "Petkit", keywords: ["petkit"] },
  { key: "savic", label: "Savic", keywords: ["savic"] },
  { key: "catit", label: "Catit", keywords: ["catit"] },
  { key: "flamingo", label: "Flamingo", keywords: ["flamingo"] },
];

// Hub /bons-plans-beaute : sous-ensemble beauté de BON_PLAN_BRANDS
// Liste ordonnée alphabétiquement pour maintenance ; le dropdown utilisera
// le même ordre alpha via le prop `sortBrandsBy="alpha"`.
export const BEAUTE_BRANDS: BrandDef[] = [
  { key: "adopt", label: "Adopt'", keywords: ["adopt", "adopt-parfums", "adopt parfums", "adopt'"] },
  { key: "amazon", label: "Amazon", keywords: ["amazon"] },
  { key: "andis", label: "Andis", keywords: ["andis"] },
  { key: "atelier-du-sourcil", label: "L'Atelier du Sourcil", keywords: ["atelier du sourcil", "atelier-du-sourcil"] },
  { key: "babyliss", label: "BaByliss", keywords: ["babyliss", "babylissmen"] },
  { key: "baija", label: "Baïja", keywords: ["baija", "baïja"] },
  { key: "beauty-of-joseon", label: "Beauty of Joseon", keywords: ["beauty of joseon", "beauty-of-joseon"] },
  { key: "beauty-success", label: "Beauty Success", keywords: ["beauty success", "beauty-success", "beautysuccess"] },
  { key: "bioderma", label: "Bioderma", keywords: ["bioderma"] },
  { key: "biotherm", label: "Biotherm", keywords: ["biotherm"] },
  { key: "biotyfull", label: "Biotyfull Box", keywords: ["biotyfull", "biotyfull-box", "biotyfull box"] },
  { key: "blissim", label: "Blissim", keywords: ["blissim"] },
  { key: "braun", label: "Braun", keywords: ["braun", "braun-silk-epil", "braun-series"] },
  { key: "caudalie", label: "Caudalie", keywords: ["caudalie"] },
  { key: "cerave", label: "CeraVe", keywords: ["cerave"] },
  { key: "chanel", label: "Chanel", keywords: ["chanel", "chanel-parfum"] },
  { key: "clarins", label: "Clarins", keywords: ["clarins"] },
  { key: "clinique", label: "Clinique", keywords: ["clinique"] },
  { key: "cosrx", label: "CosRX", keywords: ["cosrx"] },
  { key: "dr-pierre-ricaud", label: "Dr Pierre Ricaud", keywords: ["dr pierre ricaud", "dr-pierre-ricaud", "pierre ricaud", "pierre-ricaud"] },
  { key: "dyson", label: "Dyson", keywords: ["dyson"] },
  { key: "dior", label: "Dior", keywords: ["dior", "dior-parfum"] },
  { key: "elizabeth-arden", label: "Elizabeth Arden", keywords: ["elizabeth arden", "elizabeth-arden"] },
  { key: "erborian", label: "Erborian", keywords: ["erborian"] },
  { key: "essence", label: "Essence", keywords: ["essence", "essence-cosmetics"] },
  { key: "famille-mary", label: "Famille Mary", keywords: ["famille mary", "famille-mary"] },
  { key: "foreo", label: "Foreo", keywords: ["foreo"] },
  { key: "garancia", label: "Garancia", keywords: ["garancia"] },
  { key: "garnier", label: "Garnier", keywords: ["garnier"] },
  { key: "ghd", label: "GHD", keywords: ["ghd"] },
  { key: "gillette", label: "Gillette", keywords: ["gillette", "gillette-labs"] },
  { key: "glowria", label: "Glowria", keywords: ["glowria"] },
  { key: "kbeauty", label: "K-Beauty", keywords: ["k-beauty", "kbeauty", "k beauty"] },
  { key: "kerargan", label: "Kerargan", keywords: ["kerargan"] },
  { key: "kerastase", label: "Kérastase", keywords: ["kerastase", "kérastase"] },
  { key: "kiko", label: "Kiko Milano", keywords: ["kiko", "kiko-milano"] },
  { key: "la-roche-posay", label: "La Roche-Posay", keywords: ["la roche-posay", "la-roche-posay", "la roche posay", "roche-posay"] },
  { key: "lea-nature", label: "Léa Nature", keywords: ["léa nature", "lea nature", "lea-nature", "léa-nature"] },
  { key: "le-rouge-francais", label: "Le Rouge Français", keywords: ["le rouge français", "rouge français", "le-rouge-francais", "rouge-francais"] },
  { key: "loccitane", label: "L'Occitane", keywords: ["l'occitane", "l occitane", "loccitane", "occitane"] },
  { key: "lookfantastic", label: "Lookfantastic", keywords: ["lookfantastic"] },
  { key: "loreal", label: "L'Oréal", keywords: ["l'oréal", "l oreal", "loreal", "loreal-paris", "l'oréal paris"] },
  { key: "lancome", label: "Lancôme", keywords: ["lancome", "lancôme"] },
  { key: "lierac", label: "Lierac", keywords: ["lierac"] },
  { key: "mademoiselle-bio", label: "Mademoiselle Bio", keywords: ["mademoiselle bio", "mademoiselle-bio"] },
  { key: "magnifaik", label: "Magnifaïk", keywords: ["magnifaïk", "magnifaik"] },
  { key: "maybelline", label: "Maybelline", keywords: ["maybelline"] },
  { key: "medicube", label: "Medicube", keywords: ["medicube"] },
  { key: "melvita", label: "Melvita", keywords: ["melvita"] },
  { key: "miin", label: "MiiN Cosmetics", keywords: ["miin", "miin cosmetics", "miin-cosmetics"] },
  { key: "mixa", label: "Mixa", keywords: ["mixa"] },
  { key: "news-parfums", label: "News Parfums", keywords: ["news parfums", "news-parfums"] },
  { key: "nivea", label: "Nivea", keywords: ["nivea"] },
  { key: "nuxe", label: "Nuxe", keywords: ["nuxe"] },
  { key: "nyx", label: "NYX Professional Makeup", keywords: ["nyx", "nyx-professional-makeup"] },
  { key: "olaplex", label: "Olaplex", keywords: ["olaplex"] },
  { key: "oral-b", label: "Oral-B", keywords: ["oral-b", "oral b", "oralb"] },
  { key: "perfumes-club", label: "Perfumes Club", keywords: ["perfumes club", "perfumes-club", "perfumesclub"] },
  { key: "philips", label: "Philips", keywords: ["philips"] },
  { key: "pranarom", label: "Pranarôm", keywords: ["pranarôm", "pranarom"] },
  { key: "remington", label: "Remington", keywords: ["remington"] },
  { key: "sephora", label: "Sephora", keywords: ["sephora"] },
  { key: "so-bio-etic", label: "So'Bio Étic", keywords: ["so'bio etic", "so bio etic", "so-bio-etic", "sobio", "so'bio"] },
  { key: "stylvana", label: "Stylevana", keywords: ["stylvana", "stylevana"] },
  { key: "thalgo", label: "Thalgo", keywords: ["thalgo"] },
  { key: "the-ordinary", label: "The Ordinary", keywords: ["the ordinary", "the-ordinary", "ordinary"] },
  { key: "uriage", label: "Uriage", keywords: ["uriage"] },
  { key: "vichy", label: "Vichy", keywords: ["vichy"] },
  { key: "wahl", label: "Wahl", keywords: ["wahl"] },
  { key: "weleda", label: "Weleda", keywords: ["weleda"] },
  { key: "yesstyle", label: "YesStyle", keywords: ["yesstyle"] },
  { key: "yves-rocher", label: "Yves Rocher", keywords: ["yves rocher", "yves-rocher", "yvesrocher"] },
  { key: "yves-saint-laurent", label: "Yves Saint Laurent", keywords: ["yves saint laurent", "yves-saint-laurent", "ysl"] },
];

// Hub /bons-plans-bebe : sous-ensemble bébé / puériculture
export const BEBE_BRANDS: BrandDef[] = [
  { key: "amazon", label: "Amazon", keywords: ["amazon"] },
  { key: "pampers", label: "Pampers", keywords: ["pampers"] },
  { key: "beaba", label: "Béaba", keywords: ["béaba", "beaba"] },
  { key: "tigex", label: "Tigex", keywords: ["tigex"] },
  { key: "chicco", label: "Chicco", keywords: ["chicco"] },
  { key: "mam", label: "MAM", keywords: ["mam-bebe", "mam bebe"] },
  { key: "philips-avent", label: "Philips Avent", keywords: ["philips avent", "philips-avent", "avent"] },
  { key: "mustela", label: "Mustela", keywords: ["mustela"] },
  { key: "tidoo", label: "Tidoo", keywords: ["tidoo"] },
  { key: "bioderma", label: "Bioderma", keywords: ["bioderma"] },
  { key: "babyliss", label: "Babyliss", keywords: ["babyliss"] },
  { key: "babymoov", label: "Babymoov", keywords: ["babymoov"] },
  { key: "babyzen", label: "Babyzen", keywords: ["babyzen", "yoyo"] },
  { key: "babybjorn", label: "BabyBjörn", keywords: ["babybjorn", "babybjörn"] },
  { key: "maxi-cosi", label: "Maxi-Cosi", keywords: ["maxi-cosi", "maxi cosi", "maxicosi"] },
  { key: "cybex", label: "Cybex", keywords: ["cybex"] },
  { key: "kinderkraft", label: "Kinderkraft", keywords: ["kinderkraft"] },
  { key: "lionelo", label: "Lionelo", keywords: ["lionelo"] },
  { key: "joie", label: "Joie", keywords: ["joie"] },
  { key: "bebe-confort", label: "Bébé Confort", keywords: ["bébé confort", "bebe confort", "bebe-confort"] },
  { key: "stokke", label: "Stokke", keywords: ["stokke"] },
  { key: "elvie", label: "Elvie", keywords: ["elvie"] },
  { key: "medela", label: "Medela", keywords: ["medela"] },
  { key: "momcozy", label: "Momcozy", keywords: ["momcozy"] },
  { key: "nuk", label: "NUK", keywords: ["nuk"] },
  { key: "tommee-tippee", label: "Tommee Tippee", keywords: ["tommee tippee", "tommee-tippee"] },
  { key: "fisher-price", label: "Fisher-Price", keywords: ["fisher-price", "fisher price"] },
  { key: "vtech", label: "Vtech", keywords: ["vtech", "v-tech"] },
  { key: "puericulture", label: "Puériculture (autre)", keywords: ["puériculture", "puericulture"] },
];

// Hub /bons-plans-jouets (LEGO, Playmobil, jeux de société, peluches, poupées, jouets éducatifs)
export const JOUETS_BRANDS: BrandDef[] = [
  { key: "amazon", label: "Amazon", keywords: ["amazon"] },
  { key: "lego", label: "LEGO", keywords: ["lego"] },
  { key: "playmobil", label: "Playmobil", keywords: ["playmobil"] },
  { key: "mattel", label: "Mattel", keywords: ["mattel"] },
  { key: "barbie", label: "Barbie", keywords: ["barbie"] },
  { key: "hot-wheels", label: "Hot Wheels", keywords: ["hot wheels", "hot-wheels"] },
  { key: "hasbro", label: "Hasbro", keywords: ["hasbro"] },
  { key: "monopoly", label: "Monopoly", keywords: ["monopoly"] },
  { key: "nerf", label: "Nerf", keywords: ["nerf"] },
  { key: "ravensburger", label: "Ravensburger", keywords: ["ravensburger"] },
  { key: "asmodee", label: "Asmodee", keywords: ["asmodee"] },
  { key: "djeco", label: "Djeco", keywords: ["djeco"] },
  { key: "haba", label: "Haba", keywords: ["haba"] },
  { key: "vtech", label: "Vtech", keywords: ["vtech", "v-tech"] },
  { key: "fisher-price", label: "Fisher-Price", keywords: ["fisher-price", "fisher price"] },
  { key: "schleich", label: "Schleich", keywords: ["schleich"] },
  { key: "sylvanian-families", label: "Sylvanian Families", keywords: ["sylvanian families", "sylvanian-families"] },
  { key: "funko-pop", label: "Funko Pop", keywords: ["funko", "funko-pop"] },
  { key: "squishmallows", label: "Squishmallows", keywords: ["squishmallows"] },
  { key: "pokemon", label: "Pokémon", keywords: ["pokemon", "pokémon"] },
  { key: "disney", label: "Disney", keywords: ["disney"] },
  { key: "marvel", label: "Marvel", keywords: ["marvel"] },
  { key: "star-wars", label: "Star Wars", keywords: ["star wars", "star-wars"] },
  { key: "crayola", label: "Crayola", keywords: ["crayola"] },
  { key: "smoby", label: "Smoby", keywords: ["smoby"] },
  { key: "play-doh", label: "Play-Doh", keywords: ["play-doh", "play doh"] },
  { key: "bandai", label: "Bandai", keywords: ["bandai"] },
  { key: "tiptoi", label: "Tiptoi", keywords: ["tiptoi"] },
  { key: "barbie-extra", label: "Barbie Extra", keywords: ["barbie extra"] },
];

// Hub /bons-plans-mode (mode, chaussures, montres analogiques, sacs, accessoires)
export const MODE_BRANDS: BrandDef[] = [
  { key: "amazon", label: "Amazon", keywords: ["amazon"] },
  // Sport / sneakers
  { key: "nike", label: "Nike", keywords: ["nike", "jordan", "nike-jordan"] },
  { key: "adidas", label: "Adidas", keywords: ["adidas"] },
  { key: "puma", label: "Puma", keywords: ["puma"] },
  { key: "reebok", label: "Reebok", keywords: ["reebok"] },
  { key: "asics", label: "Asics", keywords: ["asics"] },
  { key: "hoka", label: "Hoka", keywords: ["hoka", "hoka-one-one"] },
  { key: "salomon", label: "Salomon", keywords: ["salomon"] },
  { key: "new-balance", label: "New Balance", keywords: ["new-balance", "new balance"] },
  { key: "converse", label: "Converse", keywords: ["converse"] },
  { key: "vans", label: "Vans", keywords: ["vans"] },
  // Mode premium / casual
  { key: "lacoste", label: "Lacoste", keywords: ["lacoste"] },
  { key: "tommy-hilfiger", label: "Tommy Hilfiger", keywords: ["tommy-hilfiger", "tommy hilfiger", "tommy"] },
  { key: "calvin-klein", label: "Calvin Klein", keywords: ["calvin-klein", "calvin klein"] },
  { key: "levis", label: "Levi's", keywords: ["levis", "levi's", "levi-s"] },
  { key: "jott", label: "Jott", keywords: ["jott"] },
  { key: "quiksilver", label: "Quiksilver", keywords: ["quiksilver"] },
  // Chaussures
  { key: "bata", label: "Bata", keywords: ["bata"] },
  { key: "birkenstock", label: "Birkenstock", keywords: ["birkenstock"] },
  { key: "crocs", label: "Crocs", keywords: ["crocs"] },
  { key: "chaussea", label: "Chaussea", keywords: ["chaussea"] },
  // Bagagerie / sacs
  { key: "eastpak", label: "Eastpak", keywords: ["eastpak"] },
  { key: "delsey", label: "Delsey", keywords: ["delsey"] },
  { key: "samsonite", label: "Samsonite", keywords: ["samsonite"] },
  // Lunettes
  { key: "ray-ban", label: "Ray-Ban", keywords: ["ray-ban", "ray ban", "rayban"] },
  // Enseignes mode FR
  { key: "la-halle", label: "La Halle", keywords: ["la halle", "la-halle"] },
  { key: "gemo", label: "Gémo", keywords: ["gémo", "gemo"] },
  { key: "showroom-prive", label: "Showroom Privé", keywords: ["showroom prive", "showroom privé", "showroomprive", "showroom-prive"] },
  { key: "le-slip-francais", label: "Le Slip Français", keywords: ["le slip français", "le slip francais", "le-slip-francais", "slip-francais"] },
  { key: "monsieur-tshirt", label: "Monsieur Tshirt", keywords: ["monsieur tshirt", "monsieur-tshirt"] },
  { key: "blanche-porte", label: "Blanche Porte", keywords: ["blanche porte", "blanche-porte", "blancheporte"] },
  { key: "afibel", label: "Afibel", keywords: ["afibel"] },
  { key: "damart", label: "Damart", keywords: ["damart"] },
  { key: "daxon", label: "Daxon", keywords: ["daxon"] },
  { key: "private-sport-shop", label: "Private Sport Shop", keywords: ["private sport shop", "private-sport-shop"] },
];

// Liste manuelle des box beauté présentes sur le site
export const BOX_BEAUTE_BRANDS: BrandDef[] = [
  { key: "biotyfull", label: "Biotyfull Box", keywords: ["biotyfull", "biotyfull-box", "biotyfull box"] },
  { key: "blissim", label: "Blissim", keywords: ["blissim"] },
  { key: "glowria", label: "Glowria", keywords: ["glowria"] },
  { key: "lookfantastic", label: "Lookfantastic", keywords: ["lookfantastic"] },
  { key: "prescription-lab", label: "Prescription Lab", keywords: ["prescription lab", "prescription-lab", "prescriptionlab"] },
  { key: "my-little-box", label: "My Little Box", keywords: ["my little box", "my-little-box", "mylittlebox"] },
  { key: "my-beauty-factory", label: "My Beauty Factory", keywords: ["my beauty factory", "my-beauty-factory", "mybeautyfactory"] },
  { key: "laromabox", label: "L'Arôma Box", keywords: ["laromabox", "l-aroma-box", "l'aroma box", "larômabox", "l'arôma box", "aroma box"] },
  { key: "belle-au-naturel", label: "Belle au Naturel", keywords: ["belle au naturel", "belle-au-naturel"] },
  { key: "mademoiselle-bio", label: "Mademoiselle Bio", keywords: ["mademoiselle bio", "mademoiselle-bio"] },
  { key: "mademoiselle-confettis", label: "Mademoiselle Confettis", keywords: ["mademoiselle confettis", "mademoiselle-confettis"] },
  { key: "nuoo", label: "Nuoo", keywords: ["nuoo"] },
];

// Hub /bons-plans-rentree : fournitures scolaires + cartables + agendas + coloriage éducatif
export const RENTREE_BRANDS: BrandDef[] = [
  { key: "amazon", label: "Amazon", keywords: ["amazon"] },
  { key: "bic", label: "BIC", keywords: ["bic", "bic-kids"] },
  { key: "maped", label: "Maped", keywords: ["maped", "color-peps"] },
  { key: "stabilo", label: "STABILO", keywords: ["stabilo", "stabilo-boss"] },
  { key: "clairefontaine", label: "Clairefontaine", keywords: ["clairefontaine"] },
  { key: "oxford", label: "Oxford", keywords: ["oxford"] },
  { key: "faber-castell", label: "Faber-Castell", keywords: ["faber-castell", "faber castell"] },
  { key: "staedtler", label: "Staedtler", keywords: ["staedtler"] },
  { key: "pilot", label: "Pilot", keywords: ["pilot", "pilot-frixion", "frixion"] },
  { key: "paper-mate", label: "Paper Mate", keywords: ["paper mate", "paper-mate"] },
  { key: "sharpie", label: "Sharpie", keywords: ["sharpie"] },
  { key: "scotch", label: "Scotch", keywords: ["scotch"] },
  { key: "posca", label: "Posca", keywords: ["posca"] },
  { key: "canson", label: "Canson", keywords: ["canson"] },
  { key: "crayola", label: "Crayola", keywords: ["crayola"] },
  { key: "minecraft", label: "Minecraft", keywords: ["minecraft"] },
  { key: "roblox", label: "Roblox", keywords: ["roblox"] },
  { key: "casio", label: "Casio", keywords: ["casio"] },
  { key: "texas-instruments", label: "Texas Instruments", keywords: ["texas instruments", "texas-instruments"] },
];

/**
 * Catalogue commun utilisé par les pages transversales (« bons plans en cours »
 * et catégorie générale). Chaque univers garde sa liste spécialisée, mais une
 * marque ajoutée à l'un d'eux n'est plus oubliée dans le filtre global.
 */
export const ALL_DEAL_BRANDS: BrandDef[] = [
  ...BON_PLAN_BRANDS,
  ...BEAUTE_BRANDS,
  ...BEBE_BRANDS,
  ...TECH_BRANDS,
  ...MAISON_BRANDS,
  ...JARDIN_BRANDS,
  ...JOUETS_BRANDS,
  ...MODE_BRANDS,
  ...BOX_BEAUTE_BRANDS,
  ...RENTREE_BRANDS,
];
