import type { BrandDef } from "@/app/components/BrandFilter";

// Liste manuelle propre pour /categorie/bon-plan et /bons-plans-en-cours
// (validée par l'utilisateur, ajustée le 29 mai 2026).
export const BON_PLAN_BRANDS: BrandDef[] = [
  // Marketplaces & sites
  { key: "amazon", label: "Amazon", keywords: ["amazon"] },
  { key: "cdiscount", label: "Cdiscount", keywords: ["cdiscount"] },
  { key: "yesstyle", label: "YesStyle", keywords: ["yesstyle"] },
  { key: "lookfantastic", label: "Lookfantastic", keywords: ["lookfantastic"] },
  { key: "bebeboutik", label: "Bebeboutik", keywords: ["bebeboutik", "bébéboutik"] },
  { key: "showroom-prive", label: "Showroom Privé", keywords: ["showroom privé", "showroom prive", "showroom-prive", "showroomprive"] },
  { key: "greenweez", label: "Greenweez", keywords: ["greenweez"] },
  { key: "private-sport-shop", label: "Private Sport Shop", keywords: ["private sport shop", "private-sport-shop"] },
  { key: "zooplus", label: "Zooplus", keywords: ["zooplus", "zoo plus"] },
  { key: "mano-mano", label: "Mano Mano", keywords: ["mano mano", "manomano", "mano-mano"] },
  { key: "darty", label: "Darty", keywords: ["darty"] },
  // Cashback (catégorie large)
  { key: "cashback", label: "Cashback", keywords: ["cashback", "igraal", "ebuyclub", "poulpeo"] },
  // Beauté
  { key: "loreal", label: "L'Oréal", keywords: ["l'oréal", "l oreal", "loreal", "l'oreal", "loreal-paris", "l'oréal paris"] },
  { key: "garnier", label: "Garnier", keywords: ["garnier"] },
  { key: "maybelline", label: "Maybelline", keywords: ["maybelline"] },
  { key: "ghd", label: "GHD", keywords: ["ghd"] },
  { key: "dr-pierre-ricaud", label: "Dr Pierre Ricaud", keywords: ["dr pierre ricaud", "dr-pierre-ricaud", "pierre ricaud", "pierre-ricaud"] },
  { key: "lea-nature", label: "Léa Nature", keywords: ["léa nature", "lea nature", "lea-nature", "léa-nature"] },
  { key: "loccitane", label: "L'Occitane", keywords: ["l'occitane", "l occitane", "loccitane", "occitane"] },
  { key: "clarins", label: "Clarins", keywords: ["clarins"] },
  { key: "beauty-success", label: "Beauty Success", keywords: ["beauty success", "beauty-success", "beautysuccess"] },
  // Famille / bébé
  { key: "puericulture", label: "Puériculture", keywords: ["puériculture", "puericulture"] },
  { key: "pampers", label: "Pampers", keywords: ["pampers"] },
  { key: "pingo", label: "Pingo", keywords: ["pingo"] },
  { key: "biolane", label: "Biolane", keywords: ["biolane"] },
  { key: "greenweez", label: "Greenweez", keywords: ["greenweez"] },
  // K-Beauty (catégorie)
  { key: "kbeauty", label: "K-Beauty", keywords: ["k-beauty", "kbeauty", "k beauty"] },
  // Tech
  { key: "philips", label: "Philips", keywords: ["philips"] },
  { key: "samsung", label: "Samsung", keywords: ["samsung"] },
  { key: "dyson", label: "Dyson", keywords: ["dyson"] },
  { key: "oral-b", label: "Oral-B", keywords: ["oral-b", "oral b", "oralb"] },
  // Ajouts utilisateur
  { key: "thalgo", label: "Thalgo", keywords: ["thalgo"] },
  { key: "adopt", label: "Adopt'", keywords: ["adopt", "adopt-parfums", "adopt parfums", "adopt'"] },
  { key: "weleda", label: "Weleda", keywords: ["weleda"] },
  { key: "beaba", label: "Béaba", keywords: ["béaba", "beaba"] },
  { key: "stylvana", label: "Stylvana", keywords: ["stylvana", "stylevana"] },
  { key: "miin", label: "MiiN Cosmetics", keywords: ["miin", "miin cosmetics", "miin-cosmetics", "miin cosmetic"] },
  { key: "les-createurs-bio", label: "Les Créateurs Bio", keywords: ["les créateurs bio", "les createurs bio", "les-createurs-bio", "createurs bio", "createurs-bio"] },
  { key: "magnifaik", label: "Magnifaïk", keywords: ["magnifaïk", "magnifaik"] },
  { key: "atelier-du-sourcil", label: "L'Atelier du Sourcil", keywords: ["atelier du sourcil", "l'atelier du sourcil", "atelier-du-sourcil"] },
  { key: "pranarom", label: "Pranarôm", keywords: ["pranarôm", "pranarom"] },
  { key: "le-rouge-francais", label: "Le Rouge Français", keywords: ["le rouge français", "rouge français", "le-rouge-francais", "rouge-francais", "le rouge francais"] },
  { key: "mademoiselle-bio", label: "Mademoiselle Bio", keywords: ["mademoiselle bio", "mademoiselle-bio"] },
  { key: "rakuten", label: "Rakuten", keywords: ["rakuten"] },
  { key: "famille-mary", label: "Famille Mary", keywords: ["famille mary", "famille-mary"] },
  { key: "afibel", label: "Afibel", keywords: ["afibel"] },
  { key: "beaute-produit", label: "Beauté Produit", keywords: ["beauté produit", "beaute produit", "beaute-produit", "beauteproduit", "beaute-produit.com"] },
  { key: "daxon", label: "Daxon", keywords: ["daxon"] },
  { key: "laboratoire-biarritz", label: "Laboratoire Biarritz", keywords: ["laboratoire biarritz", "laboratoire-biarritz", "labo biarritz"] },
  { key: "news-parfums", label: "News Parfums", keywords: ["news parfums", "news-parfums", "newsparfums"] },
  { key: "blanche-porte", label: "Blanche Porte", keywords: ["blanche porte", "blanche-porte", "blancheporte"] },
  { key: "gemo", label: "Gémo", keywords: ["gémo", "gemo"] },
  { key: "damart", label: "Damart", keywords: ["damart"] },
];

// Hub /bons-plans-ninja : on filtre par gamme de produits Ninja
export const NINJA_BRANDS: BrandDef[] = [
  { key: "foodi", label: "Ninja Foodi (airfryer)", keywords: ["foodi", "ninja-foodi", "airfryer", "friteuse-sans-huile"] },
  { key: "creami", label: "Ninja CREAMi (glaces)", keywords: ["creami", "ninja-creami", "sorbetiere", "sorbetière"] },
  { key: "slushi", label: "Ninja SLUSHi (granités)", keywords: ["slushi", "ninja-slushi", "granité", "granite"] },
  { key: "crispi", label: "Ninja CRISPi (verre)", keywords: ["crispi", "ninja-crispi"] },
  { key: "blast", label: "Ninja Blast (blender)", keywords: ["blast", "ninja-blast", "blender"] },
  { key: "thirsti", label: "Ninja Thirsti (boissons)", keywords: ["thirsti", "ninja-thirsti"] },
  { key: "speedi", label: "Ninja Speedi (multicuiseur)", keywords: ["speedi", "ninja-speedi"] },
];

// Hub /bons-plans-tech
export const TECH_BRANDS: BrandDef[] = [
  { key: "acer", label: "Acer", keywords: ["acer"] },
  { key: "amazfit", label: "Amazfit", keywords: ["amazfit"] },
  { key: "apple", label: "Apple", keywords: ["apple", "macbook", "ipad", "airpods", "apple-watch", "iphone"] },
  { key: "samsung", label: "Samsung", keywords: ["samsung", "galaxy", "galaxy-watch", "galaxy-buds"] },
  { key: "google", label: "Google", keywords: ["google", "pixel", "pixel-watch", "pixel-buds"] },
  { key: "xiaomi", label: "Xiaomi / Redmi", keywords: ["xiaomi", "redmi", "mi-watch", "poco"] },
  { key: "huawei", label: "Huawei", keywords: ["huawei"] },
  { key: "oneplus", label: "OnePlus", keywords: ["oneplus", "one plus"] },
  { key: "sony", label: "Sony", keywords: ["sony", "playstation", "ps5"] },
  { key: "jbl", label: "JBL", keywords: ["jbl"] },
  { key: "bose", label: "Bose", keywords: ["bose"] },
  { key: "shokz", label: "Shokz", keywords: ["shokz"] },
  { key: "amazon", label: "Amazon", keywords: ["amazon", "kindle", "echo", "amazon-echo", "fire-tv"] },
  { key: "blackview", label: "Blackview", keywords: ["blackview"] },
  { key: "blink", label: "Blink", keywords: ["blink"] },
  { key: "cdiscount-tech", label: "Cdiscount", keywords: ["cdiscount"] },
  { key: "creality", label: "Creality", keywords: ["creality"] },
  { key: "darty-tech", label: "Darty", keywords: ["darty"] },
  { key: "electro-depot-tech", label: "Électro Dépôt", keywords: ["electro-depot", "electro dépôt"] },
  { key: "lg", label: "LG", keywords: ["lg"] },
  { key: "asus", label: "ASUS", keywords: ["asus", "rog"] },
  { key: "dell", label: "Dell", keywords: ["dell"] },
  { key: "hp", label: "HP", keywords: ["hp", "hewlett"] },
  { key: "lenovo", label: "Lenovo", keywords: ["lenovo"] },
  { key: "alienware", label: "Alienware", keywords: ["alienware"] },
  { key: "microsoft", label: "Microsoft", keywords: ["microsoft", "surface", "xbox"] },
  { key: "nintendo", label: "Nintendo", keywords: ["nintendo", "switch"] },
  { key: "logitech", label: "Logitech", keywords: ["logitech"] },
  { key: "razer", label: "Razer", keywords: ["razer"] },
  { key: "insta360", label: "Insta360", keywords: ["insta360", "insta 360"] },
  { key: "gopro", label: "GoPro", keywords: ["gopro", "go-pro"] },
  { key: "kodak", label: "Kodak", keywords: ["kodak"] },
  { key: "marshall", label: "Marshall", keywords: ["marshall"] },
  { key: "skullcandy", label: "Skullcandy", keywords: ["skullcandy"] },
  { key: "urbanglide", label: "UrbanGlide", keywords: ["urbanglide", "urban glide"] },
  { key: "anker", label: "Anker / Soundcore", keywords: ["anker", "soundcore"] },
  { key: "isinwheel", label: "Isinwheel", keywords: ["isinwheel"] },
  { key: "zigbuy-tech", label: "Zigbuy", keywords: ["zigbuy"] },
];

// Hub /bons-plans-maison (incl. cuisine), maintenu par ordre alphabétique.
export const MAISON_BRANDS: BrandDef[] = [
  { key: "amazon-maison", label: "Amazon", keywords: ["amazon"] },
  { key: "ariston", label: "Ariston", keywords: ["ariston"] },
  { key: "bissell", label: "Bissell", keywords: ["bissell"] },
  { key: "blancheporte-maison", label: "Blancheporte", keywords: ["blancheporte", "blanche-porte"] },
  { key: "bosch", label: "Bosch", keywords: ["bosch"] },
  { key: "calor", label: "Calor", keywords: ["calor"] },
  { key: "cecotec", label: "Cecotec", keywords: ["cecotec"] },
  { key: "cdiscount-maison", label: "Cdiscount", keywords: ["cdiscount"] },
  { key: "chiq", label: "CHiQ", keywords: ["chiq"] },
  { key: "comfee", label: "Comfee", keywords: ["comfee"] },
  { key: "coocheer", label: "Coocheer", keywords: ["coocheer"] },
  { key: "continental-edison", label: "Continental Edison", keywords: ["continental edison", "continental-edison"] },
  { key: "create", label: "Create", keywords: ["create"] },
  { key: "cuisinart", label: "Cuisinart", keywords: ["cuisinart"] },
  { key: "darty-maison", label: "Darty", keywords: ["darty"] },
  { key: "delonghi", label: "De'Longhi", keywords: ["delonghi", "de'longhi", "de longhi"] },
  { key: "dreame", label: "Dreame", keywords: ["dreame"] },
  { key: "dreo", label: "Dreo", keywords: ["dreo"] },
  { key: "dyson", label: "Dyson", keywords: ["dyson"] },
  { key: "ecovacs-maison", label: "Ecovacs", keywords: ["ecovacs", "deebot"] },
  { key: "electro-depot", label: "Électro Dépôt", keywords: ["electro-depot", "electro dépôt"] },
  { key: "electrolux", label: "Electrolux", keywords: ["electrolux"] },
  { key: "electactic", label: "Electactic", keywords: ["electactic"] },
  { key: "fairy", label: "Fairy", keywords: ["fairy"] },
  { key: "finish", label: "Finish", keywords: ["finish"] },
  { key: "fretta", label: "Fretta", keywords: ["fretta"] },
  { key: "lavazza", label: "Lavazza", keywords: ["lavazza"] },
  { key: "hisense", label: "Hisense", keywords: ["hisense"] },
  { key: "h-koenig", label: "H.Koenig", keywords: ["h-koenig", "h.koenig"] },
  { key: "honeywell", label: "Honeywell", keywords: ["honeywell"] },
  { key: "hoover", label: "Hoover", keywords: ["hoover"] },
  { key: "hydrofast", label: "Hydrofast", keywords: ["hydrofast"] },
  { key: "irobot", label: "iRobot / Roomba", keywords: ["irobot", "roomba"] },
  { key: "jimmy", label: "JIMMY", keywords: ["jimmy"] },
  { key: "karcher-maison", label: "Kärcher", keywords: ["kärcher", "karcher"] },
  { key: "kitchenaid", label: "KitchenAid", keywords: ["kitchenaid", "kitchen aid"] },
  { key: "klarstein", label: "Klarstein", keywords: ["klarstein"] },
  { key: "krups", label: "Krups", keywords: ["krups"] },
  { key: "lagrange", label: "Lagrange", keywords: ["lagrange"] },
  { key: "lefant", label: "Lefant", keywords: ["lefant"] },
  { key: "levoit", label: "Levoit", keywords: ["levoit"] },
  { key: "lg-elec", label: "LG (électroménager)", keywords: ["lg"] },
  { key: "magimix", label: "Magimix", keywords: ["magimix"] },
  { key: "manomano-maison", label: "ManoMano", keywords: ["manomano", "mano-mano"] },
  { key: "medion", label: "Medion", keywords: ["medion"] },
  { key: "midea", label: "Midea", keywords: ["midea"] },
  { key: "moulinex", label: "Moulinex", keywords: ["moulinex"] },
  { key: "narwal", label: "Narwal", keywords: ["narwal"] },
  { key: "nespresso", label: "Nespresso", keywords: ["nespresso"] },
  { key: "ninja", label: "Ninja", keywords: ["ninja", "foodi", "creami", "slushi", "crispi"] },
  { key: "novilla", label: "Novilla", keywords: ["novilla"] },
  { key: "olimpia-splendid", label: "Olimpia Splendid", keywords: ["olimpia splendid", "olimpia-splendid"] },
  { key: "philips", label: "Philips", keywords: ["philips"] },
  { key: "polti", label: "Polti", keywords: ["polti", "vaporetto"] },
  { key: "pro-breeze", label: "Pro Breeze", keywords: ["pro breeze", "pro-breeze"] },
  { key: "roborock", label: "Roborock", keywords: ["roborock"] },
  { key: "rotomatic", label: "Rotomatic", keywords: ["rotomatic"] },
  { key: "rowenta", label: "Rowenta", keywords: ["rowenta"] },
  { key: "russell-hobbs", label: "Russell Hobbs", keywords: ["russell hobbs", "russell-hobbs"] },
  { key: "samsung-elec", label: "Samsung (électroménager)", keywords: ["samsung"] },
  { key: "seb", label: "SEB", keywords: ["seb"] },
  { key: "severin", label: "Severin", keywords: ["severin"] },
  { key: "shark", label: "Shark", keywords: ["shark"] },
  { key: "tefal", label: "Tefal", keywords: ["tefal", "t-fal"] },
  { key: "tineco", label: "Tineco", keywords: ["tineco"] },
  { key: "ultenic", label: "Ultenic", keywords: ["ultenic"] },
  { key: "valberg", label: "Valberg", keywords: ["valberg"] },
  { key: "vevor-maison", label: "VEVOR", keywords: ["vevor"] },
  { key: "vorwerk", label: "Vorwerk / Thermomix", keywords: ["thermomix", "vorwerk"] },
  { key: "yankee-candle", label: "Yankee Candle", keywords: ["yankee candle", "yankee-candle"] },
  { key: "zigbuy-maison", label: "Zigbuy", keywords: ["zigbuy"] },
];

// Types de produits proposés dans le second menu de /bons-plans-maison.
export const MAISON_PRODUCT_TYPES: BrandDef[] = [
  { key: "lave-linge", label: "Lave-linge", keywords: ["lave-linge", "lave linge", "machine a laver", "machine à laver"] },
  { key: "seche-linge", label: "Sèche-linge", keywords: ["seche-linge", "sèche-linge", "seche linge", "sèche linge", "pompe a chaleur", "pompe à chaleur"] },
  { key: "lavante-sechante", label: "Lavantes-séchantes", keywords: ["lavante-sechante", "lavante-séchante", "lavant sechant", "lavant-séchant", "washtower"] },
  { key: "lave-vaisselle", label: "Lave-vaisselle", keywords: ["lave-vaisselle", "lave vaisselle"] },
  { key: "refrigerateurs", label: "Réfrigérateurs & congélateurs", keywords: ["refrigerateur", "réfrigérateur", "frigo", "congelateur", "congélateur"] },
  { key: "fours", label: "Fours & micro-ondes", keywords: ["four encastrable", "mini-four", "mini four", "micro-ondes", "micro ondes"] },
  { key: "cuisson", label: "Cuisson & multicuiseurs", keywords: ["airfryer", "friteuse", "multicuiseur", "cookeo", "robot cuiseur", "robot-cuiseur", "plaque de cuisson", "cuisiniere", "cuisinière"] },
  { key: "cafe", label: "Café & petit-déjeuner", keywords: ["machine a cafe", "machine à café", "machine-cafe", "cafetiere", "cafetière", "expresso", "broyeur", "grille-pain", "bouilloire"] },
  { key: "preparation", label: "Préparation culinaire", keywords: ["blender", "mixeur", "robot cuisine", "robot-cuisine", "extracteur de jus", "extracteur-de-jus", "sorbetiere", "sorbetière", "machine a pain", "machine à pain", "yaourtiere", "yaourtière"] },
  { key: "ustensiles", label: "Poêles, casseroles & ustensiles", keywords: ["poele", "poêle", "casserole", "batterie de cuisine", "batterie-cuisine", "cocotte", "faitout", "ingenio", "ustensile"] },
  { key: "aspirateurs", label: "Aspirateurs & robots", keywords: ["aspirateur", "robot laveur", "robot-laveur", "roomba", "deebot", "roborock"] },
  { key: "entretien", label: "Nettoyage & entretien", keywords: ["nettoyeur vapeur", "nettoyeur-vapeur", "nettoyeur sols", "nettoyeur-sols", "shampouineuse", "fer a repasser", "fer à repasser", "centrale vapeur"] },
  { key: "air", label: "Ventilation & qualité de l’air", keywords: ["ventilateur", "climatiseur", "purificateur d'air", "purificateur-air", "humidificateur", "deshumidificateur", "déshumidificateur"] },
  { key: "linge", label: "Linge de maison", keywords: ["linge de maison", "linge-de-maison", "drap", "couette", "oreiller", "housse de couette", "serviette de bain"] },
  { key: "meubles", label: "Meubles & rangement", keywords: ["meuble", "canape", "canapé", "armoire", "commode", "table basse", "chaise", "rangement", "bibliotheque", "bibliothèque"] },
  { key: "decoration", label: "Décoration & luminaires", keywords: ["decoration", "décoration", "luminaire", "lampe", "miroir", "tapis salon", "rideau"] },
];

// Hub /bons-plans-jardin (incl. outdoor, piscine)
export const JARDIN_BRANDS: BrandDef[] = [
  { key: "amazon-jardin", label: "Amazon", keywords: ["amazon"] },
  { key: "aferiy", label: "AFERIY", keywords: ["aferiy"] },
  { key: "black-decker", label: "Black+Decker", keywords: ["black+decker", "black decker", "black-decker"] },
  { key: "bosch-jardin", label: "Bosch", keywords: ["bosch"] },
  { key: "stihl", label: "Stihl", keywords: ["stihl"] },
  { key: "husqvarna", label: "Husqvarna", keywords: ["husqvarna"] },
  { key: "karcher", label: "Kärcher", keywords: ["kärcher", "karcher"] },
  { key: "worx", label: "Worx", keywords: ["worx"] },
  { key: "ryobi", label: "Ryobi", keywords: ["ryobi"] },
  { key: "makita", label: "Makita", keywords: ["makita"] },
  { key: "dewalt", label: "DeWalt", keywords: ["dewalt"] },
  { key: "einhell", label: "Einhell", keywords: ["einhell"] },
  { key: "gardena", label: "Gardena", keywords: ["gardena"] },
  { key: "segway", label: "Segway (Navimow)", keywords: ["segway", "navimow"] },
  { key: "mammotion", label: "Mammotion", keywords: ["mammotion"] },
  { key: "ecovacs", label: "Ecovacs", keywords: ["ecovacs"] },
  { key: "intex", label: "Intex", keywords: ["intex"] },
  { key: "bestway", label: "Bestway", keywords: ["bestway"] },
  { key: "weber", label: "Weber", keywords: ["weber"] },
  { key: "campingaz", label: "Campingaz", keywords: ["campingaz"] },
  { key: "cdiscount-jardin", label: "Cdiscount", keywords: ["cdiscount"] },
  { key: "ecoflow", label: "EcoFlow", keywords: ["ecoflow"] },
  { key: "tefal-bbq", label: "Tefal", keywords: ["tefal"] },
  { key: "broil-king", label: "Broil King", keywords: ["broil king", "broil-king"] },
  { key: "aiper", label: "Aiper", keywords: ["aiper"] },
  { key: "beatbot", label: "Beatbot", keywords: ["beatbot"] },
  { key: "wybot", label: "WYBOT", keywords: ["wybot"] },
  { key: "zodiac", label: "Zodiac", keywords: ["zodiac"] },
  // Animaux / animalerie
  { key: "feandrea", label: "Feandrea", keywords: ["feandrea"] },
  { key: "tractive", label: "Tractive", keywords: ["tractive"] },
  { key: "kippy", label: "Kippy", keywords: ["kippy"] },
  { key: "zooplus", label: "Zooplus", keywords: ["zooplus"] },
  { key: "edgard-cooper", label: "Edgard & Cooper", keywords: ["edgard cooper", "edgard-cooper"] },
  { key: "royal-canin", label: "Royal Canin", keywords: ["royal canin", "royal-canin"] },
  { key: "purina", label: "Purina", keywords: ["purina", "pro plan", "pro-plan"] },
  { key: "pawhut", label: "PawHut", keywords: ["pawhut"] },
  { key: "gitelsnour", label: "Gitelsnour", keywords: ["gitelsnour"] },
  { key: "petkit", label: "Petkit", keywords: ["petkit"] },
  { key: "savic", label: "Savic", keywords: ["savic"] },
  { key: "catit", label: "Catit", keywords: ["catit"] },
  { key: "flamingo", label: "Flamingo", keywords: ["flamingo"] },
  { key: "jackery", label: "Jackery", keywords: ["jackery"] },
  { key: "jummico", label: "JUMMICO", keywords: ["jummico"] },
  { key: "manomano-jardin", label: "ManoMano", keywords: ["manomano", "mano-mano"] },
  { key: "redkey", label: "Redkey", keywords: ["redkey"] },
  { key: "scheppach", label: "Scheppach", keywords: ["scheppach"] },
  { key: "songmics", label: "SONGMICS", keywords: ["songmics"] },
  { key: "stiga", label: "STIGA", keywords: ["stiga"] },
  { key: "tectake", label: "TecTake", keywords: ["tectake"] },
  { key: "ubpet", label: "UBPET", keywords: ["ubpet"] },
  { key: "vevor-jardin", label: "VEVOR", keywords: ["vevor"] },
];

// Types de produits proposés dans le second menu de /bons-plans-jardin.
export const JARDIN_PRODUCT_TYPES: BrandDef[] = [
  { key: "tondeuses", label: "Tondeuses à gazon", keywords: ["tondeuse a gazon", "tondeuse à gazon", "tondeuse thermique", "tondeuse electrique", "tondeuse électrique", "tondeuse autoportee", "tondeuse autoportée", "tracteur de jardin"] },
  { key: "robots-tondeuses", label: "Robots tondeuses", keywords: ["robot tondeuse", "robot-tondeuse", "automower", "navimow", "luba", "landroid"] },
  { key: "outils", label: "Outils de jardin", keywords: ["taille-haie", "taille haie", "debroussailleuse", "débroussailleuse", "coupe-bordure", "coupe bordure", "tronconneuse", "tronçonneuse", "souffleur", "motobineuse", "scarificateur"] },
  { key: "nettoyeurs", label: "Nettoyeurs haute pression", keywords: ["nettoyeur haute pression", "karcher", "kärcher", "nettoyeur terrasse"] },
  { key: "piscines", label: "Piscines & spas", keywords: ["piscine tubulaire", "piscine hors sol", "piscine gonflable", "spa gonflable", "jacuzzi", "spa intex", "spa bestway"] },
  { key: "robots-piscine", label: "Robots de piscine", keywords: ["robot piscine", "robot-piscine", "nettoyeur piscine", "aiper", "beatbot", "wybot", "bwt cosmy"] },
  { key: "parasols", label: "Parasols & protection solaire", keywords: ["parasol", "voile d'ombrage", "tonnelle", "pergola", "store banne"] },
  { key: "mobilier", label: "Mobilier de jardin", keywords: ["salon de jardin", "table de jardin", "chaise de jardin", "fauteuil de jardin", "transat", "chaise longue", "balancelle", "hamac", "bain de soleil"] },
  { key: "barbecue", label: "Barbecues & planchas", keywords: ["barbecue", "bbq", "plancha", "grill exterieur", "grill extérieur", "fumoir"] },
  { key: "arrosage", label: "Arrosage & pompes", keywords: ["arrosage", "tuyau d'arrosage", "arrosoir", "pompe a eau", "pompe à eau", "pompe immergee", "pompe immergée", "recuperateur d'eau", "récupérateur d'eau"] },
  { key: "abris", label: "Abris & rangement extérieur", keywords: ["abri de jardin", "coffre de jardin", "rangement exterieur", "rangement extérieur", "serre de jardin", "carport"] },
  { key: "camping", label: "Camping & plein air", keywords: ["camping", "tente", "sac de couchage", "matelas de camping", "glaciere", "glacière", "chaise de camping", "rechaud", "réchaud"] },
  { key: "animaux", label: "Animaux & animalerie", keywords: ["chien", "chat", "croquette", "litiere", "litière", "arbre a chat", "arbre à chat", "cage de transport", "remorque velo chien", "remorque vélo chien", "niche", "poulailler"] },
  { key: "decoration", label: "Décoration extérieure", keywords: ["decoration jardin", "décoration jardin", "luminaire exterieur", "luminaire extérieur", "lampe solaire", "fontaine de jardin", "brasero"] },
];

// Hub /bons-plans-beaute : sous-ensemble beauté de BON_PLAN_BRANDS
// Liste ordonnée alphabétiquement pour maintenance ; le dropdown utilisera
// le même ordre alpha via le prop `sortBrandsBy="alpha"`.
export const BEAUTE_BRANDS: BrandDef[] = [
  { key: "alga-maris", label: "Alga Maris", keywords: ["alga maris", "laboratoires de biarritz", "laboratoire de biarritz"] },
  { key: "adopt", label: "Adopt'", keywords: ["adopt", "adopt-parfums", "adopt parfums", "adopt'"] },
  { key: "amazon", label: "Amazon", keywords: ["amazon"] },
  { key: "andis", label: "Andis", keywords: ["andis"] },
  { key: "atelier-du-sourcil", label: "L'Atelier du Sourcil", keywords: ["atelier du sourcil", "atelier-du-sourcil"] },
  { key: "atida-beaute", label: "Atida", keywords: ["atida", "sante-discount"] },
  { key: "babyliss", label: "BaByliss", keywords: ["babyliss", "babylissmen"] },
  { key: "baija", label: "Baïja", keywords: ["baija", "baïja"] },
  { key: "beauty-of-joseon", label: "Beauty of Joseon", keywords: ["beauty of joseon", "beauty-of-joseon"] },
  { key: "beauty-success", label: "Beauty Success", keywords: ["beauty success", "beauty-success", "beautysuccess"] },
  { key: "bioderma", label: "Bioderma", keywords: ["bioderma"] },
  { key: "biotherm", label: "Biotherm", keywords: ["biotherm"] },
  { key: "biotyfull", label: "Biotyfull Box", keywords: ["biotyfull", "biotyfull-box", "biotyfull box"] },
  { key: "blissim", label: "Blissim", keywords: ["blissim"] },
  { key: "braun", label: "Braun", keywords: ["braun", "braun-silk-epil", "braun-series"] },
  { key: "caudalie", label: "Caudalie", keywords: ["caudalie"] },
  { key: "cerave", label: "CeraVe", keywords: ["cerave"] },
  { key: "chloe", label: "Chloé", keywords: ["chloé", "chloe"] },
  { key: "chanel", label: "Chanel", keywords: ["chanel", "chanel-parfum"] },
  { key: "christophe-robin", label: "Christophe Robin", keywords: ["christophe robin", "christophe-robin"] },
  { key: "clarins", label: "Clarins", keywords: ["clarins"] },
  { key: "clinique", label: "Clinique", keywords: ["clinique"] },
  { key: "cosrx", label: "CosRX", keywords: ["cosrx"] },
  { key: "cosmechic", label: "CosméChic", keywords: ["cosmechic", "cosméchic", "cosme chic"] },
  { key: "dr-pierre-ricaud", label: "Dr Pierre Ricaud", keywords: ["dr pierre ricaud", "dr-pierre-ricaud", "pierre ricaud", "pierre-ricaud"] },
  { key: "dyson", label: "Dyson", keywords: ["dyson"] },
  { key: "dior", label: "Dior", keywords: ["dior", "dior-parfum"] },
  { key: "elizabeth-arden", label: "Elizabeth Arden", keywords: ["elizabeth arden", "elizabeth-arden"] },
  { key: "erborian", label: "Erborian", keywords: ["erborian"] },
  { key: "essence", label: "Essence", keywords: ["essence", "essence-cosmetics"] },
  { key: "famille-mary", label: "Famille Mary", keywords: ["famille mary", "famille-mary"] },
  { key: "foreo", label: "Foreo", keywords: ["foreo"] },
  { key: "garancia", label: "Garancia", keywords: ["garancia"] },
  { key: "garnier", label: "Garnier", keywords: ["garnier"] },
  { key: "greenweez-beaute", label: "Greenweez", keywords: ["greenweez"] },
  { key: "guerlain", label: "Guerlain", keywords: ["guerlain"] },
  { key: "ghd", label: "GHD", keywords: ["ghd"] },
  { key: "gillette", label: "Gillette", keywords: ["gillette", "gillette-labs"] },
  { key: "glowria", label: "Glowria", keywords: ["glowria"] },
  { key: "institut-esthederm", label: "Institut Esthederm", keywords: ["institut esthederm", "institut-esthederm", "esthederm"] },
  { key: "ioma", label: "IOMA", keywords: ["ioma"] },
  { key: "isdin", label: "ISDIN", keywords: ["isdin"] },
  { key: "kbeauty", label: "K-Beauty", keywords: ["k-beauty", "kbeauty", "k beauty"] },
  { key: "kerargan", label: "Kerargan", keywords: ["kerargan"] },
  { key: "kerastase", label: "Kérastase", keywords: ["kerastase", "kérastase"] },
  { key: "kiko", label: "Kiko Milano", keywords: ["kiko", "kiko-milano"] },
  { key: "la-roche-posay", label: "La Roche-Posay", keywords: ["la roche-posay", "la-roche-posay", "la roche posay", "roche-posay"] },
  { key: "lea-nature", label: "Léa Nature", keywords: ["léa nature", "lea nature", "lea-nature", "léa-nature"] },
  { key: "le-rouge-francais", label: "Le Rouge Français", keywords: ["le rouge français", "rouge français", "le-rouge-francais", "rouge-francais"] },
  { key: "loccitane", label: "L'Occitane", keywords: ["l'occitane", "l occitane", "loccitane", "occitane"] },
  { key: "lookfantastic", label: "Lookfantastic", keywords: ["lookfantastic"] },
  { key: "loreal", label: "L'Oréal", keywords: ["l'oréal", "l oreal", "loreal", "loreal-paris", "l'oréal paris"] },
  { key: "lancome", label: "Lancôme", keywords: ["lancome", "lancôme"] },
  { key: "lierac", label: "Lierac", keywords: ["lierac"] },
  { key: "mademoiselle-bio", label: "Mademoiselle Bio", keywords: ["mademoiselle bio", "mademoiselle-bio"] },
  { key: "magnifaik", label: "Magnifaïk", keywords: ["magnifaïk", "magnifaik"] },
  { key: "maybelline", label: "Maybelline", keywords: ["maybelline"] },
  { key: "marilou-bio", label: "Marilou Bio", keywords: ["marilou bio", "marilou-bio"] },
  { key: "medicube", label: "Medicube", keywords: ["medicube"] },
  { key: "melvita", label: "Melvita", keywords: ["melvita"] },
  { key: "miin", label: "MiiN Cosmetics", keywords: ["miin", "miin cosmetics", "miin-cosmetics"] },
  { key: "mixa", label: "Mixa", keywords: ["mixa"] },
  { key: "news-parfums", label: "News Parfums", keywords: ["news parfums", "news-parfums"] },
  { key: "nooance", label: "Nooance", keywords: ["nooance"] },
  { key: "nivea", label: "Nivea", keywords: ["nivea"] },
  { key: "nuxe", label: "Nuxe", keywords: ["nuxe"] },
  { key: "nyx", label: "NYX Professional Makeup", keywords: ["nyx", "nyx-professional-makeup"] },
  { key: "olaplex", label: "Olaplex", keywords: ["olaplex"] },
  { key: "oral-b", label: "Oral-B", keywords: ["oral-b", "oral b", "oralb"] },
  { key: "perfumes-club", label: "Perfumes Club", keywords: ["perfumes club", "perfumes-club", "perfumesclub"] },
  { key: "pin-up-secret", label: "Pin Up Secret", keywords: ["pin up secret", "pin-up-secret", "pinup secret"] },
  { key: "philips", label: "Philips", keywords: ["philips"] },
  { key: "pranarom", label: "Pranarôm", keywords: ["pranarôm", "pranarom"] },
  { key: "remington", label: "Remington", keywords: ["remington"] },
  { key: "rosebaie", label: "RoseBaie", keywords: ["rosebaie", "rose baie"] },
  { key: "seasonly-beaute", label: "Seasonly", keywords: ["seasonly"] },
  { key: "sephora", label: "Sephora", keywords: ["sephora"] },
  { key: "so-bio-etic", label: "So'Bio Étic", keywords: ["so'bio etic", "so bio etic", "so-bio-etic", "sobio", "so'bio"] },
  { key: "stylvana", label: "Stylevana", keywords: ["stylvana", "stylevana"] },
  { key: "schwarzkopf", label: "Schwarzkopf", keywords: ["schwarzkopf"] },
  { key: "thalgo", label: "Thalgo", keywords: ["thalgo"] },
  { key: "the-ordinary", label: "The Ordinary", keywords: ["the ordinary", "the-ordinary", "ordinary"] },
  { key: "uriage", label: "Uriage", keywords: ["uriage"] },
  { key: "vichy", label: "Vichy", keywords: ["vichy"] },
  { key: "wahl", label: "Wahl", keywords: ["wahl"] },
  { key: "weleda", label: "Weleda", keywords: ["weleda"] },
  { key: "yesstyle", label: "YesStyle", keywords: ["yesstyle"] },
  { key: "yves-rocher", label: "Yves Rocher", keywords: ["yves rocher", "yves-rocher", "yvesrocher"] },
  { key: "yves-saint-laurent", label: "Yves Saint Laurent", keywords: ["yves saint laurent", "yves-saint-laurent", "ysl"] },
];

// Hub /bons-plans-bebe : marques bébé / puériculture.
// Liste maintenue par ordre alphabétique ; le composant applique également
// un tri alphabétique afin que l'ordre reste stable avec les compteurs.
export const BEBE_BRANDS: BrandDef[] = [
  { key: "acorelle", label: "Acorelle", keywords: ["acorelle"] },
  { key: "amazon", label: "Amazon", keywords: ["amazon"] },
  { key: "aolso", label: "Aolso", keywords: ["aolso"] },
  { key: "badabulle", label: "Badabulle", keywords: ["badabulle"] },
  { key: "baby-einstein", label: "Baby Einstein", keywords: ["baby einstein", "baby-einstein"] },
  { key: "babybjorn", label: "BabyBjörn", keywords: ["babybjorn", "babybjörn"] },
  { key: "babymoov", label: "Babymoov", keywords: ["babymoov"] },
  { key: "babyzen", label: "Babyzen", keywords: ["babyzen", "yoyo"] },
  { key: "beaba", label: "Béaba", keywords: ["béaba", "beaba"] },
  { key: "bebe-confort", label: "Bébé Confort", keywords: ["bébé confort", "bebe confort", "bebe-confort", "bebeconfort"] },
  { key: "bebeboutik", label: "Bebeboutik", keywords: ["bebeboutik", "bébéboutik"] },
  { key: "bioregena", label: "Bioregena", keywords: ["bioregena"] },
  { key: "bledina", label: "Blédina", keywords: ["blédina", "bledina"] },
  { key: "bioderma", label: "Bioderma", keywords: ["bioderma"] },
  { key: "biolane", label: "Biolane", keywords: ["biolane"] },
  { key: "bright-starts", label: "Bright Starts", keywords: ["bright starts", "bright-starts"] },
  { key: "carrefour", label: "Carrefour", keywords: ["carrefour"] },
  { key: "chicco", label: "Chicco", keywords: ["chicco"] },
  { key: "childhome", label: "Childhome", keywords: ["childhome"] },
  { key: "cybex", label: "Cybex", keywords: ["cybex"] },
  { key: "dbb-remond", label: "dBb Remond", keywords: ["dbb-remond", "dbb remond"] },
  { key: "elvie", label: "Elvie", keywords: ["elvie"] },
  { key: "fisher-price", label: "Fisher-Price", keywords: ["fisher-price", "fisher price"] },
  { key: "greenweez", label: "Greenweez", keywords: ["greenweez"] },
  { key: "grownsy", label: "GROWNSY", keywords: ["grownsy"] },
  { key: "huggies", label: "Huggies", keywords: ["huggies", "huggies pure"] },
  { key: "ingenuity", label: "Ingenuity", keywords: ["ingenuity"] },
  { key: "jane", label: "Jané", keywords: ["jané", "jane-bebe", "jane bebe"] },
  { key: "jonzac", label: "Eau Thermale Jonzac", keywords: ["eau thermale jonzac", "jonzac"] },
  { key: "joie", label: "Joie", keywords: ["joie"] },
  { key: "kesser", label: "Kesser", keywords: ["kesser"] },
  { key: "kinderkraft", label: "Kinderkraft", keywords: ["kinderkraft"] },
  { key: "la-boite-rose-bebe", label: "La Boîte Rose", keywords: ["la boîte rose", "la boite rose", "la-boite-rose"] },
  { key: "lionelo", label: "Lionelo", keywords: ["lionelo"] },
  { key: "mam", label: "MAM", keywords: ["mam-bebe", "mam bebe"] },
  { key: "maxi-cosi", label: "Maxi-Cosi", keywords: ["maxi-cosi", "maxi cosi", "maxicosi"] },
  { key: "medi-partners", label: "Medi Partners", keywords: ["medi partners", "medi-partners"] },
  { key: "medela", label: "Medela", keywords: ["medela"] },
  { key: "momcozy", label: "Momcozy", keywords: ["momcozy"] },
  { key: "mustela", label: "Mustela", keywords: ["mustela"] },
  { key: "nania", label: "Nania", keywords: ["nania"] },
  { key: "nuby", label: "Nuby", keywords: ["nuby"] },
  { key: "nuk", label: "NUK", keywords: ["nuk"] },
  { key: "nuliie", label: "Nuliie", keywords: ["nuliie"] },
  { key: "pampers", label: "Pampers", keywords: ["pampers"] },
  { key: "philips-avent", label: "Philips Avent", keywords: ["philips avent", "philips-avent", "avent"] },
  { key: "pingo", label: "Pingo", keywords: ["pingo"] },
  { key: "pranarom", label: "Pranarôm / PranaBB", keywords: ["pranarôm", "pranarom", "pranabb"] },
  { key: "roba", label: "Roba", keywords: ["roba"] },
  { key: "sophie-la-girafe", label: "Sophie la girafe", keywords: ["sophie la girafe", "sophie-la-girafe"] },
  { key: "stokke", label: "Stokke", keywords: ["stokke"] },
  { key: "thermobaby", label: "Thermobaby", keywords: ["thermobaby"] },
  { key: "tidoo", label: "Tidoo", keywords: ["tidoo"] },
  { key: "tigex", label: "Tigex", keywords: ["tigex"] },
  { key: "tommee-tippee", label: "Tommee Tippee", keywords: ["tommee tippee", "tommee-tippee"] },
  { key: "totsy-baby", label: "Totsy Baby", keywords: ["totsy baby", "totsy-baby"] },
  { key: "vertbaudet", label: "Vertbaudet", keywords: ["vertbaudet"] },
  { key: "vtech", label: "VTech", keywords: ["vtech", "v-tech"] },
  { key: "waterwipes", label: "WaterWipes", keywords: ["waterwipes"] },
  { key: "weleda", label: "Weleda", keywords: ["weleda"] },
  { key: "yoomum", label: "YooMum", keywords: ["yoomum", "yoo mum"] },
  { key: "zeeman", label: "Zeeman", keywords: ["zeeman"] },
];

// Types de produits proposés dans le second menu de /bons-plans-bebe.
// La recherche porte sur le titre, la description, le slug et les tags.
export const BEBE_PRODUCT_TYPES: BrandDef[] = [
  { key: "couches", label: "Couches & change", keywords: ["couche", "lingette", "table a langer", "table à langer", "matelas a langer", "matelas à langer"] },
  { key: "biberons", label: "Biberons & repas", keywords: ["biberon", "tetine", "tétine", "sucette", "babycook", "chauffe-biberon", "repas bebe", "repas bébé", "vaisselle bebe", "vaisselle bébé"] },
  { key: "allaitement", label: "Allaitement", keywords: ["allaitement", "tire-lait", "coussin d'allaitement", "crevasses"] },
  { key: "poussettes", label: "Poussettes & sorties", keywords: ["poussette", "landau", "porte-bebe", "porte-bébé", "sac a langer", "sac à langer", "nid d'ange", "nid-dange", "chanceliere", "chancelière"] },
  { key: "sieges-auto", label: "Sièges auto", keywords: ["siege auto", "siège auto", "siege-auto", "cosi", "coque auto", "rehausseur"] },
  { key: "sommeil", label: "Sommeil & chambre", keywords: ["lit bebe", "lit bébé", "lit parapluie", "cododo", "berceau", "matelas bebe", "matelas bébé", "veilleuse", "babyphone", "chambre bebe", "chambre bébé"] },
  { key: "toilette", label: "Toilette & soins", keywords: ["bain bebe", "bain bébé", "baignoire", "thermometre", "thermomètre", "soin bebe", "soin bébé", "gel lavant", "savon bebe", "savon bébé", "liniment", "mouche-bebe", "mouche-bébé"] },
  { key: "vetements", label: "Vêtements bébé", keywords: ["vetement bebe", "vêtement bébé", "vêtements bébé", "body bebe", "body bébé", "pyjama bebe", "pyjama bébé", "grenouillere", "grenouillère", "chaussons bebe", "chaussons bébé"] },
  { key: "jouets", label: "Jouets & éveil", keywords: ["jouet bebe", "jouet bébé", "eveil bebe", "éveil bébé", "hochet", "tapis d'eveil", "tapis d'éveil", "doudou", "sophie la girafe", "transat bebe", "transat bébé"] },
  { key: "mobilier", label: "Mobilier bébé", keywords: ["chaise haute", "chaise-haute", "fauteuil bebe", "fauteuil bébé", "mobilier bebe", "mobilier bébé", "commode bebe", "commode bébé"] },
];

// Hub /bons-plans-jouets (LEGO, Playmobil, jeux de société, peluches, poupées, jouets éducatifs)
export const JOUETS_BRANDS: BrandDef[] = [
  { key: "amazon", label: "Amazon", keywords: ["amazon"] },
  { key: "bebeboutik-jouets", label: "Bebeboutik", keywords: ["bebeboutik", "bébéboutik"] },
  { key: "carrefour-jouets", label: "Carrefour", keywords: ["carrefour"] },
  { key: "creabul-jouets", label: "Créabul", keywords: ["créabul", "creabul"] },
  { key: "greenweez-jouets", label: "Greenweez", keywords: ["greenweez"] },
  { key: "hape", label: "Hape", keywords: ["hape"] },
  { key: "lansay", label: "Lansay", keywords: ["lansay"] },
  { key: "lego", label: "LEGO", keywords: ["lego"] },
  { key: "playmobil", label: "Playmobil", keywords: ["playmobil"] },
  { key: "mattel", label: "Mattel", keywords: ["mattel"] },
  { key: "barbie", label: "Barbie", keywords: ["barbie"] },
  { key: "hot-wheels", label: "Hot Wheels", keywords: ["hot wheels", "hot-wheels"] },
  { key: "hasbro", label: "Hasbro", keywords: ["hasbro"] },
  { key: "monopoly", label: "Monopoly", keywords: ["monopoly"] },
  { key: "nerf", label: "Nerf", keywords: ["nerf"] },
  { key: "ravensburger", label: "Ravensburger", keywords: ["ravensburger"] },
  { key: "asmodee", label: "Asmodee", keywords: ["asmodee"] },
  { key: "djeco", label: "Djeco", keywords: ["djeco"] },
  { key: "haba", label: "Haba", keywords: ["haba"] },
  { key: "vtech", label: "Vtech", keywords: ["vtech", "v-tech"] },
  { key: "fisher-price", label: "Fisher-Price", keywords: ["fisher-price", "fisher price"] },
  { key: "schleich", label: "Schleich", keywords: ["schleich"] },
  { key: "sylvanian-families", label: "Sylvanian Families", keywords: ["sylvanian families", "sylvanian-families"] },
  { key: "funko-pop", label: "Funko Pop", keywords: ["funko", "funko-pop"] },
  { key: "squishmallows", label: "Squishmallows", keywords: ["squishmallows"] },
  { key: "pokemon", label: "Pokémon", keywords: ["pokemon", "pokémon"] },
  { key: "disney", label: "Disney", keywords: ["disney"] },
  { key: "marvel", label: "Marvel", keywords: ["marvel"] },
  { key: "star-wars", label: "Star Wars", keywords: ["star wars", "star-wars"] },
  { key: "crayola", label: "Crayola", keywords: ["crayola"] },
  { key: "smoby", label: "Smoby", keywords: ["smoby"] },
  { key: "play-doh", label: "Play-Doh", keywords: ["play-doh", "play doh"] },
  { key: "bandai", label: "Bandai", keywords: ["bandai"] },
  { key: "tiptoi", label: "Tiptoi", keywords: ["tiptoi"] },
  { key: "barbie-extra", label: "Barbie Extra", keywords: ["barbie extra"] },
];

// Types de jouets proposés dans le second menu de /bons-plans-jouets.
export const JOUETS_PRODUCT_TYPES: BrandDef[] = [
  { key: "vehicules", label: "Voitures & véhicules", keywords: ["voiture", "vehicule", "véhicule", "camion", "garage", "circuit", "hot wheels", "train jouet", "tracteur jouet"] },
  { key: "poupees", label: "Poupées & poupons", keywords: ["poupee", "poupée", "poupon", "barbie", "polly pocket", "maison de poupee", "maison de poupée"] },
  { key: "construction", label: "Jeux de construction", keywords: ["lego", "playmobil", "jeu de construction", "jeux de construction", "briques", "meccano", "kapla"] },
  { key: "societe", label: "Jeux de société & cartes", keywords: ["jeu de societe", "jeu de société", "jeux de societe", "jeux de société", "jeu de cartes", "monopoly", "dixit", "catan", "unlock", "trivial pursuit"] },
  { key: "peluches", label: "Peluches & doudous", keywords: ["peluche", "doudou", "squishmallow"] },
  { key: "figurines", label: "Figurines & univers", keywords: ["figurine", "funko", "sylvanian", "schleich", "pokemon", "pokémon", "transformers"] },
  { key: "educatifs", label: "Jeux éducatifs & éveil", keywords: ["jouet educatif", "jouet éducatif", "jeu educatif", "jeu éducatif", "eveil", "éveil", "vtech", "fisher-price", "tiptoi", "montessori"] },
  { key: "creatifs", label: "Loisirs créatifs", keywords: ["kit creatif", "kit créatif", "loisir creatif", "loisir créatif", "coloriage", "peinture", "pate a modeler", "pâte à modeler", "play-doh", "perles"] },
  { key: "puzzles", label: "Puzzles", keywords: ["puzzle", "puzzles"] },
  { key: "plein-air", label: "Jeux de plein air", keywords: ["plein air", "exterieur", "extérieur", "toboggan", "balancoire", "balançoire", "trampoline", "cabane enfant", "bac a sable", "bac à sable", "pistolet a eau", "pistolet à eau"] },
  { key: "radiocommandes", label: "Jouets télécommandés", keywords: ["telecommande", "télécommande", "radiocommande", "radiocommandé", "drone enfant", "robot jouet"] },
  { key: "deguisements", label: "Déguisements", keywords: ["deguisement", "déguisement", "costume enfant", "masque enfant"] },
];

// Hub /bons-plans-mode (mode, chaussures, montres analogiques, sacs, accessoires)
export const MODE_BRANDS: BrandDef[] = [
  { key: "amazon", label: "Amazon", keywords: ["amazon"] },
  { key: "caroll", label: "Caroll", keywords: ["caroll"] },
  { key: "degriffstock", label: "Dégriffstock", keywords: ["degriffstock", "dégriffstock"] },
  { key: "geox", label: "Geox", keywords: ["geox"] },
  { key: "histoire-or", label: "Histoire d'Or", keywords: ["histoire d'or", "histoire dor", "histoire-dor"] },
  { key: "kiabi-mode", label: "Kiabi", keywords: ["kiabi"] },
  { key: "lollipops", label: "Lollipops", keywords: ["lollipops"] },
  { key: "magnifaik-mode", label: "Magnifaïk", keywords: ["magnifaïk", "magnifaik"] },
  { key: "one-watch-company", label: "One Watch Company", keywords: ["one watch company", "one-watch-company"] },
  { key: "prozis-mode", label: "Prozis", keywords: ["prozis"] },
  { key: "sans-complexe", label: "Sans Complexe", keywords: ["sans complexe", "sans-complexe"] },
  { key: "spartoo", label: "Spartoo", keywords: ["spartoo"] },
  // Sport / sneakers
  { key: "nike", label: "Nike", keywords: ["nike", "jordan", "nike-jordan"] },
  { key: "adidas", label: "Adidas", keywords: ["adidas"] },
  { key: "puma", label: "Puma", keywords: ["puma"] },
  { key: "reebok", label: "Reebok", keywords: ["reebok"] },
  { key: "asics", label: "Asics", keywords: ["asics"] },
  { key: "hoka", label: "Hoka", keywords: ["hoka", "hoka-one-one"] },
  { key: "salomon", label: "Salomon", keywords: ["salomon"] },
  { key: "new-balance", label: "New Balance", keywords: ["new-balance", "new balance"] },
  { key: "converse", label: "Converse", keywords: ["converse"] },
  { key: "vans", label: "Vans", keywords: ["vans"] },
  // Mode premium / casual
  { key: "lacoste", label: "Lacoste", keywords: ["lacoste"] },
  { key: "tommy-hilfiger", label: "Tommy Hilfiger", keywords: ["tommy-hilfiger", "tommy hilfiger", "tommy"] },
  { key: "calvin-klein", label: "Calvin Klein", keywords: ["calvin-klein", "calvin klein"] },
  { key: "levis", label: "Levi's", keywords: ["levis", "levi's", "levi-s"] },
  { key: "jott", label: "Jott", keywords: ["jott"] },
  { key: "quiksilver", label: "Quiksilver", keywords: ["quiksilver"] },
  // Chaussures
  { key: "bata", label: "Bata", keywords: ["bata"] },
  { key: "birkenstock", label: "Birkenstock", keywords: ["birkenstock"] },
  { key: "crocs", label: "Crocs", keywords: ["crocs"] },
  { key: "chaussea", label: "Chaussea", keywords: ["chaussea"] },
  // Bagagerie / sacs
  { key: "eastpak", label: "Eastpak", keywords: ["eastpak"] },
  { key: "delsey", label: "Delsey", keywords: ["delsey"] },
  { key: "samsonite", label: "Samsonite", keywords: ["samsonite"] },
  // Lunettes
  { key: "ray-ban", label: "Ray-Ban", keywords: ["ray-ban", "ray ban", "rayban"] },
  // Enseignes mode FR
  { key: "la-halle", label: "La Halle", keywords: ["la halle", "la-halle"] },
  { key: "gemo", label: "Gémo", keywords: ["gémo", "gemo"] },
  { key: "showroom-prive", label: "Showroom Privé", keywords: ["showroom prive", "showroom privé", "showroomprive", "showroom-prive"] },
  { key: "le-slip-francais", label: "Le Slip Français", keywords: ["le slip français", "le slip francais", "le-slip-francais", "slip-francais"] },
  { key: "monsieur-tshirt", label: "Monsieur Tshirt", keywords: ["monsieur tshirt", "monsieur-tshirt"] },
  { key: "blanche-porte", label: "Blanche Porte", keywords: ["blanche porte", "blanche-porte", "blancheporte"] },
  { key: "afibel", label: "Afibel", keywords: ["afibel"] },
  { key: "damart", label: "Damart", keywords: ["damart"] },
  { key: "daxon", label: "Daxon", keywords: ["daxon"] },
  { key: "private-sport-shop", label: "Private Sport Shop", keywords: ["private sport shop", "private-sport-shop"] },
];

// Types de produits proposés dans le second menu de /bons-plans-mode.
export const MODE_PRODUCT_TYPES: BrandDef[] = [
  { key: "chaussures", label: "Chaussures & baskets", keywords: ["chaussure", "basket", "sneaker", "running", "sandale", "escarpin", "botte", "bottine", "mocassin", "chausson"] },
  { key: "sacs", label: "Sacs & bagagerie", keywords: ["sac a main", "sac à main", "sac a dos", "sac à dos", "sac bandouliere", "sac bandoulière", "cabas", "tote bag", "bagagerie", "valise", "maroquinerie"] },
  { key: "femme", label: "Vêtements femme", keywords: ["mode femme", "vetement femme", "vêtement femme", "robe", "jupe", "chemisier", "blouse femme", "pantalon femme", "manteau femme", "veste femme"] },
  { key: "homme", label: "Vêtements homme", keywords: ["mode homme", "vetement homme", "vêtement homme", "chemise homme", "pantalon homme", "costume homme", "manteau homme", "veste homme", "polo homme"] },
  { key: "enfant", label: "Vêtements enfant", keywords: ["mode enfant", "vetement enfant", "vêtement enfant", "fille", "garcon", "garçon", "ado", "kids"] },
  { key: "sport", label: "Vêtements de sport", keywords: ["vetement sport", "vêtement sport", "legging", "brassiere", "brassière", "survetement", "survêtement", "short sport", "maillot sport", "tenue sport"] },
  { key: "lingerie", label: "Lingerie & sous-vêtements", keywords: ["lingerie", "sous-vetement", "sous-vêtement", "soutien-gorge", "culotte", "boxer", "slip", "chaussette"] },
  { key: "manteaux", label: "Manteaux & vestes", keywords: ["manteau", "veste", "blouson", "doudoune", "parka", "impermeable", "imperméable"] },
  { key: "hauts", label: "T-shirts, pulls & sweats", keywords: ["t-shirt", "tee-shirt", "pull", "sweat", "hoodie", "polo", "debardeur", "débardeur"] },
  { key: "bas", label: "Jeans, pantalons & shorts", keywords: ["jean", "pantalon", "short", "bermuda", "jogging"] },
  { key: "montres", label: "Montres", keywords: ["montre analogique", "montre automatique", "montre quartz", "montre homme", "montre femme"] },
  { key: "bijoux", label: "Bijoux", keywords: ["bijou", "collier", "bracelet", "boucle d'oreille", "boucles d'oreilles", "bague", "pendentif"] },
  { key: "accessoires", label: "Accessoires de mode", keywords: ["accessoire mode", "lunette de soleil", "lunettes de soleil", "ceinture", "casquette", "bonnet", "echarpe", "écharpe", "foulard", "portefeuille"] },
];

// Liste manuelle des box beauté présentes sur le site
export const BOX_BEAUTE_BRANDS: BrandDef[] = [
  { key: "biotyfull", label: "Biotyfull Box", keywords: ["biotyfull", "biotyfull-box", "biotyfull box"] },
  { key: "blissim", label: "Blissim", keywords: ["blissim"] },
  { key: "glowria", label: "Glowria", keywords: ["glowria"] },
  { key: "lookfantastic", label: "Lookfantastic", keywords: ["lookfantastic"] },
  { key: "prescription-lab", label: "Prescription Lab", keywords: ["prescription lab", "prescription-lab", "prescriptionlab"] },
  { key: "my-little-box", label: "My Little Box", keywords: ["my little box", "my-little-box", "mylittlebox"] },
  { key: "my-beauty-factory", label: "My Beauty Factory", keywords: ["my beauty factory", "my-beauty-factory", "mybeautyfactory"] },
  { key: "laromabox", label: "L'Arôma Box", keywords: ["laromabox", "l-aroma-box", "l'aroma box", "larômabox", "l'arôma box", "aroma box"] },
  { key: "belle-au-naturel", label: "Belle au Naturel", keywords: ["belle au naturel", "belle-au-naturel"] },
  { key: "mademoiselle-bio", label: "Mademoiselle Bio", keywords: ["mademoiselle bio", "mademoiselle-bio"] },
  { key: "mademoiselle-confettis", label: "Mademoiselle Confettis", keywords: ["mademoiselle confettis", "mademoiselle-confettis"] },
  { key: "nuoo", label: "Nuoo", keywords: ["nuoo"] },
];

// Hub /bons-plans-rentree : fournitures scolaires + cartables + agendas + coloriage éducatif
export const RENTREE_BRANDS: BrandDef[] = [
  { key: "amazon", label: "Amazon", keywords: ["amazon"] },
  { key: "beaba-rentree", label: "Béaba", keywords: ["béaba", "beaba"] },
  { key: "bic", label: "BIC", keywords: ["bic", "bic-kids"] },
  { key: "carrefour-rentree", label: "Carrefour", keywords: ["carrefour"] },
  { key: "cmonetiquette", label: "C-MonEtiquette", keywords: ["c-monetiquette", "c mon etiquette", "cmonetiquette"] },
  { key: "doyomtoy", label: "Doyomtoy", keywords: ["doyomtoy"] },
  { key: "greenweez-rentree", label: "Greenweez", keywords: ["greenweez"] },
  { key: "homcom", label: "HOMCOM", keywords: ["homcom"] },
  { key: "kinspory", label: "Kinspory", keywords: ["kinspory"] },
  { key: "maped", label: "Maped", keywords: ["maped", "color-peps"] },
  { key: "milan-jeunesse", label: "Milan Jeunesse", keywords: ["milan jeunesse", "milan-jeunesse"] },
  { key: "stabilo", label: "STABILO", keywords: ["stabilo", "stabilo-boss"] },
  { key: "clairefontaine", label: "Clairefontaine", keywords: ["clairefontaine"] },
  { key: "oxford", label: "Oxford", keywords: ["oxford"] },
  { key: "faber-castell", label: "Faber-Castell", keywords: ["faber-castell", "faber castell"] },
  { key: "staedtler", label: "Staedtler", keywords: ["staedtler"] },
  { key: "pilot", label: "Pilot", keywords: ["pilot", "pilot-frixion", "frixion"] },
  { key: "paper-mate", label: "Paper Mate", keywords: ["paper mate", "paper-mate"] },
  { key: "post-it", label: "Post-it", keywords: ["post-it", "post it", "3m"] },
  { key: "private-sport-shop-rentree", label: "Private Sport Shop", keywords: ["private sport shop", "private-sport-shop"] },
  { key: "rougier-ple", label: "Rougier & Plé", keywords: ["rougier & plé", "rougier et plé", "rougier-ple"] },
  { key: "sharpie", label: "Sharpie", keywords: ["sharpie"] },
  { key: "scotch", label: "Scotch", keywords: ["scotch"] },
  { key: "posca", label: "Posca", keywords: ["posca"] },
  { key: "canson", label: "Canson", keywords: ["canson"] },
  { key: "crayola", label: "Crayola", keywords: ["crayola"] },
  { key: "minecraft", label: "Minecraft", keywords: ["minecraft"] },
  { key: "roblox", label: "Roblox", keywords: ["roblox"] },
  { key: "casio", label: "Casio", keywords: ["casio"] },
  { key: "texas-instruments", label: "Texas Instruments", keywords: ["texas instruments", "texas-instruments"] },
  { key: "tanns", label: "Tann's", keywords: ["tann's", "tanns", "tann-s"] },
];

// Types de produits proposés dans le second menu de /bons-plans-rentree.
export const RENTREE_PRODUCT_TYPES: BrandDef[] = [
  { key: "ecriture", label: "Crayons, stylos & feutres", keywords: ["crayon", "stylo", "feutre", "surligneur", "stabilo", "frixion", "porte-mine", "marqueur", "bic"] },
  { key: "cahiers", label: "Cahiers, feuilles & classeurs", keywords: ["cahier", "feuille", "copie double", "classeur", "intercalaire", "pochette plastique", "bloc note", "bloc-notes", "repertoire", "répertoire"] },
  { key: "cartables", label: "Cartables & sacs à dos", keywords: ["cartable", "sac a dos", "sac à dos", "sac scolaire", "bagage scolaire"] },
  { key: "trousses", label: "Trousses & accessoires", keywords: ["trousse", "taille-crayon", "taille crayon", "gomme", "regle", "règle", "compas", "equerre", "équerre", "rapporteur"] },
  { key: "calculatrices", label: "Calculatrices", keywords: ["calculatrice", "casio", "texas instruments", "texas-instruments"] },
  { key: "agendas", label: "Agendas & organisation", keywords: ["agenda", "calendrier scolaire", "planning", "organiseur", "planner"] },
  { key: "arts", label: "Dessin & loisirs créatifs", keywords: ["coloriage", "crayola", "posca", "canson", "peinture", "pastel", "aquarelle", "loisir creatif", "loisir créatif"] },
  { key: "livres", label: "Livres & révisions", keywords: ["livre scolaire", "cahier de vacances", "revision", "révision", "annales", "dictionnaire", "bescherelle", "parascolaire"] },
  { key: "informatique", label: "Informatique scolaire", keywords: ["ordinateur portable", "pc portable", "chromebook", "tablette tactile", "imprimante", "cle usb", "clé usb"] },
  { key: "etiquettes", label: "Étiquettes & protection", keywords: ["etiquette", "étiquette", "protege-cahier", "protège-cahier", "couvre-livre", "couvre livre", "ruban adhesif", "ruban adhésif", "scotch"] },
  { key: "repas", label: "Goûter & repas scolaire", keywords: ["gourde", "boite a gouter", "boîte à goûter", "lunch box", "lunchbox", "boite repas", "boîte repas"] },
];

/**
 * Catalogue commun utilisé par les pages transversales (« bons plans en cours »
 * et catégorie générale). Chaque univers garde sa liste spécialisée, mais une
 * marque ajoutée à l'un d'eux n'est plus oubliée dans le filtre global.
 */
const TRANSVERSAL_DEAL_BRANDS: BrandDef[] = [
  { key: "4711", label: "4711", keywords: ["4711", "4711 original"] },
  { key: "atida", label: "Atida", keywords: ["atida", "sante-discount"] },
  { key: "azzaro", label: "Azzaro", keywords: ["azzaro", "loris azzaro"] },
  { key: "cacharel", label: "Cacharel", keywords: ["cacharel"] },
  { key: "caroll", label: "Caroll", keywords: ["caroll"] },
  { key: "chloe", label: "Chloé", keywords: ["chloé", "chloe"] },
  { key: "creabul", label: "Créabul", keywords: ["creabul", "créabul"] },
  { key: "dolce-gusto", label: "Dolce Gusto", keywords: ["dolce gusto", "dolce-gusto"] },
  { key: "francoise-saget", label: "Françoise Saget", keywords: ["françoise saget", "francoise saget", "francoise-saget"] },
  { key: "gallia", label: "Gallia", keywords: ["gallia", "laboratoire gallia"] },
  { key: "gres", label: "Grès", keywords: ["grès", "parfums grès", "gres"] },
  { key: "issey-miyake", label: "Issey Miyake", keywords: ["issey miyake", "l'eau d'issey"] },
  { key: "la-belle-adresse", label: "La Belle Adresse", keywords: ["la belle adresse", "la-belle-adresse"] },
  { key: "la-boite-rose", label: "La Boîte Rose", keywords: ["la boîte rose", "la boite rose", "la-boite-rose"] },
  { key: "la-cuisine-doceane", label: "La Cuisine d’Océane", keywords: ["la cuisine d'oceane", "la cuisine d’océane"] },
  { key: "lolita-lempicka", label: "Lolita Lempicka", keywords: ["lolita lempicka"] },
  { key: "lollipops", label: "Lollipops", keywords: ["lollipops"] },
  { key: "montagne-noire", label: "Montagne Noire", keywords: ["montagne noire", "montagne-noire"] },
  { key: "parfums-moins-chers", label: "Parfums Moins Chers", keywords: ["parfums moins chers", "parfums-moins-chers"] },
  { key: "prozis", label: "Prozis", keywords: ["prozis"] },
  { key: "rabanne", label: "Rabanne", keywords: ["rabanne", "paco rabanne"] },
  { key: "ratte-mag", label: "Ratte Mag’", keywords: ["ratte mag", "ratte du touquet"] },
  { key: "seasonly", label: "Seasonly", keywords: ["seasonly"] },
];

export const ALL_DEAL_BRANDS: BrandDef[] = [
  ...TRANSVERSAL_DEAL_BRANDS,
  ...BON_PLAN_BRANDS,
  ...BEAUTE_BRANDS,
  ...BEBE_BRANDS,
  ...TECH_BRANDS,
  ...MAISON_BRANDS,
  ...JARDIN_BRANDS,
  ...JOUETS_BRANDS,
  ...MODE_BRANDS,
  ...BOX_BEAUTE_BRANDS,
  ...RENTREE_BRANDS,
];
