// Marques pour les pages /code-promo/[marque].
// La page agrège uniquement les articles MDX existants liés à la marque
// (filtre par matchTags). Aucun contenu inventé : tout vient de tes vrais articles.
//
// Liste triée alphabétiquement par nom.

export interface CodePromoBrand {
  slug: string;
  name: string;
  affiliateUrl: string;
  affiliateLabel: string;
  matchTags: string[]; // tags à matcher dans le frontmatter MDX
  color: string;
  currentOffer?: {
    code: string;
    discount: string;
    conditions: string;
    verifiedAt: string;
  };
}

export const CODE_PROMO_BRANDS: CodePromoBrand[] = [
  {
    slug: "bears-with-benefits",
    name: "Bears with Benefits",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=109774&awinaffid=990397&ued=https%3A%2F%2Fwww.bears-with-benefits.fr%2Fcollections%2Fbestseller",
    affiliateLabel: "Voir les offres Bears with Benefits",
    matchTags: ["bears with benefits", "bears-with-benefits", "gummies"],
    color: "#EAB8CA",
    currentOffer: {
      code: "BEARFECT",
      discount: "12 % supplémentaires",
      conditions: "BearsDay : jusqu'à 50 % de réduction et un tote bag offert dès 59 € d'achat. Vérifier le cumul et les exclusions au panier.",
      verifiedAt: "2026-08-25",
    },
  },
  {
    slug: "prescription-lab",
    name: "Prescription Lab",
    affiliateUrl: "https://www.prescriptionlab.com/landing/4pour14?ae=10&aev=https%3A%2F%2Fwww.prescriptionlab.com%2Flanding%2F5pour15%3Fml%3Dmail%26utm_source%3DMailing_pub%26utm_medium%3Dspeciale%26utm_campaign%3DM_allcampaigns",
    affiliateLabel: "Voir les offres Prescription Lab",
    matchTags: ["prescription-lab", "prescription lab"],
    color: "#A37C76",
  },
  {
    slug: "zigbuy",
    name: "Zigbuy",
    affiliateUrl: "https://ttanalytics.zigbuy.fr/c?c=40833&m=12&a=511692&r=&u=",
    affiliateLabel: "Voir les offres Zigbuy",
    matchTags: ["zigbuy", "zig-buy"],
    color: "#E85D04",
  },
  {
    slug: "belle-au-naturel",
    name: "Belle au Naturel",
    affiliateUrl: "https://wkl.belleaunaturel.fr/click-9693-2623?clickid=&subid=",
    affiliateLabel: "Voir les offres Belle au Naturel",
    matchTags: ["belle-au-naturel", "belle au naturel", "box-beaute-bio"],
    color: "#6B8E23",
  },
  {
    slug: "createurs-bio",
    name: "Les Créateurs Bio",
    affiliateUrl: "https://clk.tradedoubler.com/click?p=351766&a=3421259&url=https%3A%2F%2Fcreateursbio.fr%2F",
    affiliateLabel: "Voir les offres Les Créateurs Bio",
    matchTags: ["createurs-bio", "créateurs bio", "createurs bio", "cosmetiques-bio"],
    color: "#4F7942",
  },
  {
    slug: "a-demain",
    name: "A Demain",
    affiliateUrl: "https://a-demain.shop/?utm_medium=affiliation&utm_support=affilae&utm_source=blog&utm_campaign=bonsplansmania&ae=232",
    affiliateLabel: "Voir les offres A Demain",
    matchTags: ["a-demain", "a demain"],
    color: "#1F2937",
  },
  {
    slug: "adopt",
    name: "Adopt",
    affiliateUrl: "https://lb.affilae.com/r/?p=678fab80242409f9262715e4&af=65&lp=https%3A%2F%2Fwww.adopt.com%2Ffr%3Futm_source%3Daffilae%26utm_medium%3Dcodes-promos%26utm_campaign%3Dbonsplansmania",
    affiliateLabel: "Voir les offres Adopt",
    matchTags: ["adopt"],
    color: "#EC4899",
  },
  {
    slug: "activa-store",
    name: "Activa Store",
    affiliateUrl: "https://rel.fr.activastore.com/?P4B68D57CD2D1F1&redir=https%3A%2F%2Ffr.activastore.com%2F",
    affiliateLabel: "Voir les offres Activa Store",
    matchTags: ["activa-store", "activa store", "activastore", "complements-alimentaires"],
    color: "#6B8E23",
  },
  {
    slug: "aliexpress",
    name: "AliExpress",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=26009&awinaffid=990397&ued=https%3A%2F%2Ffr.aliexpress.com%2F%3Fwh_offline%3Dtrue%26gatewayAdapt%3Dglo2fra",
    affiliateLabel: "Voir les offres AliExpress",
    matchTags: ["aliexpress"],
    color: "#FF4500",
  },
  {
    slug: "atelier-du-sourcil",
    name: "L'Atelier du Sourcil",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=33057&awinaffid=990397&ued=https%3A%2F%2Fwww.atelierdusourcil.com%2F",
    affiliateLabel: "Voir les offres L'Atelier du Sourcil",
    matchTags: ["atelier-du-sourcil", "sourcils"],
    color: "#4A4A4A",
  },
  {
    slug: "atida",
    name: "Atida",
    affiliateUrl: "https://nwq.atida.fr/?P512F8957CD2D1F1&redir=https%3A%2F%2Fwww.atida.fr%2F",
    affiliateLabel: "Voir les promotions Atida",
    matchTags: ["atida", "sante-discount", "parapharmacie"],
    color: "#E85D75",
  },
  {
    slug: "afibel",
    name: "Afibel",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23267212&url=https%3A%2F%2Fwww.afibel.com",
    affiliateLabel: "Voir les offres Afibel",
    matchTags: ["afibel", "mode-femme", "grande-taille"],
    color: "#7A3152",
  },
  {
    slug: "beaba",
    name: "Béaba",
    affiliateUrl: "https://oam.beaba.com/?P5127CD57CD2D1D1&redir=https%3A%2F%2Fwww.beaba.com%2F",
    affiliateLabel: "Voir les offres Béaba",
    matchTags: ["beaba", "béaba"],
    color: "#4FC3F7",
  },
  {
    slug: "babybio",
    name: "Babybio",
    affiliateUrl: "https://awe.babybio.fr/?P5125FF57CD2D151&redir=https%3A%2F%2Fwww.babybio.fr%2Ffr%2F",
    affiliateLabel: "Voir les offres Babybio",
    matchTags: ["babybio", "alimentation bébé", "alimentation bio bébé"],
    color: "#76A942",
  },
  {
    slug: "beauty-success",
    name: "Beauty Success",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23247206&url=https%3A%2F%2Fwww.beautysuccess.fr%2F",
    affiliateLabel: "Voir les offres Beauty Success",
    matchTags: ["beauty-success", "beauty success"],
    color: "#FF1493",
  },
  {
    slug: "bayard-jeunesse",
    name: "Bayard Jeunesse",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P51323D57CD2D171&redir=https%3A%2F%2Fwww.bayard-jeunesse.com%2F",
    affiliateLabel: "Voir les offres Bayard Jeunesse",
    matchTags: ["bayard-jeunesse", "bayard jeunesse", "magazines enfants"],
    color: "#E53935",
  },
  {
    slug: "biogemm",
    name: "Biogemm",
    affiliateUrl: "https://c3po.link/QhtkyTp2kz",
    affiliateLabel: "Voir les offres Biogemm",
    matchTags: ["biogemm", "gemmotherapie"],
    color: "#558B2F",
  },
  {
    slug: "biotyfull-box",
    name: "Biotyfull Box",
    affiliateUrl: "https://xno.biotyfullbox.fr/?P51362157CD2D1D1&redir=https%3A%2F%2Fwww.biotyfullbox.fr%2F",
    affiliateLabel: "Voir les offres Biotyfull Box",
    matchTags: ["biotyfull", "biotyfull-box"],
    color: "#7FB069",
  },
  {
    slug: "blanche-porte",
    name: "Blancheporte",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23247216&url=https%3A%2F%2Fwww.blancheporte.fr%2F",
    affiliateLabel: "Activer le code Blancheporte",
    matchTags: ["blanche-porte", "blancheporte"],
    color: "#1E3A8A",
  },
  {
    slug: "blissim",
    name: "Blissim",
    affiliateUrl: "https://tidd.ly/3TxbBY7",
    affiliateLabel: "Voir les offres Blissim",
    matchTags: ["blissim"],
    color: "#FF6B9D",
  },
  {
    slug: "c-mon-etiquette",
    name: "C-MonEtiquette",
    affiliateUrl: "https://wgn.c-monetiquette.fr/?P510ED957CD2D151&redir=https%3A%2F%2Fwww.c-monetiquette.fr%2F",
    affiliateLabel: "Voir les offres C-MonEtiquette",
    matchTags: ["c-mon-etiquette", "etiquettes"],
    color: "#F59E0B",
  },
  {
    slug: "carte-noire",
    name: "Carte Noire",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=109112&awinaffid=990397&ued=https%3A%2F%2Fwww.cartenoire.fr%2Ffr%2Frentreeaubureau",
    affiliateLabel: "Voir les offres Carte Noire",
    matchTags: ["carte-noire", "carte noire"],
    color: "#1F2937",
  },
  {
    slug: "biolane",
    name: "Biolane",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=27764&awinaffid=990397&ued=https%3A%2F%2Fbiolane.fr%2F",
    affiliateLabel: "Voir les offres Biolane",
    matchTags: ["biolane", "soin bébé", "couches bébé"],
    color: "#65A6A2",
  },
  {
    slug: "caroll",
    name: "Caroll",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P512E6157CD2D1F1&redir=https%3A%2F%2Fwww.caroll.com%2Ffr_fr%2F",
    affiliateLabel: "Voir les offres Caroll",
    matchTags: ["caroll"],
    color: "#243746",
  },
  {
    slug: "carrefour",
    name: "Carrefour",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P51378757CD2D2131&redir=https%3A%2F%2Fwww.carrefour.fr%2F",
    affiliateLabel: "Voir les promotions Carrefour",
    matchTags: ["carrefour"],
    color: "#0050AA",
  },
  {
    slug: "cdiscount",
    name: "Cdiscount",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=6948&awinaffid=990397&ued=https%3A%2F%2Fwww.cdiscount.com%2F",
    affiliateLabel: "Voir les offres Cdiscount",
    matchTags: ["cdiscount"],
    color: "#0A4FA1",
  },
  {
    slug: "cdiscount-voyages",
    name: "Cdiscount Voyages",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=14021&awinaffid=990397&ued=https%3A%2F%2Fwww.cdiscount.com%2Fvoyages%2F",
    affiliateLabel: "Voir les offres Cdiscount Voyages",
    matchTags: ["cdiscount-voyages", "voyage-cdiscount"],
    color: "#0A4FA1",
  },
  {
    slug: "chaussea",
    name: "Chaussea",
    affiliateUrl: "https://jwv.chaussea.com/?P51387157CD2D1B1&redir=https%3A%2F%2Fwww.chaussea.com%2Ffr%2F",
    affiliateLabel: "Voir les offres Chaussea",
    matchTags: ["chaussea"],
    color: "#E53935",
  },
  {
    slug: "clarins",
    name: "Clarins",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23248736&url=https%3A%2F%2Fwww.clarins.fr",
    affiliateLabel: "Voir les offres Clarins",
    matchTags: ["clarins"],
    color: "#C9302C",
  },
  {
    slug: "cosmechic",
    name: "Cosmé'Chic",
    affiliateUrl: "https://cosmechic.fr/fr/?utm_source=bonsplansmania&utm_medium=affiliation&utm_campaign=comparatif_beaute_2026&utm_content=code-promo",
    affiliateLabel: "Voir les offres Cosmé'Chic",
    matchTags: ["cosmechic", "cosme-chic", "cosmé-chic"],
    color: "#E91E63",
  },
  {
    slug: "coupon-network",
    name: "Coupon Network",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23249363&url=https%3A%2F%2Fwww.couponnetwork.fr",
    affiliateLabel: "Voir les offres Coupon Network",
    matchTags: ["coupon-network", "coupon network", "bons-de-reduction", "remboursement"],
    color: "#E53935",
  },
  {
    slug: "covigneron",
    name: "Covigneron",
    affiliateUrl: "https://c3po.link/QVWRujassz",
    affiliateLabel: "Voir les offres Covigneron",
    matchTags: ["covigneron", "vin", "box-vin"],
    color: "#7C2D12",
  },
  {
    slug: "creabul",
    name: "Creabul",
    affiliateUrl: "https://www.creabul.fr/?ae=1036",
    affiliateLabel: "Voir les offres Creabul",
    matchTags: ["creabul"],
    color: "#9333EA",
  },
  {
    slug: "damart",
    name: "Damart",
    affiliateUrl: "https://tracking.publicidees.com/clic.php?promoid=97278&progid=3079&partid=61992",
    affiliateLabel: "Voir les offres Damart",
    matchTags: ["damart", "thermolactyl"],
    color: "#1E3A8A",
  },
  {
    slug: "darty",
    name: "Darty",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=7735&awinaffid=990397&ued=https%3A%2F%2Fwww.darty.com%2F",
    affiliateLabel: "Voir les offres Darty",
    matchTags: ["darty"],
    color: "#E60000",
  },
  {
    slug: "daxon",
    name: "Daxon",
    affiliateUrl: "https://fnty.co/c/r-nCqxZeUT",
    affiliateLabel: "Voir les offres Daxon",
    matchTags: ["daxon"],
    color: "#1E40AF",
  },
  {
    slug: "demain-beauty",
    name: "Demain Beauty",
    affiliateUrl: "https://demainbeauty.com/?ae=115",
    affiliateLabel: "Voir les offres Demain Beauty",
    matchTags: ["demain-beauty"],
    color: "#EC4899",
  },
  {
    slug: "bebeboutik",
    name: "Bebeboutik",
    affiliateUrl: "https://a.time1.me/r?promoid=193535&progid=2890&partid=61992",
    affiliateLabel: "Voir les ventes privées Bebeboutik",
    matchTags: ["bebeboutik", "bébéboutik", "ventes privées bébé", "puericulture"],
    color: "#E94E8B",
  },
  {
    slug: "degriffstock",
    name: "Dégriffstock",
    affiliateUrl: "https://auz.degriffstock.com/?P51257757CD2D1D1&redir=https%3A%2F%2Fwww.degriffstock.com%2F",
    affiliateLabel: "Voir les promotions Dégriffstock",
    matchTags: ["degriffstock", "dégriffstock", "mode dégriffée", "destockage"],
    color: "#D71920",
  },
  {
    slug: "dr-pierre-ricaud",
    name: "Dr Pierre Ricaud",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=6977&awinaffid=990397&ued=https%3A%2F%2Fwww.ricaud.com%2Ffr-fr",
    affiliateLabel: "Voir les offres Dr Pierre Ricaud",
    matchTags: ["dr-pierre-ricaud", "pierre ricaud", "pierre-ricaud", "dr pierre ricaud"],
    color: "#5D4D8C",
  },
  {
    slug: "e-leclerc",
    name: "E.Leclerc",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=15135&awinaffid=990397&ued=https%3A%2F%2Fwww.e.leclerc%2F",
    affiliateLabel: "Voir les offres E.Leclerc",
    matchTags: ["e-leclerc", "eleclerc", "leclerc"],
    color: "#0050A4",
  },
  {
    slug: "electro-depot",
    name: "Électro Dépôt",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23260341&url=https%3A%2F%2Fwww.electrodepot.fr",
    affiliateLabel: "Voir les offres Électro Dépôt",
    matchTags: ["electro-depot", "electro depot", "électro dépôt"],
    color: "#E30613",
  },
  {
    slug: "desigual", name: "Desigual",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P4EFAB57CD2D151&redir=https%3A%2F%2Fwww.desigual.com%2Ffr_FR%2F",
    affiliateLabel: "Voir les offres Desigual", matchTags: ["desigual", "mode femme", "mode colorée"], color: "#111111",
  },
  {
    slug: "famille-mary",
    name: "Famille Mary",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23249989&url=https%3A%2F%2Fwww.famillemary.fr",
    affiliateLabel: "Voir les offres Famille Mary",
    matchTags: ["famille-mary", "famille mary"],
    color: "#D97706",
  },
  {
    slug: "laboratoires-biarritz",
    name: "Laboratoires de Biarritz",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23249992&url=https%3A%2F%2Fwww.laboratoires-biarritz.com%2F",
    affiliateLabel: "Voir les offres Laboratoires de Biarritz",
    matchTags: ["laboratoires-biarritz", "laboratoires de biarritz", "alga-maris"],
    color: "#176B87",
  },
  {
    slug: "laboratoires-bimont",
    name: "Laboratoires Bimont",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23249322&url=https%3A%2F%2Fwww.laboratoiresbimont.com",
    affiliateLabel: "Voir les offres Laboratoires Bimont",
    matchTags: ["laboratoires-bimont", "laboratoires bimont", "bimont"],
    color: "#477A48",
  },
  {
    slug: "made-in-sport",
    name: "Made in Sport",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23254976&url=https%3A%2F%2Fwww.madeinsport.com",
    affiliateLabel: "Voir les offres Made in Sport",
    matchTags: ["made-in-sport", "made in sport", "maillots"],
    color: "#111827",
  },
  {
    slug: "my-beauty-factory",
    name: "My Beauty Factory",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23249991&url=https%3A%2F%2Fwww.mybeautyfactory.fr",
    affiliateLabel: "Voir les offres My Beauty Factory",
    matchTags: ["my-beauty-factory", "my beauty factory", "mybeautyfactory"],
    color: "#D66B8D",
  },
  {
    slug: "news-parfums",
    name: "News Parfums",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23249990&url=https%3A%2F%2Fwww.news-parfums.com",
    affiliateLabel: "Voir les offres News Parfums",
    matchTags: ["news-parfums", "news parfums", "parfum"],
    color: "#8B1E3F",
  },
  {
    slug: "francoise-saget",
    name: "Françoise Saget",
    affiliateUrl: "https://aye.francoisesaget.com/?P51279357CD2D191&redir=https%3A%2F%2Fwww.francoisesaget.com%2Ffr-fr%2F",
    affiliateLabel: "Voir les offres Françoise Saget",
    matchTags: ["francoise-saget", "francoise saget", "françoise saget"],
    color: "#1F3A8A",
  },
  {
    slug: "dplantes",
    name: "D.Plantes",
    affiliateUrl: "https://yzp.dplantes.com/?P510BA157CD2D2131&redir=https%3A%2F%2Fwww.dplantes.com%2Fnos-plantes",
    affiliateLabel: "Voir les offres D.Plantes",
    matchTags: ["dplantes", "d.plantes"],
    color: "#4F772D",
  },
  {
    slug: "glowria",
    name: "Glowria",
    affiliateUrl: "https://glowria.com/?ae=487",
    affiliateLabel: "Voir les offres Glowria",
    matchTags: ["glowria"],
    color: "#F97316",
  },
  {
    slug: "greenweez",
    name: "Greenweez",
    affiliateUrl: "https://www.greenweez.com/?utm_source=affilae&utm_medium=affiliation&utm_campaign=bonsplansmania&ae=344",
    affiliateLabel: "Voir les offres Greenweez",
    matchTags: ["greenweez"],
    color: "#4CAF50",
  },
  {
    slug: "gemo", name: "Gémo",
    affiliateUrl: "https://ava.gemo.fr/?P4894B57CD2D191&redir=https%3A%2F%2Fwww.gemo.fr%2F",
    affiliateLabel: "Voir les bons plans Gémo", matchTags: ["gemo", "gémo", "mode famille", "chaussures"], color: "#E30613",
  },
  {
    slug: "havas-voyages",
    name: "Havas Voyages",
    affiliateUrl: "https://kfx.havas-voyages.fr/?P511EA757CD2D151&redir=https%3A%2F%2Fwww.havas-voyages.fr%2F",
    affiliateLabel: "Voir les bons plans Havas Voyages",
    matchTags: ["havas-voyages", "havas voyages", "voyage"],
    color: "#E30613",
  },
  {
    slug: "hellofresh",
    name: "HelloFresh",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P51241357CD2D1B1&redir=https%3A%2F%2Fwww.hellofresh.fr%2F",
    affiliateLabel: "Profiter de l'offre HelloFresh",
    matchTags: ["hellofresh", "hello fresh", "box repas", "box à cuisiner"],
    color: "#91C11E",
  },
  {
    slug: "histoire-dor",
    name: "Histoire d'Or",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P51334157CD2D1D1&redir=https%3A%2F%2Fwww.histoiredor.com%2Ffr_FR",
    affiliateLabel: "Voir les offres Histoire d'Or",
    matchTags: ["histoire-dor", "histoire d'or", "histoire d’or"],
    color: "#B28A45",
  },
  {
    slug: "ioma",
    name: "IOMA Paris",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=26447&awinaffid=990397&ued=https%3A%2F%2Fioma-paris.com%2F",
    affiliateLabel: "Voir les offres IOMA Paris",
    matchTags: ["ioma", "ioma-paris", "soins-personnalises"],
    color: "#1F2937",
  },
  {
    slug: "isinwheel",
    name: "iSinwheel",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=59757&awinaffid=990397&ued=https%3A%2F%2Fwww.isinwheel.fr%2F",
    affiliateLabel: "Voir les offres iSinwheel",
    matchTags: ["isinwheel", "i-sinwheel", "trottinette-electrique", "velo-electrique"],
    color: "#111827",
  },
  {
    slug: "jho",
    name: "Jho",
    affiliateUrl: "https://lb.affilae.com/r/?p=5d91e79de9c24d727230b780&af=270&lp=https%3A%2F%2Fjho.fr%2F",
    affiliateLabel: "Voir les offres Jho",
    matchTags: ["jho", "protections-menstruelles"],
    color: "#2E7D32",
  },
  {
    slug: "lea-nature",
    name: "Léa Nature",
    affiliateUrl: "https://ryt.leanature.com/?P5127D757CD2D2131&redir=https%3A%2F%2Fwww.leanature.com%2F",
    affiliateLabel: "Voir les offres Léa Nature",
    matchTags: ["lea-nature", "léa nature", "lea nature"],
    color: "#558B2F",
  },
  {
    slug: "morgan",
    name: "Morgan",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P43B4357CD2D131&redir=https%3A%2F%2Fwww.morgandetoi.fr%2F",
    affiliateLabel: "Voir les offres Morgan",
    matchTags: ["morgan", "morgan de toi", "mode femme"],
    color: "#9E1B32",
  },
  {
    slug: "micromania",
    name: "Micromania",
    affiliateUrl: "https://xht.micromania.fr/?P3CB057CD2D161&redir=https%3A%2F%2Fwww.micromania.fr%2F",
    affiliateLabel: "Voir les offres Micromania",
    matchTags: ["micromania", "jeux vidéo", "gaming", "console"],
    color: "#F28C00",
  },
  {
    slug: "little-cigogne",
    name: "Little Cigogne",
    affiliateUrl: "https://c3po.link/QJFMmPDPY9",
    affiliateLabel: "Voir les offres Little Cigogne",
    matchTags: ["little-cigogne", "mode-enfant"],
    color: "#F472B6",
  },
  {
    slug: "lollipops",
    name: "Lollipops",
    affiliateUrl: "https://fou.lollipops.fr/?P51322957CD2D151&redir=https%3A%2F%2Flollipops.fr%2F",
    affiliateLabel: "Voir les offres Lollipops",
    matchTags: ["lollipops", "lollipops paris"],
    color: "#E91E63",
  },
  {
    slug: "la-boite-rose",
    name: "La Boîte Rose",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=26737&awinaffid=990397&ued=https%3A%2F%2Fwww.laboiterose.fr%2Ffr",
    affiliateLabel: "Découvrir La Boîte Rose",
    matchTags: ["la-boite-rose", "laboiterose", "la boîte rose", "grossesse", "bebe"],
    color: "#E83E8C",
  },
  {
    slug: "lookfantastic",
    name: "LOOKFANTASTIC",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=7496&awinaffid=990397&ued=https%3A%2F%2Fwww.lookfantastic.fr%2F",
    affiliateLabel: "Voir les offres LOOKFANTASTIC",
    matchTags: ["lookfantastic"],
    color: "#000000",
  },
  {
    slug: "le-rouge-francais",
    name: "Le Rouge Français",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=115665&awinaffid=990397&ued=https%3A%2F%2Flerougefrancais.com%2F",
    affiliateLabel: "Voir les offres Le Rouge Français",
    matchTags: ["le-rouge-francais", "rouge-francais", "maquillage-bio", "maquillage-vegan"],
    color: "#8D153A",
  },
  {
    slug: "loccitane",
    name: "L'Occitane",
    affiliateUrl: "https://fr.loccitane.com/?eaf-publisher=affilae&eaf-name=affilae-fil_rouge&eaf-creative=all&eaf-creativetype=all&utm_source=affilae&utm_medium=roiAffiliate&utm_campaign=affilae-fil_rouge&utm_term=bonsplansmania&eseg-name=bonsplansmania&eseg-item=474&ae=474",
    affiliateLabel: "Voir les offres L'Occitane",
    matchTags: ["loccitane", "l-occitane", "l'occitane"],
    color: "#1F4A3D",
  },
  {
    slug: "la-boite-du-fromager",
    name: "La Boîte du Fromager",
    affiliateUrl: "https://www.laboitedufromager.com/?ae=470",
    affiliateLabel: "Découvrir La Boîte du Fromager",
    matchTags: ["la-boite-du-fromager", "la boîte du fromager", "box fromage"],
    color: "#8B5E3C",
  },
  {
    slug: "la-box-fromage",
    name: "La Box Fromage",
    affiliateUrl: "https://laboxfromage.fr/?ae=991",
    affiliateLabel: "Découvrir La Box Fromage",
    matchTags: ["la-box-fromage", "la box fromage", "box fromage"],
    color: "#D19A45",
  },
  {
    slug: "la-gourmet-box",
    name: "La Gourmet Box",
    affiliateUrl: "https://www.lagourmetbox.com/fr/?ae=481",
    affiliateLabel: "Découvrir La Gourmet Box",
    matchTags: ["la-gourmet-box", "la gourmet box", "box gourmande"],
    color: "#7A2E2E",
  },
  {
    slug: "le-petit-ballon",
    name: "Le Petit Ballon",
    affiliateUrl: "https://lb.affilae.com/r/?p=534ea4a10f4c9a09348b4568&af=542&lp=https%3A%2F%2Fwww.lepetitballon.com%2F%3F_mkpid%3D2114%26_mkpd%3D%7BaffiliateId%7D%7C%7BClickID%7D%26utm_source%3Daffilae%26utm_medium%3Daffiliation%26_mkpc%3D542%26utm_campaign%3D542",
    affiliateLabel: "Voir les offres Le Petit Ballon",
    matchTags: ["le-petit-ballon", "le petit ballon", "box vin"],
    color: "#7F1D1D",
  },
  {
    slug: "mieux-que-des-fleurs",
    name: "Mieux Que Des Fleurs",
    affiliateUrl: "https://mieuxquedesfleurs.com/?ae=462",
    affiliateLabel: "Voir les idées cadeaux",
    matchTags: ["mieux-que-des-fleurs", "mieux que des fleurs", "cadeau"],
    color: "#E879A8",
  },
  {
    slug: "magnifaik",
    name: "Magnifaïk",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=112600&awinaffid=990397&ued=https%3A%2F%2Fwww.magnifaik.com%2F",
    affiliateLabel: "Voir les offres Magnifaïk",
    matchTags: ["magnifaik"],
    color: "#9333EA",
  },
  {
    slug: "lagrange-vacances",
    name: "Vacances Lagrange",
    affiliateUrl: "https://tracking.publicidees.com/clic.php?promoid=113863&progid=4201&partid=61992",
    affiliateLabel: "Voir les offres Vacances Lagrange",
    matchTags: ["lagrange-vacances", "vacances lagrange", "lagrange", "vacances"],
    color: "#0075A9",
  },
  {
    slug: "marionnaud",
    name: "Marionnaud",
    affiliateUrl: "https://www.marionnaud.fr/promotions",
    affiliateLabel: "Voir les offres Marionnaud",
    matchTags: ["marionnaud"],
    color: "#C9302C",
  },
  {
    slug: "manomano",
    name: "ManoMano",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=17547&awinaffid=990397&ued=https%3A%2F%2Fwww.manomano.fr%2F",
    affiliateLabel: "Voir les offres ManoMano",
    matchTags: ["manomano", "mano mano"],
    color: "#00B2A9",
  },
  {
    slug: "miin-cosmetics",
    name: "MiiN Cosmetics",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=29885&awinaffid=990397&campaign=&ued=https%3A%2F%2Fmiin-cosmetics.fr%2Fcontent%2F190-vuelta-a-la-rutina",
    affiliateLabel: "Voir les offres MiiN Cosmetics",
    matchTags: ["miin-cosmetics", "miin cosmetics", "miin", "k-beauty"],
    color: "#EC4899",
  },
  {
    slug: "milan-jeunesse",
    name: "Milan Jeunesse",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P51323F57CD2D171&redir=https%3A%2F%2Fmilan-jeunesse.com%2F",
    affiliateLabel: "Voir les offres Milan Jeunesse",
    matchTags: ["milan-jeunesse", "milan jeunesse", "magazines-enfants"],
    color: "#E53935",
  },
  {
    slug: "nocibe",
    name: "Nocibé",
    affiliateUrl: "https://www.nocibe.fr/",
    affiliateLabel: "Voir les offres Nocibé",
    matchTags: ["nocibe", "nocibé"],
    color: "#E91E63",
  },
  {
    slug: "one-watch-company",
    name: "One Watch Company",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P51379557CD2D1D1&redir=https%3A%2F%2Fonewatchcompany.com%2Ffr",
    affiliateLabel: "Voir les offres One Watch Company",
    matchTags: ["one-watch-company", "one-watch", "one watch company"],
    color: "#111827",
  },
  {
    slug: "mileade",
    name: "Miléade",
    affiliateUrl: "https://a.time1.me/r?promoid=105072&progid=3530&partid=61992",
    affiliateLabel: "Voir les bons plans Miléade",
    matchTags: ["mileade", "miléade", "village-club", "vacances"],
    color: "#006F8B",
  },
  {
    slug: "parfums-moins-chers",
    name: "Parfums Moins Chers",
    affiliateUrl: "https://zmk.parfumsmoinschers.com/?P4642357CD2D191&redir=https%3A%2F%2Fwww.parfumsmoinschers.com%2F",
    affiliateLabel: "Voir les parfums en promotion",
    matchTags: ["parfums-moins-chers", "parfums moins chers", "parfumsmoinschers", "parfum discount"],
    color: "#8B1E3F",
  },
  {
    slug: "pranarom",
    name: "Pranarom",
    affiliateUrl: "https://lb.affilae.com/r/?p=6814b22bc71e1ba3064b7ebb&af=978&lp=https%3A%2F%2Fpranarom.fr%2F",
    affiliateLabel: "Voir les offres Pranarom",
    matchTags: ["pranarom"],
    color: "#5A8A3A",
  },
  {
    slug: "monsieur-tshirt",
    name: "Monsieur TSHIRT",
    affiliateUrl: "https://monsieurtshirt.com/?ae=619",
    affiliateLabel: "Voir les cadeaux Monsieur TSHIRT",
    matchTags: ["monsieur-tshirt", "monsieur tshirt", "cadeau personnalisé"],
    color: "#111827",
  },
  {
    slug: "une-petite-mousse",
    name: "Une Petite Mousse",
    affiliateUrl: "https://unepetitemousse.fr/?ae=992",
    affiliateLabel: "Découvrir les box Une Petite Mousse",
    matchTags: ["une-petite-mousse", "une petite mousse", "box bière", "bière artisanale"],
    color: "#D97706",
  },
  {
    slug: "prozis",
    name: "Prozis",
    affiliateUrl: "https://prozis.com/1YlNV",
    affiliateLabel: "Profiter de l'offre Prozis jusqu'à -50 %",
    matchTags: ["prozis", "bonsmania", "imback"],
    color: "#AEEA00",
    currentOffer: {
      code: "IMBACK",
      discount: "Jusqu'à -50 %",
      conditions: "Jusqu'à 50 % de réduction sur une sélection de vêtements homme et femme et de produits alimentaires. Le niveau de remise varie selon les articles ; vérifier le prix final et l'éligibilité du code dans le panier.",
      verifiedAt: "2026-09-02",
    },
  },
  {
    slug: "rougier-ple",
    name: "Rougier & Plé",
    affiliateUrl: "https://afi.rougier-ple.fr/?P4826957CD2D1B1&redir=https%3A%2F%2Fwww.rougier-ple.fr%2F",
    affiliateLabel: "Voir les offres Rougier & Plé",
    matchTags: ["rougier-ple", "rougier & plé", "rougier et plé"],
    color: "#E30613",
  },
  {
    slug: "private-sport-shop",
    name: "Private Sport Shop",
    affiliateUrl: "https://tracking.publicidees.com/clic.php?promoid=60430&progid=2334&partid=61992",
    affiliateLabel: "Voir les ventes Private Sport Shop",
    matchTags: ["private-sport-shop", "private sport shop", "privatesportshop"],
    color: "#0F766E",
    currentOffer: {
      code: "BTS20",
      discount: "-20 %",
      conditions: "20 % supplémentaires dès 3 produits de la vente privée Back to Sport, jusqu’au 27 août 2026. Non cumulable avec un autre code.",
      verifiedAt: "2026-08-21",
    },
  },
  {
    slug: "rakuten",
    name: "Rakuten",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23252090&url=https%3A%2F%2Ffr.shopping.rakuten.com",
    affiliateLabel: "Voir les offres Rakuten",
    matchTags: ["rakuten"],
    color: "#BF0000",
  },
  {
    slug: "sarenza",
    name: "Sarenza",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P512D1157CD2D191&redir=https%3A%2F%2Fwww.sarenza.com%2Ffr%2Ffr",
    affiliateLabel: "Voir les offres Sarenza",
    matchTags: ["sarenza"],
    color: "#1976D2",
  },
  {
    slug: "sans-complexe",
    name: "Sans Complexe",
    affiliateUrl: "https://hca.sanscomplexe.com/?P4E63D57CD2D1D1&redir=https%3A%2F%2Fwww.sanscomplexe.com%2F",
    affiliateLabel: "Voir les offres Sans Complexe",
    matchTags: ["sans-complexe", "sans complexe", "sanscomplexe", "lingerie grande taille"],
    color: "#A85D6A",
  },
  {
    slug: "seasonly",
    name: "Seasonly",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=30403&awinaffid=990397&ued=https%3A%2F%2Fseasonly.fr%2F",
    affiliateLabel: "Voir les offres Seasonly",
    matchTags: ["seasonly"],
    color: "#F59E0B",
  },
  {
    slug: "sensilab",
    name: "Sensilab",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=24206&awinaffid=990397&ued=https%3A%2F%2Fwww.sensilab.fr%2F",
    affiliateLabel: "Voir les offres Sensilab",
    matchTags: ["sensilab"],
    color: "#059669",
  },
  {
    slug: "sephora",
    name: "Sephora",
    affiliateUrl: "https://www.sephora.fr/",
    affiliateLabel: "Voir les offres Sephora",
    matchTags: ["sephora", "sephora collection"],
    color: "#000000",
  },
  {
    slug: "showroomprive",
    name: "Showroomprivé",
    affiliateUrl: "https://lk.gt/aT3RF",
    affiliateLabel: "Voir les offres Showroomprivé",
    matchTags: ["showroomprive", "showroomprivé"],
    color: "#EC4899",
  },
  {
    slug: "somatoline-cosmetic",
    name: "Somatoline Cosmetic",
    affiliateUrl: "https://www.somatolinecosmetic.fr/",
    affiliateLabel: "Voir les offres Somatoline Cosmetic",
    matchTags: ["somatoline", "somatoline-cosmetic"],
    color: "#1E3A8A",
  },
  {
    slug: "shoes-fr",
    name: "Shoes.fr",
    affiliateUrl: "https://vkz.shoes.fr/?P51317957CD2D171&redir=https%3A%2F%2Fwww.shoes.fr%2F",
    affiliateLabel: "Voir les promotions Shoes.fr",
    matchTags: ["shoes.fr", "shoes-fr", "chaussures"],
    color: "#E30613",
  },
  {
    slug: "stylevana",
    name: "Stylevana",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=23223&awinaffid=990397&ued=https%3A%2F%2Fwww.stylevana.com%2Ffr",
    affiliateLabel: "Voir les offres Stylevana",
    matchTags: ["stylevana"],
    color: "#FF6B9D",
  },
  {
    slug: "zolux",
    name: "Zolux",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=7334&awinaffid=990397&ued=https%3A%2F%2Fwww.zolux.com%2F",
    affiliateLabel: "Voir les produits Zolux",
    matchTags: ["zolux", "animalerie", "animaux", "accessoires-animaux"],
    color: "#77B82A",
  },
  {
    slug: "spartoo",
    name: "Spartoo",
    affiliateUrl: "https://cgl.spartoo.com/?P510F5157CD2D1A1&redir=https%3A%2F%2Fwww.spartoo.com%2F",
    affiliateLabel: "Voir les bons plans Spartoo",
    matchTags: ["spartoo", "chaussures", "mode", "baskets"],
    color: "#E30613",
  },
  {
    slug: "thalgo",
    name: "Thalgo",
    affiliateUrl: "https://swc.thalgo.fr/?P4F50557CD2D1D1&redir=https%3A%2F%2Fwww.thalgo.fr%2F",
    affiliateLabel: "Voir les offres Thalgo",
    matchTags: ["thalgo", "soins-marins"],
    color: "#0EA5E9",
  },
  {
    slug: "pin-up-secret",
    name: "Pin Up Secret",
    affiliateUrl: "https://a.time1.me/r?promoid=243139&progid=8054&partid=61992",
    affiliateLabel: "Voir les offres Pin Up Secret",
    matchTags: ["pin-up-secret", "pin up secret"],
    color: "#D9467A",
  },
  {
    slug: "twenty-dc",
    name: "Twenty DC",
    affiliateUrl: "https://osu.twentydc.com/?P51399D57CD2D1F1&redir=https%3A%2F%2Ftwentydc.com%2F",
    affiliateLabel: "Voir les offres Twenty DC",
    matchTags: ["twenty-dc", "twentydc", "twenty dc", "collagene"],
    color: "#7C3AED",
  },
  {
    slug: "uriage",
    name: "Uriage",
    affiliateUrl: "https://ntk.uriage.fr/?P511FDB57CD2D131&redir=https%3A%2F%2Fwww.uriage.fr%2F",
    affiliateLabel: "Voir les offres Uriage",
    matchTags: ["uriage"],
    color: "#0EA5E9",
  },
  {
    slug: "vidaxl",
    name: "vidaXL",
    affiliateUrl: "https://a.time1.me/r?promoid=84560&progid=3149&partid=61992",
    affiliateLabel: "Voir les offres vidaXL",
    matchTags: ["vidaxl", "vida xl", "maison", "jardin"],
    color: "#F28C00",
  },
  {
    slug: "weleda",
    name: "Weleda",
    affiliateUrl: "https://zew.weleda.fr/?P511D9D57CD2D1D1&redir=https%3A%2F%2Fwww.weleda.fr%2F",
    affiliateLabel: "Voir les offres Weleda",
    matchTags: ["weleda"],
    color: "#B85B27",
  },
  {
    slug: "voyages-auchan",
    name: "Voyages Auchan",
    affiliateUrl: "https://vmx.voyages-auchan.com/?P51211D57CD2D1D1&redir=https%3A%2F%2Fwww.voyages-auchan.com%2F",
    affiliateLabel: "Voir les bons plans Voyages Auchan",
    matchTags: ["voyages-auchan", "voyages auchan", "auchan voyages", "voyage pas cher"],
    color: "#E30613",
  },
  {
    slug: "yesstyle",
    name: "YesStyle",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=15447&awinaffid=990397&ued=https%3A%2F%2Fwww.yesstyle.com%2Ffr%2Fhome.html",
    affiliateLabel: "Voir les offres YesStyle",
    matchTags: ["yesstyle"],
    color: "#FF6B9D",
  },
  {
    slug: "yves-rocher",
    name: "Yves Rocher",
    affiliateUrl: "https://www.yves-rocher.fr/",
    affiliateLabel: "Voir les offres Yves Rocher",
    matchTags: ["yves-rocher", "yves rocher"],
    color: "#4A7C59",
  },
  {
    slug: "zooplus",
    name: "Zooplus",
    affiliateUrl: "https://tidd.ly/4bvX2g9",
    affiliateLabel: "Voir les codes promo Zooplus",
    matchTags: ["zooplus", "animalerie"],
    color: "#FFA726",
  },
  {
    slug: "baija",
    name: "Baïja",
    affiliateUrl: "https://lk.gt/aSNSY",
    affiliateLabel: "Voir les offres Baïja",
    matchTags: ["baija", "baïja"],
    color: "#E8A87C",
  },
];

export function getBrandBySlug(slug: string): CodePromoBrand | undefined {
  return CODE_PROMO_BRANDS.find((b) => b.slug === slug);
}
