// Codes promo & offres valables toute l'année, affichés sur /codes-promo-permanents.
// Chaque entrée est un CodePromoOffer avec `permanent: true` → badge vert "Permanent"
// affiché à la place de la date d'expiration.
//
// Convention :
// - type "code"       : le clic déclenche la popup Dealabs (code copiable + CTA site)
// - type "newsletter" : le clic redirige direct vers la page inscription
// - type "cashback"   : services d'affiliation cashback
// - type "livraison"  : services permanents (livraison, retours, etc.)
// - type "offre"      : autres offres pérennes (soldes fixes, ventes privées, etc.)

import type { CodePromoOffer } from "./code-promo-offers";

export const CODES_PERMANENTS_OFFERS: CodePromoOffer[] = [
  {
    id: "perm-caroll-booster-10-deux-articles",
    brandSlug: "caroll",
    type: "offre",
    value: "-10 %",
    valueLabel: "DÈS 2 ARTICLES",
    title: "Caroll : -10 % dès 2 articles achetés",
    permanent: true,
    featured: true,
    conditions: "Remise accordée dès l'achat de 2 articles, selon les conditions de l'offre Booster affichées par Caroll. Vérifier son application dans le panier.",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P512E6157CD2D1F1&redir=https%3A%2F%2Fwww.caroll.com%2Ffr_fr%2Fjeux-et-offres-en-cours%23Booster",
  },
  {
    id: "perm-caroll-newsletter-15",
    brandSlug: "caroll",
    type: "newsletter",
    value: "-15 %",
    valueLabel: "NEWSLETTER",
    title: "Caroll : -15 % sur votre article préféré après inscription à la newsletter",
    permanent: true,
    featured: true,
    conditions: "Offre de bienvenue obtenue après inscription à la newsletter Caroll, selon les conditions communiquées par la marque.",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P512E6157CD2D1F1&redir=https%3A%2F%2Fwww.caroll.com%2Ffr_fr%2Fjeux-et-offres-en-cours%23Caroll15",
  },
  {
    id: "perm-a-demain",
    brandSlug: "a-demain",
    brandName: "A-demain",
    type: "code",
    value: "-10 %",
    title: "-10 % sur la 1ʳᵉ commande via inscription newsletter (mode éco-responsable)",
    permanent: true,
    conditions: "Inscription newsletter A-demain pour recevoir le code -10 %. Cumulable avec promos en cours.",
    affiliateUrl: "https://a-demain.shop/?utm_medium=affiliation&utm_support=affilae&utm_source=blog&utm_campaign=bonsplansmania&ae=232",
  },
  {
    id: "perm-adopt",
    brandSlug: "adopt",
    type: "newsletter",
    value: "-20 %",
    title: "-20 % sur la 1ʳᵉ commande Adopt' via newsletter",
    permanent: true,
    conditions: "Inscription newsletter Adopt' pour recevoir le code -20 %. Parfums français accessibles, soin, maquillage.",
    featured: true,
    affiliateUrl: "https://lb.affilae.com/r/?p=678fab80242409f9262715e4&af=65&lp=https%3A%2F%2Fwww.adopt.com%2Ffr%3Futm_source%3Daffilae%26utm_medium%3Dcodes-promos%26utm_campaign%3Dbonsplansmania",
  },
  {
    id: "perm-afibel",
    brandSlug: "afibel",
    brandName: "Afibel",
    type: "newsletter",
    value: "10 €",
    valueLabel: "OFFERTS",
    title: "10 € de réduction et livraison offerte dès 30 € avec la newsletter Afibel",
    permanent: true,
    conditions: "Réservé à la première inscription à la newsletter. Offre valable une seule fois sur Internet dès 30 € d'achat et non cumulable avec une autre promotion. Le code est envoyé par e-mail.",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23267212&url=https%3A%2F%2Fwww.afibel.com",
  },
  {
    id: "perm-amazon-prime",
    brandSlug: "amazon-prime",
    brandName: "Amazon Prime",
    type: "offre",
    value: "30 j",
    valueLabel: "ESSAI",
    title: "30 jours d'essai gratuit Amazon Prime (livraison rapide + Prime Video + Reading)",
    permanent: true,
    conditions: "Essai 30 jours, puis 6,99 €/mois ou 69,90 €/an. Annulable à tout moment.",
    affiliateUrl: "https://amzn.to/4dMkVTW",
  },
  {
    id: "perm-beauty-success",
    brandSlug: "beauty-success",
    type: "newsletter",
    value: "-20 %",
    title: "-20 % sur la 1ʳᵉ commande Beauty Success via newsletter",
    permanent: true,
    conditions: "Inscription newsletter Beauty Success pour recevoir le code -20 %. Parfums, soin, maquillage.",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23247206&url=https%3A%2F%2Fwww.beautysuccess.fr%2F",
  },
  {
    id: "perm-belle-au-naturel",
    brandSlug: "belle-au-naturel",
    brandName: "Belle au Naturel",
    type: "offre",
    value: "19,90 €",
    title: "1ʳᵉ box bio Belle au Naturel à 19,90 € avec SUMMER26",
    permanent: true,
    featured: true,
    conditions: "Code SUMMER26 à saisir lors de la commande, valable jusqu'au 31 août 2026. Puis 34,90 €/mois sans engagement. Livraison incluse.",
    affiliateUrl: "https://wkl.belleaunaturel.fr/click-9693-2623?clickid=&subid=code-permanent",
  },
  {
    id: "perm-bzb-bizzbee",
    brandSlug: "bzb-bizzbee",
    brandName: "BZB / Bizzbee",
    type: "offre",
    value: "-25 %",
    valueLabel: "ANNIV.",
    title: "Programme Pass fidélité gratuit BZB/Bizzbee : -25 % anniversaire + bons d'achat + loteries",
    permanent: true,
    conditions: "Inscription Pass gratuite en magasin ou en ligne. Cumul automatique des points sur chaque achat.",
    affiliateUrl: "https://www.b-z-b.com/programme-de-fidelite.html",
  },
  {
    id: "perm-cdiscount",
    brandSlug: "cdiscount",
    type: "code",
    value: "-10 €",
    title: "-10 € dès 50 € d'achat sur la 1ʳᵉ commande Cdiscount",
    code: "HELLO10",
    permanent: true,
    conditions: "Code HELLO10 valable pour les nouveaux clients (panier mini 50 €). Cumulable avec promos en cours. + livraison gratuite avec Cdiscount à Volonté.",
    affiliateUrl: "https://tidd.ly/4dJ6jB6",
  },
  {
    id: "perm-damart",
    brandSlug: "damart",
    type: "newsletter",
    value: "-20 €",
    title: "-20 € sur la 1ʳᵉ commande Damart via newsletter (mode femme/homme/enfant + linge maison)",
    permanent: true,
    conditions: "Inscription à la newsletter Damart pour recevoir l'offre de bienvenue. Des exclusions et conditions de non-cumul peuvent s'appliquer : vérifier le message reçu et le panier.",
    affiliateUrl: "https://tracking.publicidees.com/clic.php?promoid=97278&progid=3079&partid=61992",
  },
  {
    id: "perm-daxon",
    brandSlug: "daxon",
    type: "newsletter",
    value: "15 €",
    valueLabel: "OFFERTS",
    title: "15 € offerts sur la 1ʳᵉ commande Daxon via newsletter",
    permanent: true,
    conditions: "Inscription newsletter gratuite. 15 € utilisables dès la 1ʳᵉ commande.",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23260342&url=https%3A%2F%2Fwww.daxon.fr",
  },
  {
    id: "perm-demain-beauty",
    brandSlug: "demain-beauty",
    type: "newsletter",
    value: "-10 %",
    title: "-10 % sur la 1ʳᵉ commande Demain Beauty via newsletter",
    permanent: true,
    conditions: "Inscription newsletter Demain Beauty pour recevoir le code -10 %.",
    affiliateUrl: "https://demainbeauty.com/?ae=115",
  },
  {
    id: "perm-dr-pierre-ricaud",
    brandSlug: "dr-pierre-ricaud",
    type: "offre",
    value: "-50 %",
    valueLabel: "BIENVENUE",
    title: "-50 % sur la 1ʳᵉ commande Dr Pierre Ricaud + cadeau + livraison offerte dès 49 €",
    permanent: true,
    featured: true,
    conditions: "Offre nouvelle cliente. Cumulable avec promos en cours.",
    affiliateUrl: "https://tidd.ly/3UFSiN5",
  },
  {
    id: "perm-ebuyclub",
    brandSlug: "ebuyclub",
    brandName: "eBuyclub",
    type: "cashback",
    value: "3 €",
    valueLabel: "OFFERTS",
    title: "eBuyclub : 3 € offerts à l'inscription + cashback sur 2 500+ marchands",
    permanent: true,
    conditions: "Inscription gratuite. Bonus 3 € crédité après la 1ʳᵉ commande validée. Coupons remboursés jusqu'à 60 % sur les courses.",
    affiliateUrl: "https://www.ebuyclub.com/",
  },
  {
    id: "perm-greenweez",
    brandSlug: "greenweez",
    type: "code",
    value: "-10 %",
    title: "-10 % sur la 1ʳᵉ commande Greenweez + livraison offerte dès 39 €",
    code: "BIENVENUE2026",
    permanent: true,
    featured: true,
    conditions: "Offre affichée pour les nouveaux clients dès 39 € d'achats. Vérifier l'éligibilité, les exclusions et l'application du code dans le panier. Cumul non garanti.",
    affiliateUrl: "https://www.greenweez.com/?utm_source=affilae&utm_medium=affiliation&utm_campaign=bonsplansmania&ae=344",
  },
  {
    id: "perm-igraal",
    brandSlug: "igraal",
    brandName: "iGraal",
    type: "cashback",
    value: "3 €",
    valueLabel: "OFFERTS",
    title: "iGraal : 3 € de bonus à l'inscription + cashback 1 à 20 % sur 2 000+ boutiques",
    permanent: true,
    featured: true,
    conditions: "Inscription gratuite. Cumulable avec tous les codes promo des marques.",
    affiliateUrl: "https://www.igraal.com/?parrain_id=instantgagnantduweb",
  },
  {
    id: "perm-atelier-du-sourcil",
    brandSlug: "atelier-du-sourcil",
    type: "newsletter",
    value: "-10 %",
    title: "-10 % sur la 1ʳᵉ commande L'Atelier du Sourcil via newsletter + livraison dès 50 €",
    permanent: true,
    conditions: "Code reçu par e-mail après inscription. Cumulable avec promos en cours.",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=33057&awinaffid=990397&ued=https%3A%2F%2Fwww.atelierdusourcil.com%2F",
  },
  {
    id: "perm-le-rouge-francais",
    brandSlug: "le-rouge-francais",
    brandName: "Le Rouge Français",
    type: "newsletter",
    value: "-15 %",
    title: "-15 % sur la 1ʳᵉ commande Le Rouge Français (rouges à lèvres bio made in France)",
    permanent: true,
    conditions: "Inscription newsletter Le Rouge Français pour recevoir le code -15 %.",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=115665&awinaffid=990397&ued=https%3A%2F%2Flerougefrancais.com%2F",
  },
  {
    id: "perm-lea-nature",
    brandSlug: "lea-nature",
    type: "newsletter",
    value: "-10 %",
    title: "-10 % sur la 1ʳᵉ commande Léa Nature via newsletter (So'Bio Étic, Boho Green, Florame, Jonzac...)",
    permanent: true,
    conditions: "Inscription newsletter Léa Nature pour recevoir le code par e-mail.",
    affiliateUrl: "https://ryt.leanature.com/?P5127D757CD2D2131&redir=https%3A%2F%2Fwww.leanature.com%2F",
  },
  {
    id: "perm-createurs-bio",
    brandSlug: "createurs-bio",
    brandName: "Les Créateurs Bio",
    type: "offre",
    value: "-50 %",
    valueLabel: "ANTI-GASPI",
    title: "Les Créateurs Bio : jusqu'à -50 % permanent sur la section anti-gaspi + -5 % newsletter",
    permanent: true,
    conditions: "Section anti-gaspi accessible toute l'année sans code (produits DLC proche). Newsletter -5 % en plus.",
    affiliateUrl: "https://clk.tradedoubler.com/click?p=351766&a=3421259&url=https%3A%2F%2Fcreateursbio.fr%2F",
  },
  {
    id: "perm-magnifaik",
    brandSlug: "magnifaik",
    type: "newsletter",
    value: "-10 %",
    title: "-10 % sur la 1ʳᵉ commande Magnifaïk via newsletter",
    permanent: true,
    conditions: "Inscription newsletter Magnifaïk pour recevoir le code -10 %.",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=112600&awinaffid=990397&ued=https%3A%2F%2Fwww.magnifaik.com%2F",
  },
  {
    id: "perm-mieux-que-des-fleurs",
    brandSlug: "mieux-que-des-fleurs",
    brandName: "Mieux que des fleurs",
    type: "newsletter",
    value: "-10 %",
    title: "-10 % sur la 1ʳᵉ commande Mieux que des fleurs (boîtes cadeaux personnalisées)",
    permanent: true,
    conditions: "Inscription newsletter pour recevoir le code -10 %.",
    affiliateUrl: "https://mieuxquedesfleurs.com/?ae=462",
  },
  {
    id: "perm-miin",
    brandSlug: "miin-cosmetics",
    brandName: "MiiN Cosmetics",
    type: "newsletter",
    value: "10 €",
    valueLabel: "OFFERTS",
    title: "10 € offerts sur la 1ʳᵉ commande MiiN Cosmetics via newsletter (K-Beauty)",
    permanent: true,
    conditions: "Inscription newsletter MiiN gratuite. Cumulable avec promos en cours.",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=29885&awinaffid=990397&ued=https%3A%2F%2Fmiin-cosmetics.fr%2F",
  },
  {
    id: "perm-news-parfums",
    brandSlug: "news-parfums",
    brandName: "News Parfums",
    type: "offre",
    value: "-70 %",
    valueLabel: "PARFUMS",
    title: "News Parfums : parfums de marque jusqu'à -70 % toute l'année + livraison offerte dès 60 €",
    permanent: true,
    conditions: "Sélection rotative de 500+ parfums. Originaux et flacons éco (sans boîte).",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23249990&url=https%3A%2F%2Fwww.news-parfums.com",
  },
  {
    id: "perm-nubiance",
    brandSlug: "nubiance",
    brandName: "Nubiance",
    type: "offre",
    value: "FIDÉLITÉ",
    valueLabel: "+ PARRAINAGE",
    title: "Nubiance : programme fidélité + parrainage sur les soins peaux noires & métissées",
    permanent: true,
    conditions: "Inscription newsletter pour code de bienvenue. Points fidélité cumulés à chaque commande.",
    affiliateUrl: "https://nubiance.fr/pages/programme-de-fidelite-parrainage",
  },
  {
    id: "perm-poulpeo",
    brandSlug: "poulpeo",
    brandName: "Poulpeo",
    type: "cashback",
    value: "CASHBACK",
    valueLabel: "1 600+ SITES",
    title: "Poulpeo : cashback sur 1 600+ marchands + cashbacks boostés + extension Chrome auto",
    permanent: true,
    conditions: "Inscription gratuite. Cashback validé sous 2-3 mois. Cumulable avec codes promo.",
    affiliateUrl: "https://www.poulpeo.com/p/UaLtab",
  },
  {
    id: "perm-pranarom",
    brandSlug: "pranarom",
    type: "newsletter",
    value: "-10 %",
    title: "-10 % sur la 1ʳᵉ commande Pranarôm via newsletter (huiles essentielles, aromathérapie)",
    permanent: true,
    conditions: "Inscription newsletter Pranarôm pour recevoir le code -10 %.",
    affiliateUrl: "https://lb.affilae.com/r/?p=6814b22bc71e1ba3064b7ebb&af=978&lp=https%3A%2F%2Fpranarom.fr%2F",
  },
  {
    id: "perm-rakuten",
    brandSlug: "rakuten",
    type: "cashback",
    value: "CLUB R",
    valueLabel: "GRATUIT",
    title: "Rakuten Club R : cashback gratuit toute l'année + Rakuten Points convertibles",
    permanent: true,
    conditions: "Inscription gratuite au Club R. Cashback crédité après validation de la commande. Cumulable avec codes promo. Opérations boostées Mega Peak Days.",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23252090&url=https%3A%2F%2Ffr.shopping.rakuten.com",
  },
  {
    id: "perm-rougier-ple",
    brandSlug: "rougier-ple",
    brandName: "Rougier & Plé",
    type: "newsletter",
    value: "-10 %",
    title: "-10 % sur la 1ʳᵉ commande Rougier & Plé (matériel beaux-arts, loisirs créatifs, scrap)",
    permanent: true,
    conditions: "Inscription newsletter Rougier & Plé pour recevoir le code -10 %.",
    affiliateUrl: "https://afi.rougier-ple.fr/?P4826957CD2D1B1&redir=https%3A%2F%2Fwww.rougier-ple.fr%2F",
  },
  {
    id: "perm-sarenza",
    brandSlug: "sarenza",
    type: "newsletter",
    value: "20 €",
    valueLabel: "OFFERTS",
    title: "20 € offerts dès 100 € d'achat sur la 1ʳᵉ commande Sarenza + offres anniv (-40 %) et découverte (-30 %)",
    permanent: true,
    featured: true,
    conditions: "Inscription newsletter pour le code bienvenue. Articles expédiés par Sarenza uniquement.",
    affiliateUrl: "https://lk.gt/aXh1b",
  },
  {
    id: "perm-shoes-fr",
    brandSlug: "shoes-fr",
    brandName: "Shoes.fr",
    type: "newsletter",
    value: "5 €",
    valueLabel: "OFFERTS",
    title: "5 € offerts sur la 1ʳᵉ commande Shoes.fr via newsletter (chaussures homme/femme/enfant)",
    permanent: true,
    conditions: "Inscription newsletter Shoes.fr pour recevoir les 5 €.",
    affiliateUrl: "https://vkz.shoes.fr/?P51317957CD2D171&redir=https%3A%2F%2Fwww.shoes.fr%2F",
  },
  {
    id: "perm-showroomprive",
    brandSlug: "showroomprive",
    brandName: "Showroom Privé",
    type: "offre",
    value: "-70 %",
    valueLabel: "VENTES",
    title: "Showroom Privé : ventes privées quotidiennes -30 % à -70 % sur 200+ marques",
    permanent: true,
    conditions: "Inscription obligatoire (gratuite). Stocks limités, ventes 3 à 7 jours.",
    affiliateUrl: "https://lk.gt/aGiih",
  },
  {
    id: "perm-twenty-dc",
    brandSlug: "twenty-dc",
    type: "newsletter",
    value: "-10 %",
    title: "-10 % sur la 1ʳᵉ commande Twenty DC (collagène marin, Cosmetic Food)",
    permanent: true,
    conditions: "Inscription newsletter Twenty DC pour recevoir le code -10 %.",
    affiliateUrl: "https://osu.twentydc.com/?P51399D57CD2D1F1&redir=https%3A%2F%2Ftwentydc.com%2F",
  },
  {
    id: "perm-manomano",
    brandSlug: "manomano",
    type: "newsletter",
    value: "5 €",
    valueLabel: "DÈS 150 €",
    title: "5 € offerts dès 150 € après inscription à la newsletter ManoMano",
    permanent: true,
    conditions: "Code envoyé par e-mail, valable un mois à compter de sa réception pour une commande de 150 € minimum.",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=17547&awinaffid=990397&ued=https%3A%2F%2Fwww.manomano.fr%2F",
  },
  {
    id: "perm-zooplus",
    brandSlug: "zooplus",
    type: "newsletter",
    value: "-10 %",
    title: "-10 % sur la prochaine commande Zooplus après inscription newsletter",
    permanent: true,
    conditions: "Code envoyé par e-mail après inscription à la newsletter. Zooplus annonce également 333 zooPoints de bienvenue.",
    affiliateUrl: "https://tidd.ly/4bvX2g9",
  },
];
