// Marques pour les pages /code-promo/[marque].
// La page agrège uniquement les articles MDX existants liés à la marque
// (filtre par matchTags). Aucun contenu inventé : tout vient de tes vrais articles.
//
// Liste triée alphabétiquement par nom.

export interface CodePromoBrand {
  slug: string;
  name: string;
  affiliateUrl: string;
  affiliateLabel: string;
  matchTags: string[]; // tags à matcher dans le frontmatter MDX
  color: string;
  currentOffer?: {
    code: string;
    discount: string;
    conditions: string;
    verifiedAt: string;
  };
}

export const CODE_PROMO_BRANDS: CodePromoBrand[] = [
  {
    slug: "a-demain",
    name: "A Demain",
    affiliateUrl: "https://a-demain.shop/?utm_medium=affiliation&utm_support=affilae&utm_source=blog&utm_campaign=bonsplansmania&ae=232",
    affiliateLabel: "Voir les offres A Demain",
    matchTags: ["a-demain", "a demain"],
    color: "#1F2937",
  },
  {
    slug: "adopt",
    name: "Adopt",
    affiliateUrl: "https://www.adopt.com/fr?utm_source=affilae&utm_medium=codes-promos&utm_campaign=bonsplansmania&aecid=6a27ad4b4066ec6c4e0b481a",
    affiliateLabel: "Voir les offres Adopt",
    matchTags: ["adopt"],
    color: "#EC4899",
  },
  {
    slug: "activa-store",
    name: "Activa Store",
    affiliateUrl: "https://rel.fr.activastore.com/?P4B68D57CD2D1F1&redir=https%3A%2F%2Ffr.activastore.com%2F",
    affiliateLabel: "Voir les offres Activa Store",
    matchTags: ["activa-store", "activa store", "activastore", "complements-alimentaires"],
    color: "#6B8E23",
  },
  {
    slug: "aliexpress",
    name: "AliExpress",
    affiliateUrl: "https://tidd.ly/42BTllj",
    affiliateLabel: "Voir les offres AliExpress",
    matchTags: ["aliexpress"],
    color: "#FF4500",
  },
  {
    slug: "atelier-du-sourcil",
    name: "Atelier du Sourcil",
    affiliateUrl: "https://tidd.ly/43vh4Wd",
    affiliateLabel: "Voir les offres Atelier du Sourcil",
    matchTags: ["atelier-du-sourcil", "sourcils"],
    color: "#4A4A4A",
  },
  {
    slug: "atida",
    name: "Atida",
    affiliateUrl: "https://nwq.atida.fr/?P512F8957CD2D1F1&redir=https%3A%2F%2Fwww.atida.fr%2F",
    affiliateLabel: "Voir les promotions Atida",
    matchTags: ["atida", "sante-discount", "parapharmacie"],
    color: "#E85D75",
  },
  {
    slug: "beaba",
    name: "Béaba",
    affiliateUrl: "https://lk.gt/aYhaB",
    affiliateLabel: "Voir les offres Béaba",
    matchTags: ["beaba", "béaba"],
    color: "#4FC3F7",
  },
  {
    slug: "beauty-success",
    name: "Beauty Success",
    affiliateUrl: "https://fnty.co/c/r-ivVWRyPB",
    affiliateLabel: "Voir les offres Beauty Success",
    matchTags: ["beauty-success", "beauty success"],
    color: "#FF1493",
  },
  {
    slug: "bayard-jeunesse",
    name: "Bayard Jeunesse",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P51323D57CD2D171&redir=https%3A%2F%2Fwww.bayard-jeunesse.com%2F",
    affiliateLabel: "Voir les offres Bayard Jeunesse",
    matchTags: ["bayard-jeunesse", "bayard jeunesse", "magazines enfants"],
    color: "#E53935",
  },
  {
    slug: "biogemm",
    name: "Biogemm",
    affiliateUrl: "https://c3po.link/QhtkyTp2kz",
    affiliateLabel: "Voir les offres Biogemm",
    matchTags: ["biogemm", "gemmotherapie"],
    color: "#558B2F",
  },
  {
    slug: "biotyfull-box",
    name: "Biotyfull Box",
    affiliateUrl: "https://xno.biotyfullbox.fr/?P51362157CD2D1D1&redir=https%3A%2F%2Fwww.biotyfullbox.fr%2F",
    affiliateLabel: "Voir les offres Biotyfull Box",
    matchTags: ["biotyfull", "biotyfull-box"],
    color: "#7FB069",
  },
  {
    slug: "blanche-porte",
    name: "Blancheporte",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23247216&url=https%3A%2F%2Fwww.blancheporte.fr%2F",
    affiliateLabel: "Activer le code Blancheporte",
    matchTags: ["blanche-porte", "blancheporte"],
    color: "#1E3A8A",
  },
  {
    slug: "blissim",
    name: "Blissim",
    affiliateUrl: "https://tidd.ly/3TxbBY7",
    affiliateLabel: "Voir les offres Blissim",
    matchTags: ["blissim"],
    color: "#FF6B9D",
  },
  {
    slug: "c-mon-etiquette",
    name: "C-MonEtiquette",
    affiliateUrl: "https://lk.gt/aII2P",
    affiliateLabel: "Voir les offres C-MonEtiquette",
    matchTags: ["c-mon-etiquette", "etiquettes"],
    color: "#F59E0B",
  },
  {
    slug: "carte-noire",
    name: "Carte Noire",
    affiliateUrl: "https://tidd.ly/4l7Vmwj",
    affiliateLabel: "Voir les offres Carte Noire",
    matchTags: ["carte-noire", "carte noire"],
    color: "#1F2937",
  },
  {
    slug: "caroll",
    name: "Caroll",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P512E6157CD2D1F1&redir=https%3A%2F%2Fwww.caroll.com%2Ffr_fr%2F",
    affiliateLabel: "Voir les offres Caroll",
    matchTags: ["caroll"],
    color: "#243746",
  },
  {
    slug: "carrefour",
    name: "Carrefour",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P51378757CD2D2131&redir=https%3A%2F%2Fwww.carrefour.fr%2F",
    affiliateLabel: "Voir les promotions Carrefour",
    matchTags: ["carrefour"],
    color: "#0050AA",
  },
  {
    slug: "cdiscount",
    name: "Cdiscount",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=6948&awinaffid=990397&ued=https%3A%2F%2Fwww.cdiscount.com%2F",
    affiliateLabel: "Voir les offres Cdiscount",
    matchTags: ["cdiscount"],
    color: "#0A4FA1",
  },
  {
    slug: "chaussea",
    name: "Chaussea",
    affiliateUrl: "https://jwv.chaussea.com/?P51387157CD2D1B1&redir=https%3A%2F%2Fwww.chaussea.com%2Ffr%2F",
    affiliateLabel: "Voir les offres Chaussea",
    matchTags: ["chaussea"],
    color: "#E53935",
  },
  {
    slug: "clarins",
    name: "Clarins",
    affiliateUrl: "https://fnty.co/c/r-UPEIBQIo",
    affiliateLabel: "Voir les offres Clarins",
    matchTags: ["clarins"],
    color: "#C9302C",
  },
  {
    slug: "cosmechic",
    name: "Cosmé'Chic",
    affiliateUrl: "https://cosmechic.fr/fr/?utm_source=bonsplansmania&utm_medium=affiliation&utm_campaign=comparatif_beaute_2026&utm_content=code-promo",
    affiliateLabel: "Voir les offres Cosmé'Chic",
    matchTags: ["cosmechic", "cosme-chic", "cosmé-chic"],
    color: "#E91E63",
  },
  {
    slug: "covigneron",
    name: "Covigneron",
    affiliateUrl: "https://c3po.link/QVWRujassz",
    affiliateLabel: "Voir les offres Covigneron",
    matchTags: ["covigneron", "vin", "box-vin"],
    color: "#7C2D12",
  },
  {
    slug: "creabul",
    name: "Creabul",
    affiliateUrl: "https://c3po.link/QCPX7aCFg2",
    affiliateLabel: "Voir les offres Creabul",
    matchTags: ["creabul"],
    color: "#9333EA",
  },
  {
    slug: "damart",
    name: "Damart",
    affiliateUrl: "https://tracking.publicidees.com/clic.php?promoid=97278&progid=3079&partid=61992",
    affiliateLabel: "Voir les offres Damart",
    matchTags: ["damart", "thermolactyl"],
    color: "#1E3A8A",
  },
  {
    slug: "darty",
    name: "Darty",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=7735&awinaffid=990397&ued=https%3A%2F%2Fwww.darty.com%2F",
    affiliateLabel: "Voir les offres Darty",
    matchTags: ["darty"],
    color: "#E60000",
  },
  {
    slug: "daxon",
    name: "Daxon",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23260342&url=https%3A%2F%2Fwww.daxon.fr",
    affiliateLabel: "Voir les offres Daxon",
    matchTags: ["daxon"],
    color: "#1E40AF",
  },
  {
    slug: "demain-beauty",
    name: "Demain Beauty",
    affiliateUrl: "https://c3po.link/QCJ3HwVjuT",
    affiliateLabel: "Voir les offres Demain Beauty",
    matchTags: ["demain-beauty"],
    color: "#EC4899",
  },
  {
    slug: "dr-pierre-ricaud",
    name: "Dr Pierre Ricaud",
    affiliateUrl: "https://tidd.ly/3UFSiN5",
    affiliateLabel: "Voir les offres Dr Pierre Ricaud",
    matchTags: ["dr-pierre-ricaud", "pierre ricaud", "pierre-ricaud", "dr pierre ricaud"],
    color: "#5D4D8C",
  },
  {
    slug: "famille-mary",
    name: "Famille Mary",
    affiliateUrl: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23249989&url=https%3A%2F%2Fwww.famillemary.fr",
    affiliateLabel: "Voir les offres Famille Mary",
    matchTags: ["famille-mary", "famille mary"],
    color: "#D97706",
  },
  {
    slug: "francoise-saget",
    name: "Françoise Saget",
    affiliateUrl: "https://aye.francoisesaget.com/?P51279357CD2D191&redir=https%3A%2F%2Fwww.francoisesaget.com%2Ffr-fr%2F",
    affiliateLabel: "Voir les offres Françoise Saget",
    matchTags: ["francoise-saget", "francoise saget", "françoise saget"],
    color: "#1F3A8A",
  },
  {
    slug: "dplantes",
    name: "D.Plantes",
    affiliateUrl: "https://lk.gt/aEa78",
    affiliateLabel: "Voir les offres D.Plantes",
    matchTags: ["dplantes", "d.plantes"],
    color: "#4F772D",
  },
  {
    slug: "glowria",
    name: "Glowria",
    affiliateUrl: "https://glowria.com/?ae=487",
    affiliateLabel: "Voir les offres Glowria",
    matchTags: ["glowria"],
    color: "#F97316",
  },
  {
    slug: "greenweez",
    name: "Greenweez",
    affiliateUrl: "https://c3po.link/QJzHxSKDXz",
    affiliateLabel: "Voir les offres Greenweez",
    matchTags: ["greenweez"],
    color: "#4CAF50",
  },
  {
    slug: "havas-voyages",
    name: "Havas Voyages",
    affiliateUrl: "https://kfx.havas-voyages.fr/?P511EA757CD2D151&redir=https%3A%2F%2Fwww.havas-voyages.fr%2F",
    affiliateLabel: "Voir les bons plans Havas Voyages",
    matchTags: ["havas-voyages", "havas voyages", "voyage"],
    color: "#E30613",
  },
  {
    slug: "histoire-dor",
    name: "Histoire d'Or",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P51334157CD2D1D1&redir=https%3A%2F%2Fwww.histoiredor.com%2Ffr_FR",
    affiliateLabel: "Voir les offres Histoire d'Or",
    matchTags: ["histoire-dor", "histoire d'or", "histoire d’or"],
    color: "#B28A45",
  },
  {
    slug: "ioma",
    name: "Ioma",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=26447&awinaffid=990397&ued=https%3A%2F%2Fioma-paris.com%2F",
    affiliateLabel: "Voir les offres Ioma",
    matchTags: ["ioma", "soins-personnalises"],
    color: "#1F2937",
  },
  {
    slug: "jho",
    name: "Jho",
    affiliateUrl: "https://c3po.link/QCpqzeAkje",
    affiliateLabel: "Voir les offres Jho",
    matchTags: ["jho", "protections-menstruelles"],
    color: "#2E7D32",
  },
  {
    slug: "lea-nature",
    name: "Léa Nature",
    affiliateUrl: "https://lk.gt/azPuG",
    affiliateLabel: "Voir les offres Léa Nature",
    matchTags: ["lea-nature", "léa nature", "lea nature"],
    color: "#558B2F",
  },
  {
    slug: "little-cigogne",
    name: "Little Cigogne",
    affiliateUrl: "https://c3po.link/QJFMmPDPY9",
    affiliateLabel: "Voir les offres Little Cigogne",
    matchTags: ["little-cigogne", "mode-enfant"],
    color: "#F472B6",
  },
  {
    slug: "lollipops",
    name: "Lollipops",
    affiliateUrl: "https://fou.lollipops.fr/?P51322957CD2D151&redir=https%3A%2F%2Flollipops.fr%2F",
    affiliateLabel: "Voir les offres Lollipops",
    matchTags: ["lollipops", "lollipops paris"],
    color: "#E91E63",
  },
  {
    slug: "lookfantastic",
    name: "Lookfantastic",
    affiliateUrl: "https://tidd.ly/3AIsNEn",
    affiliateLabel: "Voir les offres Lookfantastic",
    matchTags: ["lookfantastic"],
    color: "#000000",
  },
  {
    slug: "loccitane",
    name: "L'Occitane",
    affiliateUrl: "https://fr.loccitane.com/?eaf-publisher=affilae&eaf-name=affilae-fil_rouge&eaf-creative=all&eaf-creativetype=all&utm_source=affilae&utm_medium=roiAffiliate&utm_campaign=affilae-fil_rouge&utm_term=bonsplansmania&eseg-name=bonsplansmania&eseg-item=474&ae=474",
    affiliateLabel: "Voir les offres L'Occitane",
    matchTags: ["loccitane", "l-occitane", "l'occitane"],
    color: "#1F4A3D",
  },
  {
    slug: "magnifaik",
    name: "Magnifaik",
    affiliateUrl: "https://tidd.ly/4uiyHDw",
    affiliateLabel: "Voir les offres Magnifaik",
    matchTags: ["magnifaik"],
    color: "#9333EA",
  },
  {
    slug: "marionnaud",
    name: "Marionnaud",
    affiliateUrl: "https://www.marionnaud.fr/promotions",
    affiliateLabel: "Voir les offres Marionnaud",
    matchTags: ["marionnaud"],
    color: "#C9302C",
  },
  {
    slug: "manomano",
    name: "ManoMano",
    affiliateUrl: "https://tidd.ly/4pF5waa",
    affiliateLabel: "Voir les offres ManoMano",
    matchTags: ["manomano", "mano mano"],
    color: "#00B2A9",
  },
  {
    slug: "miin-cosmetics",
    name: "Miin Cosmetics",
    affiliateUrl: "https://tidd.ly/4aTAR4S",
    affiliateLabel: "Voir les offres Miin Cosmetics",
    matchTags: ["miin-cosmetics", "miin cosmetics"],
    color: "#EC4899",
  },
  {
    slug: "milan-jeunesse",
    name: "Milan Jeunesse",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P51323F57CD2D171&redir=https%3A%2F%2Fmilan-jeunesse.com%2F",
    affiliateLabel: "Voir les offres Milan Jeunesse",
    matchTags: ["milan-jeunesse", "milan jeunesse", "magazines-enfants"],
    color: "#E53935",
  },
  {
    slug: "nocibe",
    name: "Nocibé",
    affiliateUrl: "https://www.nocibe.fr/",
    affiliateLabel: "Voir les offres Nocibé",
    matchTags: ["nocibe", "nocibé"],
    color: "#E91E63",
  },
  {
    slug: "one-watch-company",
    name: "One Watch Company",
    affiliateUrl: "https://action.metaffiliation.com/trk.php?mclic=P51379557CD2D1D1&redir=https%3A%2F%2Fonewatchcompany.com%2Ffr",
    affiliateLabel: "Voir les offres One Watch Company",
    matchTags: ["one-watch-company", "one-watch", "one watch company"],
    color: "#111827",
  },
  {
    slug: "pranarom",
    name: "Pranarom",
    affiliateUrl: "https://c3po.link/Qp5ydZeRVK",
    affiliateLabel: "Voir les offres Pranarom",
    matchTags: ["pranarom"],
    color: "#5A8A3A",
  },
  {
    slug: "prozis",
    name: "Prozis",
    affiliateUrl: "https://prozis.com/1YlNV",
    affiliateLabel: "Profiter du code BONSMANIA",
    matchTags: ["prozis", "bonsmania"],
    color: "#AEEA00",
    currentOffer: {
      code: "BONSMANIA",
      discount: "-10 %",
      conditions: "10 % de réduction sur le site Prozis. Vérifier l'application et les éventuelles règles de cumul dans le panier.",
      verifiedAt: "2026-08-11",
    },
  },
  {
    slug: "rougier-ple",
    name: "Rougier & Plé",
    affiliateUrl: "https://afi.rougier-ple.fr/?P4826957CD2D1B1&redir=https%3A%2F%2Fwww.rougier-ple.fr%2F",
    affiliateLabel: "Voir les offres Rougier & Plé",
    matchTags: ["rougier-ple", "rougier & plé", "rougier et plé"],
    color: "#E30613",
  },
  {
    slug: "private-sport-shop",
    name: "Private Sport Shop",
    affiliateUrl: "https://tracking.publicidees.com/clic.php?promoid=60430&progid=2334&partid=61992",
    affiliateLabel: "Voir les ventes Private Sport Shop",
    matchTags: ["private-sport-shop", "private sport shop", "privatesportshop"],
    color: "#0F766E",
  },
  {
    slug: "rakuten",
    name: "Rakuten",
    affiliateUrl: "https://fnty.co/c/r-GjssEgPP",
    affiliateLabel: "Voir les offres Rakuten",
    matchTags: ["rakuten"],
    color: "#BF0000",
  },
  {
    slug: "sarenza",
    name: "Sarenza",
    affiliateUrl: "https://lk.gt/aPzP3",
    affiliateLabel: "Voir les offres Sarenza",
    matchTags: ["sarenza"],
    color: "#1976D2",
  },
  {
    slug: "seasonly",
    name: "Seasonly",
    affiliateUrl: "https://tidd.ly/4iLlEEb",
    affiliateLabel: "Voir les offres Seasonly",
    matchTags: ["seasonly"],
    color: "#F59E0B",
  },
  {
    slug: "sensilab",
    name: "Sensilab",
    affiliateUrl: "https://www.awin1.com/cread.php?awinmid=24206&awinaffid=990397&ued=https%3A%2F%2Fwww.sensilab.fr%2F",
    affiliateLabel: "Voir les offres Sensilab",
    matchTags: ["sensilab"],
    color: "#059669",
  },
  {
    slug: "sephora",
    name: "Sephora",
    affiliateUrl: "https://www.sephora.fr/",
    affiliateLabel: "Voir les offres Sephora",
    matchTags: ["sephora", "sephora collection"],
    color: "#000000",
  },
  {
    slug: "showroomprive",
    name: "Showroomprivé",
    affiliateUrl: "https://lk.gt/aT3RF",
    affiliateLabel: "Voir les offres Showroomprivé",
    matchTags: ["showroomprive", "showroomprivé"],
    color: "#EC4899",
  },
  {
    slug: "somatoline-cosmetic",
    name: "Somatoline Cosmetic",
    affiliateUrl: "https://www.somatolinecosmetic.fr/",
    affiliateLabel: "Voir les offres Somatoline Cosmetic",
    matchTags: ["somatoline", "somatoline-cosmetic"],
    color: "#1E3A8A",
  },
  {
    slug: "stylevana",
    name: "Stylevana",
    affiliateUrl: "https://tidd.ly/4bqrGYB",
    affiliateLabel: "Voir les offres Stylevana",
    matchTags: ["stylevana"],
    color: "#FF6B9D",
  },
  {
    slug: "thalgo",
    name: "Thalgo",
    affiliateUrl: "https://lk.gt/aUfhw",
    affiliateLabel: "Voir les offres Thalgo",
    matchTags: ["thalgo", "soins-marins"],
    color: "#0EA5E9",
  },
  {
    slug: "pin-up-secret",
    name: "Pin Up Secret",
    affiliateUrl: "https://a.time1.me/r?promoid=243139&progid=8054&partid=61992",
    affiliateLabel: "Voir les offres Pin Up Secret",
    matchTags: ["pin-up-secret", "pin up secret"],
    color: "#D9467A",
  },
  {
    slug: "twenty-dc",
    name: "Twenty DC",
    affiliateUrl: "https://osu.twentydc.com/?P51399D57CD2D1F1&redir=https%3A%2F%2Ftwentydc.com%2F",
    affiliateLabel: "Voir les offres Twenty DC",
    matchTags: ["twenty-dc", "twentydc", "twenty dc", "collagene"],
    color: "#7C3AED",
  },
  {
    slug: "uriage",
    name: "Uriage",
    affiliateUrl: "https://lk.gt/aAAps",
    affiliateLabel: "Voir les offres Uriage",
    matchTags: ["uriage"],
    color: "#0EA5E9",
  },
  {
    slug: "weleda",
    name: "Weleda",
    affiliateUrl: "https://lk.gt/awIbg",
    affiliateLabel: "Voir les offres Weleda",
    matchTags: ["weleda"],
    color: "#B85B27",
  },
  {
    slug: "voyages-auchan",
    name: "Voyages Auchan",
    affiliateUrl: "https://vmx.voyages-auchan.com/?P51211D57CD2D1D1&redir=https%3A%2F%2Fwww.voyages-auchan.com%2F",
    affiliateLabel: "Voir les bons plans Voyages Auchan",
    matchTags: ["voyages-auchan", "voyages auchan", "auchan voyages", "voyage pas cher"],
    color: "#E30613",
  },
  {
    slug: "yesstyle",
    name: "YesStyle",
    affiliateUrl: "https://ystyle.co/kqCm2",
    affiliateLabel: "Voir les offres YesStyle",
    matchTags: ["yesstyle"],
    color: "#FF6B9D",
  },
  {
    slug: "yves-rocher",
    name: "Yves Rocher",
    affiliateUrl: "https://www.yves-rocher.fr/",
    affiliateLabel: "Voir les offres Yves Rocher",
    matchTags: ["yves-rocher", "yves rocher"],
    color: "#4A7C59",
  },
  {
    slug: "zooplus",
    name: "Zooplus",
    affiliateUrl: "https://tidd.ly/4bvX2g9",
    affiliateLabel: "Utiliser le code AFF-NEW10",
    matchTags: ["zooplus", "animalerie"],
    color: "#FFA726",
    currentOffer: {
      code: "AFF-NEW10",
      discount: "-10 % sur la première commande dès 59 €",
      conditions: "Offre réservée aux nouveaux clients.",
      verifiedAt: "7 août 2026",
    },
  },
  {
    slug: "baija",
    name: "Baïja",
    affiliateUrl: "https://lk.gt/aSNSY",
    affiliateLabel: "Voir les offres Baïja",
    matchTags: ["baija", "baïja"],
    color: "#E8A87C",
  },
];

export function getBrandBySlug(slug: string): CodePromoBrand | undefined {
  return CODE_PROMO_BRANDS.find((b) => b.slug === slug);
}
