/**
 * Registre des fiches produits communautaires (/produit/[slug]).
 *
 * Source de vérité unique : la page rubrique /avis-prix-beaute lit cette liste.
 * Les fiches elles-mêmes restent des pages dédiées sous src/app/produit/,
 * chacune portant ses propres offres marchands.
 *
 * Pour ajouter une fiche : créer la page sous src/app/produit/<slug>/ puis
 * ajouter l'entrée correspondante ici.
 */

export interface CommunityProduct {
  slug: string;
  brand: string;
  name: string;
  image: string;
  imageAlt: string;
  /** Rayon du parfum, sert au filtre femme / homme de /avis-prix-beaute */
  gender?: "femme" | "homme";
  category: "parfums" | "soins-visage" | "soins-corps" | "soins-cheveux" | "k-beauty" | "solaires" | "coffrets" | "box-beaute";
  /** Description courte affichée sur la page rubrique */
  teaser: string;
  lead?: string;
  idealFor?: string[];
  strengths?: string[];
  watchOut?: string[];
  editorialNote?: string;
  seoTitle?: string;
  seoDescription?: string;
  offers?: CommunityMerchantOffer[];
  /** Date d'ajout de la fiche au site (ISO), sert au tri récent / ancien */
  addedAt: string;
}

export interface CommunityMerchantOffer {
  merchant: string;
  note?: string;
  href: string;
  price?: string;
  checkedAt?: string;
  offer?: string;
  amazonAsin?: string;
}

export const COMMUNITY_PRODUCTS: CommunityProduct[] = [
  {
    slug: "acorelle-deodorant-roll-on-fraicheur-intense-bio",
    category: "soins-corps",
    addedAt: "2026-08-18T19:30:00",
    brand: "Acorelle",
    name: "Déodorant Roll-On Fraîcheur Intense Bio 50 ml",
    image: "/images/products/acorelle-deodorant-roll-on-fraicheur-intense.webp",
    imageAlt: "Acorelle déodorant roll-on Fraîcheur Intense bio 50 ml",
    teaser: "Un déodorant roll-on certifié bio, sans alcool, conçu pour limiter les odeurs tout en respectant les peaux sensibles.",
    lead: "Le Déodorant Roll-On Fraîcheur Intense Acorelle associe cristaux d’alun et ferments actifs dans une formule certifiée Cosmos Organic et fabriquée en France. La marque annonce une efficacité pendant 24 heures.",
    idealFor: ["Personnes recherchant un déodorant certifié bio", "Peaux sensibles à l’alcool", "Usage quotidien"],
    strengths: ["Sans alcool", "99 % d’ingrédients d’origine naturelle annoncés", "Format roll-on de 50 ml"],
    watchOut: ["L’efficacité d’un déodorant varie selon la transpiration", "Les cristaux d’alun ne conviennent pas à toutes les préférences"],
    editorialNote: "Notre analyse : une option simple pour celles et ceux qui privilégient une formule bio sans alcool. Il s’agit d’un déodorant, pas d’un anti-transpirant : il vise les odeurs sans bloquer la transpiration.",
    seoTitle: "Déodorant Acorelle Fraîcheur Intense bio : avis et prix",
    seoDescription: "Acorelle Déodorant Roll-On Fraîcheur Intense Bio 50 ml : analyse, points forts, limites et prix constaté chez Belle au Naturel.",
    offers: [{ merchant: "Belle au Naturel", note: "Déodorant Roll-On Fraîcheur Intense Bio 50 ml", price: "6,95 €", checkedAt: "2026-08-18", href: "https://wkl.belleaunaturel.fr/click-9693-2629?clickid=&subid=" }],
  },
  {
    slug: "coslys-shampooing-nourrissant-cameline-bio",
    category: "soins-cheveux",
    addedAt: "2026-08-18T19:29:00",
    brand: "Coslys",
    name: "Shampooing Nourrissant Cameline Bio 75 ml",
    image: "/images/products/coslys-shampooing-cameline-bio.webp",
    imageAlt: "Coslys shampooing nourrissant à la cameline bio 75 ml",
    teaser: "Un shampooing certifié bio sans silicone destiné aux cheveux secs, bouclés ou en manque de nutrition.",
    lead: "Le shampooing nourrissant Coslys mise sur la cameline bio pour nettoyer les cheveux secs et bouclés sans silicone. Son format de 75 ml convient aussi aux déplacements ou à un premier essai.",
    idealFor: ["Cheveux secs", "Cheveux bouclés", "Personnes recherchant un shampooing certifié bio"],
    strengths: ["98,8 % d’ingrédients d’origine naturelle annoncés", "Sans silicone", "Fabriqué en France selon la marque"],
    watchOut: ["Le format 75 ml est plus petit qu’un shampooing classique", "Les cheveux très secs peuvent nécessiter un soin complémentaire"],
    editorialNote: "Notre analyse : un petit format pertinent pour tester une routine capillaire bio ou partir en voyage. Pour les longueurs très sèches, un après-shampooing reste généralement utile.",
    seoTitle: "Shampooing Coslys Cameline Bio : avis et prix du 75 ml",
    seoDescription: "Coslys Shampooing Nourrissant Cameline Bio 75 ml : analyse, types de cheveux, points de vigilance et prix Belle au Naturel.",
    offers: [{ merchant: "Belle au Naturel", note: "Shampooing Nourrissant Cameline Bio 75 ml", price: "5,95 €", checkedAt: "2026-08-18", href: "https://wkl.belleaunaturel.fr/click-9693-2630?clickid=&subid=" }],
  },
  {
    slug: "cultiv-sublim-body-creme-corps-nourrissante-bio",
    category: "soins-corps",
    addedAt: "2026-08-18T19:28:00",
    brand: "Cultiv",
    name: "SUBLIM-BODY Crème Corps Nourrissante Bio 200 ml",
    image: "/images/products/cultiv-sublim-body-creme-corps.webp",
    imageAlt: "Cultiv SUBLIM-BODY crème corps nourrissante bio 200 ml",
    teaser: "Une crème corps bio à la texture onctueuse pour nourrir les peaux sèches et améliorer leur confort au quotidien.",
    lead: "SUBLIM-BODY de Cultiv est une crème nourrissante pour le corps en format 200 ml. Sa texture onctueuse cible les sensations de sécheresse et laisse la peau plus souple.",
    idealFor: ["Peaux sèches ou inconfortables", "Soin corps quotidien", "Personnes appréciant les textures riches"],
    strengths: ["Format 200 ml", "Texture nourrissante", "Certification bio annoncée"],
    watchOut: ["Une texture riche peut pénétrer moins vite", "Vérifier la composition en cas de sensibilité connue à un ingrédient"],
    editorialNote: "Notre analyse : un soin corps adapté aux personnes qui recherchent davantage de nutrition qu’avec un lait léger. À appliquer de préférence après la douche, sur peau encore légèrement humide.",
    seoTitle: "Cultiv SUBLIM-BODY crème corps bio : avis et prix",
    seoDescription: "Cultiv SUBLIM-BODY Crème Corps Nourrissante Bio 200 ml : analyse, types de peau et prix constaté chez Belle au Naturel.",
    offers: [{ merchant: "Belle au Naturel", note: "SUBLIM-BODY Crème Corps Nourrissante Bio 200 ml", price: "22 €", checkedAt: "2026-08-18", href: "https://wkl.belleaunaturel.fr/click-9693-2631?clickid=&subid=" }],
  },
  {
    slug: "bomoi-creme-solaire-bio-spf30-curcuma",
    category: "solaires",
    addedAt: "2026-08-18T19:27:00",
    brand: "Bomoï",
    name: "Crème Solaire Bio SPF30 au Curcuma 40 ml",
    image: "/images/products/bomoi-creme-solaire-bio-spf30.webp",
    imageAlt: "Bomoï crème solaire bio SPF30 au curcuma 40 ml",
    teaser: "Une crème solaire SPF30 certifiée bio, sans parfum et annoncée à 99 % d’origine naturelle.",
    lead: "La crème solaire Bomoï offre une protection SPF30 dans une formule au curcuma, sans parfum, certifiée Ecocert et fabriquée en France selon la marque. Son format de 40 ml est pensé pour le visage et les zones exposées.",
    idealFor: ["Personnes recherchant une protection SPF30 bio", "Peaux préférant les soins sans parfum", "Usage quotidien sur le visage"],
    strengths: ["SPF30", "Sans parfum", "99 % d’ingrédients d’origine naturelle annoncés"],
    watchOut: ["Renouveler fréquemment l’application, surtout après baignade ou transpiration", "Un SPF30 ne dispense pas des autres mesures de protection solaire"],
    editorialNote: "Notre analyse : une option intéressante pour un usage urbain ou une exposition modérée, à condition d’en appliquer une quantité suffisante. Pour une exposition intense, un SPF50 peut être préférable.",
    seoTitle: "Crème solaire Bomoï bio SPF30 : avis et prix",
    seoDescription: "Bomoï Crème Solaire Bio SPF30 au curcuma 40 ml : analyse, utilisation, précautions et prix Belle au Naturel.",
    offers: [{ merchant: "Belle au Naturel", note: "Crème Solaire Bio SPF30 au Curcuma 40 ml", price: "24 €", checkedAt: "2026-08-18", href: "https://wkl.belleaunaturel.fr/click-9693-2632?clickid=&subid=" }],
  },
  {
    slug: "royer-cosmetique-creme-visage-hydratante-matifiante-bio",
    category: "soins-visage",
    addedAt: "2026-08-18T19:26:00",
    brand: "Royer Cosmétique",
    name: "Crème Visage Hydratante Matifiante Bio 25 ml",
    image: "/images/products/royer-creme-visage-hydratante-matifiante.webp",
    imageAlt: "Royer Cosmétique crème visage hydratante matifiante bio 25 ml",
    teaser: "Une crème légère bio à la bave d’escargot destinée à hydrater les peaux mixtes tout en limitant les brillances.",
    lead: "La crème visage légère Royer Cosmétique associe hydratation et fini matifiant dans une formule bio à la bave d’escargot. Elle cible principalement les peaux mixtes sujettes aux brillances et aux imperfections.",
    idealFor: ["Peaux mixtes", "Zones sujettes aux brillances", "Personnes recherchant une crème légère"],
    strengths: ["Texture légère", "Action hydratante et matifiante annoncée", "Fabriquée en France selon la marque"],
    watchOut: ["La présence de bave d’escargot ne convient pas aux personnes recherchant un soin végan", "Le format 25 ml est plus petit que la plupart des crèmes visage"],
    editorialNote: "Notre analyse : une crème ciblée pour les peaux mixtes qui veulent hydrater sans fini trop riche. Les peaux sèches risquent de la trouver insuffisamment nourrissante.",
    seoTitle: "Crème matifiante Royer Cosmétique bio : avis et prix",
    seoDescription: "Royer Cosmétique Crème Visage Hydratante Matifiante Bio 25 ml : analyse, types de peau et prix Belle au Naturel.",
    offers: [{ merchant: "Belle au Naturel", note: "Crème Visage Hydratante Matifiante Bio 25 ml", price: "22,50 €", checkedAt: "2026-08-18", href: "https://wkl.belleaunaturel.fr/click-9693-2633?clickid=&subid=" }],
  },
  {
    slug: "energie-fruit-coco-curl-gelee-coiffante",
    category: "soins-cheveux",
    addedAt: "2026-08-18T18:30:00",
    brand: "Energie Fruit",
    name: "Coco Curl Gelée Coiffante 200 ml",
    image: "/images/products/energie-fruit-coco-curl-gelee.webp",
    imageAlt: "Energie Fruit Coco Curl gelée coiffante sans rinçage 200 ml",
    teaser: "Une gelée sans rinçage à l’huile de coco bio pour définir les cheveux ondulés, bouclés ou frisés sans effet carton.",
    lead: "La gelée Coco Curl Energie Fruit est un soin coiffant sans rinçage destiné aux cheveux ondulés, bouclés et frisés. Sa texture vise à définir les boucles et à limiter les frisottis sans figer les cheveux.",
    idealFor: ["Cheveux ondulés, bouclés ou frisés", "Définition sans effet carton", "Retouches sur cheveux secs ou humides"],
    strengths: ["98 % d’ingrédients d’origine naturelle annoncés", "Huile de coco bio et glycérine", "Sans silicone ni sulfate selon la marque"],
    watchOut: ["Le résultat dépend de la quantité appliquée et du type de boucle", "Une formule riche peut alourdir les cheveux très fins"],
    editorialNote: "Notre analyse : une option accessible pour structurer les boucles tout en conservant un toucher souple. Commencez avec une petite quantité, puis ajustez selon la densité et la porosité des cheveux.",
    seoTitle: "Energie Fruit Coco Curl : avis et prix de la gelée coiffante",
    seoDescription: "Energie Fruit Coco Curl 200 ml : analyse, types de cheveux, points forts, limites et prix Amazon actualisé automatiquement.",
    offers: [{
      merchant: "Amazon",
      note: "Prix et disponibilité actualisés par l’API officielle",
      href: "https://www.amazon.fr/ENERGIE-FRUIT-Coco-Curl-Anti-Frisottis/dp/B0BXSZ14TG?pf_rd_p=466283e4-cbd8-4390-b9ec-b587ab5cb8a7&pf_rd_r=TXYYA19FWK8XM3Y5B3JN&sr=1-5-29e27515-bb0a-4980-adc4-c3860763071e&th=1&linkCode=ll2&tag=lebrunnathali-21&linkId=e84670e1b0f8ad3d5ee5c413b5e7b2ea&ref_=as_li_ss_tl",
      amazonAsin: "B0BXSZ14TG",
    }],
  },
  {
    slug: "granions-serum-acide-hyaluronique-4-pourcent",
    category: "soins-visage",
    addedAt: "2026-08-18T18:29:00",
    brand: "Granions",
    name: "Sérum Acide Hyaluronique 4 % 30 ml",
    image: "/images/products/granions-serum-acide-hyaluronique-4.webp",
    imageAlt: "Granions sérum visage à l’acide hyaluronique 4 pour cent 30 ml",
    teaser: "Un sérum hydratant associant trois poids moléculaires d’acide hyaluronique dans une formule annoncée à 98 % d’origine naturelle.",
    lead: "Le sérum Granions associe trois formes d’acide hyaluronique dans une concentration totale annoncée de 4 %. Il s’utilise avant la crème pour renforcer l’hydratation et apporter un effet repulpant temporaire.",
    idealFor: ["Peaux déshydratées", "Ridules de déshydratation", "Sérum à appliquer avant la crème"],
    strengths: ["Trois poids moléculaires d’acide hyaluronique", "98 % d’ingrédients d’origine naturelle annoncés", "Fabrication française annoncée"],
    watchOut: ["Une concentration élevée n’est pas nécessairement mieux tolérée par toutes les peaux", "Appliquer ensuite une crème pour limiter l’évaporation de l’eau"],
    editorialNote: "Notre analyse : un sérum ciblé sur l’hydratation plutôt que sur un traitement anti-âge complet. Les peaux sensibles gagneront à l’introduire progressivement et à observer leur confort.",
    seoTitle: "Granions sérum acide hyaluronique 4 % : avis et prix",
    seoDescription: "Granions Sérum Acide Hyaluronique 4 % : analyse de la formule, types de peau, précautions et prix Amazon actualisé par API.",
    offers: [{
      merchant: "Amazon",
      note: "Prix et disponibilité actualisés par l’API officielle",
      href: "https://www.amazon.fr/GRANIONS-Serum-Acide-Hyaluronique-dermatologique/dp/B0GJFFPD22?pf_rd_p=466283e4-cbd8-4390-b9ec-b587ab5cb8a7&pf_rd_r=TXYYA19FWK8XM3Y5B3JN&sr=1-4-29e27515-bb0a-4980-adc4-c3860763071e&linkCode=ll2&tag=lebrunnathali-21&linkId=0939116dfa145a7e1b73ba44c7fbec46&ref_=as_li_ss_tl",
      amazonAsin: "B0GJFFPD22",
    }],
  },
  {
    slug: "dessange-nutri-extreme-richesse-soin-sans-rincage",
    category: "soins-cheveux",
    addedAt: "2026-08-18T18:28:00",
    brand: "Dessange",
    name: "Nutri-Extrême Richesse Soin Sans Rinçage 110 ml",
    image: "/images/products/dessange-nutri-extreme-richesse-soin.webp",
    imageAlt: "Dessange Nutri-Extrême Richesse soin sans rinçage cheveux très secs 110 ml",
    teaser: "Un soin sans rinçage aux peptides et à l’huile de lin conçu pour nourrir les longueurs et pointes très sèches.",
    lead: "Le soin Nutri-Extrême Richesse Dessange est destiné aux cheveux très secs. Il s’applique en petite quantité sur cheveux humides ou secs, principalement sur les longueurs et les pointes.",
    idealFor: ["Cheveux très secs", "Longueurs et pointes desséchées", "Soin quotidien sans rinçage"],
    strengths: ["Huile de lin", "Complexe de peptides annoncé", "Utilisation sur cheveux humides ou secs"],
    watchOut: ["Deux ou trois noisettes peuvent être excessives sur des cheveux fins", "Éviter les racines si elles regraissent facilement"],
    editorialNote: "Notre analyse : un soin pratique pour apporter du confort aux longueurs sèches entre deux shampooings. Le dosage compte beaucoup : une petite quantité suffit souvent sur les cheveux fins.",
    seoTitle: "Dessange Nutri-Extrême Richesse sans rinçage : avis et prix",
    seoDescription: "Dessange Nutri-Extrême Richesse 110 ml : analyse, types de cheveux, utilisation et prix Amazon actualisé automatiquement.",
    offers: [{
      merchant: "Amazon",
      note: "Prix et disponibilité actualisés par l’API officielle",
      href: "https://www.amazon.fr/DESSANGE-Nutrition-Nutri-Extr%C3%AAme-Richesse-Longueurs/dp/B0FJS9PQGH?pf_rd_p=466283e4-cbd8-4390-b9ec-b587ab5cb8a7&pf_rd_r=TXYYA19FWK8XM3Y5B3JN&sr=1-1-29e27515-bb0a-4980-adc4-c3860763071e&th=1&linkCode=ll2&tag=lebrunnathali-21&linkId=91dee32fb7719c156131a830fc0a545e&ref_=as_li_ss_tl",
      amazonAsin: "B0FJS9PQGH",
    }],
  },
  {
    slug: "cattier-masque-argile-rose-100ml",
    category: "soins-visage",
    addedAt: "2026-08-18T18:27:00",
    brand: "Cattier",
    name: "Masque Argile Rose 100 ml",
    image: "/images/products/cattier-masque-argile-rose.webp",
    imageAlt: "Cattier masque à l’argile rose bio 100 ml",
    teaser: "Un masque prêt à l’emploi à l’argile rose, destiné à adoucir et apaiser les peaux sensibles ou réactives.",
    lead: "Le masque Cattier à l’argile rose est une formule prête à l’emploi ciblant les peaux sensibles. Sa texture crémeuse évite d’avoir à mélanger soi-même une argile en poudre.",
    idealFor: ["Peaux sensibles ou réactives", "Soin visage ponctuel", "Personnes recherchant un masque prêt à l’emploi"],
    strengths: ["Argile rose", "Texture prête à l’emploi", "Positionnement bio de la gamme"],
    watchOut: ["Ne pas laisser l’argile sécher complètement sur la peau", "Espacer les utilisations si la peau tiraille"],
    editorialNote: "Notre analyse : une formule simple et accessible pour découvrir les masques à l’argile. Sur une peau sensible, mieux vaut appliquer une couche généreuse, maintenir le masque humide puis rincer sans attendre qu’il craquelle.",
    seoTitle: "Cattier masque argile rose : avis et prix du format 100 ml",
    seoDescription: "Masque à l’argile rose Cattier 100 ml : notre analyse, types de peau, conseils d’utilisation et prix Amazon via API.",
    offers: [{
      merchant: "Amazon",
      note: "Prix et disponibilité actualisés par l’API officielle",
      href: "https://www.amazon.fr/CATTIER-Masque-Argile-Rose-100ml/dp/B0941FGF9J?pf_rd_p=466283e4-cbd8-4390-b9ec-b587ab5cb8a7&pf_rd_r=TXYYA19FWK8XM3Y5B3JN&sr=1-19-29e27515-bb0a-4980-adc4-c3860763071e&th=1&linkCode=ll2&tag=lebrunnathali-21&linkId=517c8a53b35385df29a12c2029867d99&ref_=as_li_ss_tl",
      amazonAsin: "B0941FGF9J",
    }],
  },
  {
    slug: "medicube-collagen-jelly-cream-110ml",
    category: "k-beauty",
    addedAt: "2026-08-18T18:26:00",
    brand: "Medicube",
    name: "Collagen Jelly Cream 110 ml",
    image: "/images/products/medicube-collagen-jelly-cream.webp",
    imageAlt: "Medicube Collagen Jelly Cream crème gelée coréenne 110 ml",
    teaser: "Une crème gelée coréenne au collagène hydrolysé et à la niacinamide pour hydrater et apporter un fini lumineux.",
    lead: "La Collagen Jelly Cream Medicube est une crème gelée coréenne associant collagène hydrolysé et niacinamide. Elle vise surtout l’hydratation, le confort et l’éclat visuel de la peau.",
    idealFor: ["Peaux normales à sèches", "Teint terne ou déshydraté", "Routine K-Beauty hydratante"],
    strengths: ["Texture gelée", "Niacinamide", "Formule annoncée sans silicone ni colorant"],
    watchOut: ["Le collagène cosmétique agit principalement comme agent hydratant en surface", "Le fini lumineux peut ne pas convenir aux peaux recherchant un rendu mat"],
    editorialNote: "Notre analyse : une crème intéressante pour celles qui aiment les textures gelées et le fini glowy. Elle ne doit pas être présentée comme un substitut à un traitement dermatologique ni comme une solution capable de reconstruire le collagène cutané.",
    seoTitle: "Medicube Collagen Jelly Cream : avis et prix 110 ml",
    seoDescription: "Medicube Collagen Jelly Cream 110 ml : analyse, types de peau, niacinamide, limites et prix Amazon actualisé automatiquement.",
    offers: [{
      merchant: "Amazon",
      note: "Prix et disponibilité actualisés par l’API officielle",
      href: "https://www.amazon.fr/medicube-Repulpante-Niacinamide-Raffermissant-dhydratation/dp/B0CM2PPNMW?pf_rd_p=466283e4-cbd8-4390-b9ec-b587ab5cb8a7&pf_rd_r=TXYYA19FWK8XM3Y5B3JN&sr=1-17-29e27515-bb0a-4980-adc4-c3860763071e&th=1&linkCode=ll2&tag=lebrunnathali-21&linkId=8bf77695cb967711f29f0c3dddee7de1&ref_=as_li_ss_tl",
      amazonAsin: "B0CM2PPNMW",
    }],
  },
  {
    slug: "baija-creme-visage-myrtille-illuminatrice",
    category: "soins-visage",
    addedAt: "2026-08-14T13:10:00",
    brand: "Baïja",
    name: "Crème Visage Fouettée Myrtille",
    image: "/images/products/baija-creme-myrtille-visage.webp",
    imageAlt: "Crème Visage Fouettée Baïja à l’extrait de myrtille",
    teaser: "Une crème hydratante et illuminatrice à l’extrait de myrtille, pensée notamment pour les peaux ternes ou matures.",
    lead: "Cette crème fouettée Baïja associe extrait de myrtille, huiles de sésame et de tournesol dans une texture destinée à hydrater, adoucir et soutenir l’éclat de la peau.",
    idealFor: ["Peaux ternes ou matures", "Besoin d’hydratation et d’éclat", "Routine visage matin et soir"],
    strengths: ["Extrait de myrtille antioxydant", "Texture fouettée", "98 % d’ingrédients d’origine naturelle annoncés"],
    watchOut: ["La formule contient du parfum", "Un soin cosmétique ne remplace pas une protection solaire"],
    editorialNote: "Notre avis : une crème intéressante pour les peaux qui recherchent surtout confort et luminosité. Sa texture fouettée et ses huiles végétales conviendront davantage aux peaux normales à sèches qu’aux peaux très grasses.",
    offers: [{ merchant: "Baïja", note: "Crème Visage Fouettée Myrtille — boutique officielle", price: "29,90 €", checkedAt: "2026-08-14", href: "https://irb.baija.com/?P51318757CD2D1D1&redir=https%3A%2F%2Fbaija.com%2Fproducts%2Fcreme-fondante-visage-myrtille-illuminatrice" }],
  },
  {
    slug: "baija-creme-visage-ortie-anti-imperfections",
    category: "soins-visage",
    addedAt: "2026-08-14T13:05:00",
    brand: "Baïja",
    name: "Crème Visage Légère Ortie",
    image: "/images/products/baija-creme-ortie-visage.webp",
    imageAlt: "Crème Visage Légère Baïja à l’extrait d’ortie",
    teaser: "Une crème légère anti-imperfections à l’ortie et à l’amidon de riz pour les peaux mixtes à grasses.",
    lead: "La Crème Visage Légère à l’Ortie cible les brillances, les pores visibles et les imperfections avec une formule comprenant notamment de l’extrait d’ortie et de l’amidon de riz.",
    idealFor: ["Peaux mixtes à grasses", "Brillances et imperfections", "Texture légère au quotidien"],
    strengths: ["Extrait d’ortie", "Amidon de riz matifiant", "98 % d’ingrédients d’origine naturelle annoncés"],
    watchOut: ["La formule contient du parfum", "Les résultats sur les imperfections varient selon la peau"],
    editorialNote: "Notre avis : c’est la crème Baïja la plus cohérente pour une peau mixte ou grasse. L’amidon de riz vise un fini plus mat, mais les peaux sensibles au parfum devront rester prudentes.",
    offers: [{ merchant: "Baïja", note: "Crème Visage Légère Ortie 40 ml — boutique officielle", price: "30,90 €", checkedAt: "2026-08-14", href: "https://irb.baija.com/?P51318757CD2D1D1&redir=https%3A%2F%2Fbaija.com%2Fproducts%2Fcreme-legere-visage-ortie-40ml" }],
  },
  {
    slug: "baija-fluide-concentre-menthe-poivree",
    category: "soins-visage",
    addedAt: "2026-08-14T13:00:00",
    brand: "Baïja",
    name: "Fluide Concentré Menthe Poivrée 30 ml",
    image: "/images/products/baija-fluide-menthe-visage.webp",
    imageAlt: "Fluide Concentré Visage Baïja à la menthe poivrée",
    teaser: "Un fluide purifiant à la menthe poivrée et à la niacinamide pour les peaux mixtes à grasses.",
    lead: "Ce fluide concentré Baïja associe huile essentielle et hydrolat de menthe poivrée à la niacinamide dans une formule destinée à apaiser, purifier et aider à uniformiser le teint.",
    idealFor: ["Peaux mixtes à grasses", "Teint irrégulier et pores visibles", "Texture fluide sous une crème"],
    strengths: ["Menthe poivrée", "Niacinamide", "99 % d’ingrédients d’origine naturelle annoncés"],
    watchOut: ["La menthe poivrée peut ne pas convenir aux peaux très réactives", "Tester progressivement en cas de sensibilité"],
    editorialNote: "Notre avis : un fluide ciblé pour celles qui recherchent fraîcheur et action purifiante. La présence de niacinamide est intéressante, mais la menthe poivrée invite à la prudence sur une peau très sensible.",
    offers: [{ merchant: "Baïja", note: "Fluide Concentré Menthe Poivrée 30 ml — boutique officielle", price: "30,90 €", checkedAt: "2026-08-14", href: "https://irb.baija.com/?P51318757CD2D1D1&redir=https%3A%2F%2Fbaija.com%2Fproducts%2Ffluide-concentre-visage-menthe-30ml" }],
  },
  {
    slug: "baija-soin-precieux-melisse-mauve-des-bois",
    category: "soins-visage",
    addedAt: "2026-08-14T12:55:00",
    brand: "Baïja",
    name: "Soin Précieux Mélisse & Mauve des Bois 30 ml",
    image: "/images/products/baija-soin-melisse-mauve-visage.webp",
    imageAlt: "Soin Précieux Visage Baïja Mélisse et Mauve des Bois",
    teaser: "Un soin éclat pour les peaux ternes ou matures, avec mélisse, mauve des bois et acide hyaluronique.",
    lead: "Le Soin Précieux Baïja est un fluide destiné aux peaux en manque de tonus. Sa formule associe extraits de mélisse et de mauve des bois, acide hyaluronique et vitamine C.",
    idealFor: ["Peaux ternes ou matures", "Manque de tonus et d’éclat", "Soin à appliquer avant la crème"],
    strengths: ["Mélisse et mauve des bois", "Acide hyaluronique", "99 % d’ingrédients d’origine naturelle annoncés"],
    watchOut: ["La formule contient du parfum", "Les effets anti-âge restent progressifs et variables"],
    editorialNote: "Notre avis : ce soin vise surtout l’éclat, le confort et l’hydratation des peaux ternes ou matures. Il s’utilise davantage comme un sérum avant la crème que comme un hydratant unique.",
    offers: [{ merchant: "Baïja", note: "Soin Précieux Mélisse & Mauve des Bois 30 ml — boutique officielle", price: "29,90 €", checkedAt: "2026-08-14", href: "https://irb.baija.com/?P51318757CD2D1D1&redir=https%3A%2F%2Fbaija.com%2Fproducts%2Fsoin-precieux-visage-melisse-mauve-des-bois-30ml" }],
  },
  {
    slug: "baija-gipsy-bloom-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-14T12:30:00",
    brand: "Baïja",
    name: "Gipsy Bloom Eau de Parfum 15 ml",
    image: "/images/products/baija-gipsy-bloom-eau-de-parfum-15ml.webp",
    imageAlt: "Flacon Baïja Gipsy Bloom Eau de Parfum 15 ml",
    teaser: "Un parfum floral et poudré qui associe la rose, le benjoin et le santal dans un petit format nomade.",
    lead: "Gipsy Bloom est une eau de parfum Baïja florale et poudrée. La rose ouvre la composition, le benjoin apporte une facette douce et le santal installe un fond plus chaud.",
    idealFor: ["Les personnes qui aiment les parfums floraux poudrés", "Une fragrance douce au quotidien", "Un petit format facile à emporter"],
    strengths: ["Accord rose, benjoin et santal", "Format nomade de 15 ml", "Profil floral facile à identifier"],
    watchOut: ["Le format 15 ml est plus petit qu’un flacon classique", "Le rendu et la tenue varient selon la peau"],
    editorialNote: "Notre avis : Gipsy Bloom convient surtout aux amatrices de floraux doux et poudrés. La rose reste lumineuse, tandis que le benjoin et le santal apportent un fond plus enveloppant sans transformer la fragrance en parfum très gourmand.",
    seoTitle: "Baïja Gipsy Bloom : avis et prix du parfum",
    seoDescription: "Baïja Gipsy Bloom Eau de Parfum 15 ml : notre avis, notes de rose, benjoin et santal, prix vérifié et lien affilié Baïja.",
    offers: [{ merchant: "Baïja", note: "Eau de Parfum Gipsy Bloom 15 ml — boutique officielle", price: "19,90 €", checkedAt: "2026-08-14", href: "https://irb.baija.com/?P51318757CD2D1D1&redir=https%3A%2F%2Fbaija.com%2Fproducts%2Fparfum-corps-gipsy-bloom-15ml" }],
  },
  {
    slug: "baija-lost-paradise-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-14T12:25:00",
    brand: "Baïja",
    name: "Lost Paradise Eau de Parfum 15 ml",
    image: "/images/products/baija-lost-paradise-eau-de-parfum-15ml.webp",
    imageAlt: "Flacon Baïja Lost Paradise Eau de Parfum 15 ml",
    teaser: "Une fragrance fruitée et solaire à l’ananas, aux fleurs blanches et à la fève tonka.",
    lead: "Lost Paradise est une eau de parfum Baïja fruitée, pétillante et solaire. L’ananas domine le départ, les fleurs blanches structurent le cœur et la fève tonka réchauffe le fond.",
    idealFor: ["Les personnes qui aiment les parfums fruités solaires", "Une senteur estivale et dépaysante", "Un petit format facile à emporter"],
    strengths: ["Départ lumineux à l’ananas", "Fond doux à la fève tonka", "Format nomade de 15 ml"],
    watchOut: ["Le profil fruité et solaire peut sembler très estival", "La tenue varie selon la peau"],
    editorialNote: "Notre avis : Lost Paradise est le plus exotique de cette sélection Baïja. Il convient aux personnes qui aiment l’ananas frais, les fleurs blanches et les fonds doux légèrement vanillés, avec une ambiance clairement solaire.",
    seoTitle: "Baïja Lost Paradise : avis et prix du parfum",
    seoDescription: "Baïja Lost Paradise Eau de Parfum 15 ml : notre avis, notes d’ananas, fleurs blanches et fève tonka, prix et lien affilié.",
    offers: [{ merchant: "Baïja", note: "Eau de Parfum Lost Paradise 15 ml — boutique officielle", price: "19,90 €", checkedAt: "2026-08-14", href: "https://irb.baija.com/?P51318757CD2D1D1&redir=https%3A%2F%2Fbaija.com%2Fproducts%2Fparfum-corps-lost-paradise-15ml" }],
  },
  {
    slug: "baija-ile-dazur-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-14T12:20:00",
    brand: "Baïja",
    name: "Île d’Azur Eau de Parfum 15 ml",
    image: "/images/products/baija-ile-dazur-eau-de-parfum-15ml.webp",
    imageAlt: "Flacon Baïja Île d’Azur Eau de Parfum 15 ml",
    teaser: "Un floral solaire où le frangipanier et la fleur d’oranger reposent sur un fond vanillé.",
    lead: "Île d’Azur est une eau de parfum Baïja florale et solaire. La fleur de frangipanier ouvre la composition, la fleur d’oranger forme le cœur et la vanille adoucit le fond.",
    idealFor: ["Les personnes qui aiment les floraux solaires", "Les amatrices de fleur d’oranger et de vanille", "Un petit format facile à emporter"],
    strengths: ["Accord frangipanier, fleur d’oranger et vanille", "Profil floral chaleureux", "Format nomade de 15 ml"],
    watchOut: ["La vanille peut paraître douce aux personnes préférant les parfums très frais", "La tenue varie selon la peau"],
    editorialNote: "Notre avis : Île d’Azur convient aux amatrices de fleurs blanches solaires. Le frangipanier lui donne une tonalité exotique, la fleur d’oranger apporte de la lumière et la vanille arrondit l’ensemble sans en faire un parfum entièrement gourmand.",
    seoTitle: "Baïja Île d’Azur : avis et prix du parfum",
    seoDescription: "Baïja Île d’Azur Eau de Parfum 15 ml : notre avis, notes de frangipanier, fleur d’oranger et vanille, prix et lien affilié.",
    offers: [{ merchant: "Baïja", note: "Eau de Parfum Île d’Azur 15 ml — boutique officielle", price: "19,90 €", checkedAt: "2026-08-14", href: "https://irb.baija.com/?P51318757CD2D1D1&redir=https%3A%2F%2Fbaija.com%2Fproducts%2Fparfum-corps-ile-dazur-15ml" }],
  },
  {
    slug: "baija-jardin-pallanca-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-14T12:00:00",
    brand: "Baïja",
    name: "Jardin Pallanca Eau de Parfum 15 ml",
    image: "/images/products/baija-jardin-pallanca-eau-de-parfum-15ml.webp",
    imageAlt: "Flacon Baïja Jardin Pallanca Eau de Parfum 15 ml",
    teaser: "Un petit parfum frais et fruité où le cassis rencontre le jasmin et les muscs blancs, dans un format facile à emporter.",
    lead: "Jardin Pallanca est une eau de parfum Baïja au profil pétillant, frais et fruité. Son format 15 ml vise surtout les personnes qui souhaitent un parfum nomade à glisser facilement dans un sac.",
    idealFor: ["Les personnes qui aiment les parfums fruités et frais", "Un parfum léger à porter au quotidien", "Un petit format facile à emporter"],
    strengths: ["Accord cassis, jasmin et muscs blancs", "Format nomade de 15 ml", "Fabrication française annoncée par Baïja"],
    watchOut: ["Le format 15 ml est plus petit qu’un flacon classique", "La tenue et le rendu d’un parfum varient selon la peau"],
    editorialNote: "Notre avis : Jardin Pallanca convient surtout à celles qui recherchent une fragrance fraîche, fruitée et facile à porter. Le cassis apporte un départ pétillant, le jasmin adoucit le cœur et les muscs blancs donnent un fond propre et discret.",
    seoTitle: "Baïja Jardin Pallanca : avis et prix du parfum",
    seoDescription: "Baïja Jardin Pallanca Eau de Parfum 15 ml : notre avis, notes de cassis, jasmin et muscs blancs, prix vérifié et lien affilié Baïja.",
    offers: [{
      merchant: "Baïja",
      note: "Eau de Parfum Jardin Pallanca 15 ml — boutique officielle",
      price: "19,90 €",
      checkedAt: "2026-08-14",
      href: "https://irb.baija.com/?P51318757CD2D1D1&redir=https%3A%2F%2Fbaija.com%2Fproducts%2Fl-irresistible-eau-de-parfum-jardin-pallanca",
    }],
  },
  {
    slug: "beauty-of-joseon-relief-sun",
    category: "k-beauty",
    addedAt: "2026-08-13T12:00:00",
    brand: "Beauty of Joseon",
    name: "Relief Sun SPF50+ PA++++",
    image: "/images/articles/beauty-of-joseon-relief-sun-creme-solaire-yesstyle-2026.png",
    imageAlt: "Beauty of Joseon Relief Sun crème solaire SPF50+ PA++++",
    teaser: "Un solaire coréen hydratant au riz et aux probiotiques, apprécié pour son fini sans traces blanches.",
    lead: "Une protection solaire visage coréenne à la texture de crème légère. Elle convient surtout aux peaux normales à sèches qui recherchent un SPF quotidien confortable sans effet blanc.",
    idealFor: ["Protection quotidienne SPF50+", "Peaux normales à sèches", "Routine K-Beauty simple"],
    strengths: ["Texture confortable sous le maquillage", "Fini sans traces blanches", "Association riz et probiotiques"],
    watchOut: ["Une peau très grasse peut préférer une texture plus mate", "La protection doit être renouvelée en cas d’exposition"],
    editorialNote: "Notre avis : c’est un excellent solaire de ville pour celles qui abandonnent les SPF trop épais. Son principal intérêt est le confort d’utilisation quotidien, pas une promesse de soin miracle.",
    seoTitle: "Beauty of Joseon Relief Sun : avis et prix",
    seoDescription: "Beauty of Joseon Relief Sun SPF50+ : notre avis, les peaux auxquelles il convient, prix Amazon via API, offre YesStyle et avis des utilisatrices.",
    offers: [
      {
        merchant: "Amazon",
        note: "Prix et disponibilité actualisés par l’API officielle",
        href: "https://www.amazon.fr/dp/B0DFMGBZ9Z?tag=lebrunnathali-21",
        amazonAsin: "B0DFMGBZ9Z",
      },
      {
        merchant: "YesStyle",
        note: "Fiche Beauty of Joseon",
        price: "14,40 €",
        checkedAt: "2026-08-14",
        offer: "Codes promotionnels YesStyle selon l’opération en cours",
        href: "https://www.awin1.com/cread.php?awinmid=15447&awinaffid=990397&ued=https%3A%2F%2Fwww.yesstyle.com%2Ffr%2Fbeauty-of-joseon-relief%2Finfo.html%2Fpid.1137908658",
      },
    ],
  },
  {
    slug: "cerave-creme-hydratante-visage",
    category: "soins-visage",
    addedAt: "2026-08-13T11:55:00",
    brand: "CeraVe",
    name: "Crème Hydratante Visage",
    image: "/images/articles/comparatif-creme-bio-hydratante-cerave-visage-produit.png",
    imageAlt: "CeraVe Crème Hydratante Visage aux céramides et à l’acide hyaluronique",
    teaser: "Un hydratant simple aux trois céramides et à l’acide hyaluronique pour les peaux normales à sèches.",
    lead: "Une crème hydratante sans sophistication inutile, pensée pour soutenir la barrière cutanée. Elle convient surtout aux peaux normales à sèches et aux routines minimalistes.",
    idealFor: ["Peaux normales à sèches", "Barrière cutanée fragilisée", "Routine sans parfum"],
    strengths: ["Trois céramides essentiels", "Acide hyaluronique", "Formule simple et non parfumée"],
    watchOut: ["Peut sembler trop riche sur une peau très grasse", "Ce n’est pas un soin ciblé contre les taches ou les rides"],
    editorialNote: "Notre avis : CeraVe est une valeur sûre pour hydrater sans multiplier les actifs. Elle convient davantage à un besoin de confort et de barrière cutanée qu’à une recherche de correction anti-âge intensive.",
    seoTitle: "CeraVe Crème Hydratante Visage : avis et prix",
    seoDescription: "Avis sur la crème hydratante visage CeraVe : céramides, types de peau, points forts, limites, prix Amazon via API et avis des utilisatrices.",
    offers: [
      {
        merchant: "Amazon",
        note: "Prix et disponibilité actualisés par l’API officielle",
        href: "https://www.amazon.fr/dp/B07C5XYT19?tag=lebrunnathali-21",
        amazonAsin: "B07C5XYT19",
      },
    ],
  },
  {
    slug: "dr-pierre-ricaud-creme-lifting-raffermissante",
    category: "soins-visage",
    addedAt: "2026-08-13T18:20:00",
    brand: "Dr Pierre Ricaud",
    name: "Crème Lifting Raffermissante",
    image: "/images/articles/dr-pierre-ricaud-creme-lifting-raffermissante-booster-collagenes-et-elastine.png",
    imageAlt: "Crème lifting raffermissante Dr Pierre Ricaud booster collagènes et élastine",
    teaser: "Un soin anti-âge destiné aux peaux matures qui recherchent surtout fermeté, confort et amélioration de l’apparence de l’ovale.",
    lead: "La Crème Lifting Raffermissante Dr Pierre Ricaud cible la perte de fermeté avec un positionnement booster de collagènes et d’élastine. Cette fiche rassemble notre analyse, le prix vérifié chez la marque et les avis des visiteuses.",
    idealFor: ["Peaux matures", "Perte de fermeté", "Visage et ovale moins toniques"],
    strengths: ["Texture pensée pour le confort des peaux matures", "Positionnement ciblé fermeté", "Nombreux avis clients chez la marque"],
    watchOut: ["Les résultats varient selon la peau et la régularité", "Un cosmétique ne remplace pas une protection solaire quotidienne"],
    editorialNote: "Notre avis : une option cohérente pour découvrir les soins Dr Pierre Ricaud lorsque la priorité est la fermeté. Il faut juger surtout le confort, la tolérance et l’évolution de la peau après plusieurs semaines.",
    seoTitle: "Dr Pierre Ricaud avis : crème lifting raffermissante",
    seoDescription: "Dr Pierre Ricaud : avis sur la crème lifting raffermissante, types de peau, points forts, limites, offre officielle et avis des utilisatrices.",
    offers: [{
      merchant: "Dr Pierre Ricaud",
      note: "Boutique officielle Dr Pierre Ricaud",
      price: "28,90 €",
      offer: "-44 %",
      checkedAt: "2026-08-14",
      href: "https://www.awin1.com/cread.php?awinmid=6977&awinaffid=990397&ued=https%3A%2F%2Fwww.ricaud.com%2Ffr-fr%2Fcreme-lifting-raffermissante-booster-collagenes-et-elastine-1.htm",
    }],
  },
  {
    slug: "clarins-double-serum-avis",
    category: "soins-visage",
    addedAt: "2026-08-13T18:15:00",
    brand: "Clarins",
    name: "Double Serum",
    image: "/images/articles/avis-clarins-soins-anti-age-premium-test-2026.png",
    imageAlt: "Clarins Double Serum soin visage anti-âge premium",
    teaser: "Le sérum anti-âge emblématique de Clarins : une formule premium à évaluer selon le confort, l’éclat et le budget.",
    lead: "Clarins Double Serum est un soin anti-âge premium connu pour sa double formule. Notre analyse distingue les promesses de la marque, l’expérience cosmétique et les résultats que chaque utilisatrice peut réellement commenter.",
    idealFor: ["Peaux matures ou en manque d’éclat", "Routine anti-âge premium", "Utilisatrices appréciant les textures sensorielles"],
    strengths: ["Texture et dosage caractéristiques", "S’intègre facilement avant une crème", "Référence connue avec beaucoup de retours d’utilisation"],
    watchOut: ["Budget élevé", "La présence de parfum peut déplaire aux peaux très réactives", "Aucun résultat individuel n’est garanti"],
    editorialNote: "Notre avis : Double Serum mise autant sur l’expérience d’utilisation que sur son positionnement anti-âge. Il est surtout pertinent si la texture plaît et si le budget permet une utilisation régulière.",
    seoTitle: "Clarins Double Serum : avis, utilisation et offre",
    seoDescription: "Clarins Double Serum : notre avis, pour quelles peaux, points forts, limites, offre Clarins suivie et avis des utilisatrices Bons Plans Mania.",
    offers: [{
      merchant: "Clarins",
      note: "Double Serum 30 ml — boutique officielle Clarins",
      price: "108 €",
      checkedAt: "2026-08-14",
      offer: "Code WELCOME20 : -20 % sur la première commande et cadeaux selon conditions",
      href: "https://track.effiliation.com/servlet/effi.redir?id_compteur=23248736&url=https%3A%2F%2Fwww.clarins.fr%2Fdouble-serum---serum-anti-age-raffermissant%2F80103084.html",
    }],
  },
  {
    slug: "nuxe-huile-prodigieuse-avis-prix",
    category: "soins-visage",
    addedAt: "2026-08-13T18:10:00",
    brand: "Nuxe",
    name: "Huile Prodigieuse",
    image: "/images/articles/nuxe-huile-prodigieuse-100ml-visage-corps-cheveux-2026.png",
    imageAlt: "Nuxe Huile Prodigieuse huile sèche visage corps et cheveux",
    teaser: "L’huile sèche multi-usage culte de Nuxe pour le visage, le corps et les cheveux, avec une fragrance très présente.",
    lead: "L’Huile Prodigieuse de Nuxe est un soin sec multi-usage destiné à nourrir et satiner le visage, le corps et les cheveux. Son parfum signature fait partie de l’expérience et mérite d’être pris en compte avant l’achat.",
    idealFor: ["Peaux normales à sèches", "Pointes de cheveux sèches", "Routine corps sensorielle"],
    strengths: ["Usage visage, corps et cheveux", "Fini d’huile sèche", "Plusieurs versions disponibles"],
    watchOut: ["Parfum marqué", "À doser légèrement sur les cheveux fins", "La version classique n’est pas une protection solaire"],
    editorialNote: "Notre avis : son intérêt vient de sa polyvalence et de son fini sec. Elle séduira surtout les personnes qui aiment sa fragrance ; les peaux réactives au parfum devront tester avec prudence.",
    seoTitle: "Nuxe Huile Prodigieuse : avis et prix",
    seoDescription: "Nuxe Huile Prodigieuse : notre avis, usages visage corps cheveux, points forts, précautions, prix chez nos partenaires et avis des utilisatrices.",
    offers: [{
      merchant: "Amazon",
      note: "Nuxe Huile Prodigieuse 100 ml",
      price: "24,20 €",
      checkedAt: "2026-08-14",
      href: "https://www.amazon.fr/100-Nuxe-Huile-Prodigieuse-S%C3%A8che/dp/B01ATJESD6?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=34TV2XPXUMZJR&dib=eyJ2IjoiMSJ9.oa4U5V3WoUZCEIpR-0WD2lbVZvm2HxYWU8C1y2ftn3yJqTj9YDCOgmSEOCC6F9qVcAEOA9Y45SaP3ZODhhMTQV-Oz_vJbQjZgVfzfs9a82F1E6KpHSMDPOsa5oJWiJ5E5S8eHC5y-lAh7H0aFW2BMcX8lHFp7vV9YxkoqH_hleRoeP8499Eg3Y4cgR3WP8JtaMlCMWjrB3Gg7-iKGKzbaC6ucL8fAzwbGmgP5_x7bsNBoEu6qBINoCMOioIV-9uXJ0q-fwxLW33y1E_X7KFCrus2SSPScKMEQ4baGrXduek.KuNcuJYTL5ovma_mGlY8ykNNK3V22slFb0wk1NMwrAU&dib_tag=se&keywords=huile%2Bprodigieuse&qid=1786705709&sprefix=huile%2Bprodigieuse%2B%2Caps%2C173&sr=8-3&th=1&linkCode=ll2&tag=lebrunnathali-21&linkId=5d661e0a8321606421cffbb112c39ee2&ref_=as_li_ss_tl",
    }],
  },
  {
    slug: "meilleure-creme-anti-age-60-ans",
    category: "soins-visage",
    addedAt: "2026-08-13T18:05:00",
    brand: "Nuxe",
    name: "Nuxuriance Ultra La Crème Anti-Âge Global 50 ml",
    image: "/images/articles/nuxe-nuxuriance-ultra-creme-riche-anti-age-2026.png",
    imageAlt: "Nuxe Nuxuriance Ultra La Crème Anti-Âge Global 50 ml",
    teaser: "Une crème visage Nuxe de 50 ml destinée aux peaux matures qui recherchent confort, fermeté et action sur les signes de l’âge.",
    lead: "Nuxuriance Ultra La Crème Anti-Âge Global de Nuxe est un soin visage de 50 ml conçu pour les peaux matures. Cette fiche présente ses usages, ses points forts et ses limites avant l’achat.",
    idealFor: ["Peaux matures", "Recherche de confort", "Routine visage anti-âge"],
    strengths: ["Format 50 ml", "Soin visage ciblé pour les peaux matures", "Texture crème adaptée à une routine quotidienne"],
    watchOut: ["La tolérance et les résultats varient selon la peau", "Vérifier la composition en cas de sensibilité", "Cette crème ne remplace pas une protection solaire"],
    editorialNote: "Notre avis : une crème à envisager si vous recherchez un soin Nuxe destiné aux peaux matures. Le choix doit surtout dépendre du confort de la texture, de la tolérance et du budget.",
    seoTitle: "Nuxe Nuxuriance Ultra 50 ml : avis et prix",
    seoDescription: "Nuxe Nuxuriance Ultra La Crème Anti-Âge Global 50 ml : avis, types de peau, points forts, précautions et lien Amazon.",
    offers: [{
      merchant: "Amazon",
      note: "Nuxe Nuxuriance Ultra La Crème Anti-Âge Global 50 ml",
      price: "31,13 €",
      checkedAt: "2026-08-14",
      href: "https://www.amazon.fr/Nuxe-3264680036880-NUXURIANCE%C2%AE-ULTRA-50ml/dp/B0CRS2SGQM?crid=4MKQHLRPG9PW&dib=eyJ2IjoiMSJ9.CQnAIV22KOXWkLuDVDnSCpW4lxsJmaGOxVol-w_8ADbzTfd2mQxiSHJ6jyOZW-SzVf5v3xMMh_hLSUw1l56xrdKLaao3h91mToFH2oyPiVnfXHBK6V5DscQHoIOqe-2Mzhc-VpXSwwSpbrYHgkandqbaYwnWkO52Lt3OYuEV8L1t6bHiRZD-ZspZ5z5t60-NcTf_6k2x3lGyLg7Iq0S5Cpg8qgsZD41dcktmIeBWycVz5OR0FuceCm-aWmj3ye6YRwwJLoIcYEaDBXUs7e4h1QFkdtZ29iIXqRFo11S0EG4.tuar5xIW2pM8ekFkKhRdehm0QzshfTQfftqUqFeAo7A&dib_tag=se&keywords=nuxe+nuxuriance&qid=1786706047&sprefix=nuxe+n%2Caps%2C175&sr=8-3&linkCode=ll2&tag=lebrunnathali-21&linkId=721c01b6839c6799f80e33a4e0c655f7&ref_=as_li_ss_tl",
    }],
  },
  {
    slug: "la-roche-posay-anthelios-uvmune-400-fluide-invisible-spf50",
    category: "solaires",
    addedAt: "2026-08-13T11:50:00",
    brand: "La Roche-Posay",
    name: "Anthelios UVMune 400 Fluide Invisible SPF50+",
    image: "/images/articles/bon-plan-lookfantastic-la-roche-posay-anthelios-uvmune-400-spf50-19-32-euros-juillet-2026.png",
    imageAlt: "La Roche-Posay Anthelios UVMune 400 Fluide Invisible SPF50+ 50 ml",
    teaser: "Un fluide solaire visage non parfumé à très haute protection, adapté notamment aux peaux sensibles.",
    lead: "Un solaire visage fluide et non parfumé, conçu pour une haute protection quotidienne contre les UVB et les UVA longs. Une option pertinente pour les peaux sensibles qui préfèrent une texture légère.",
    offers: [
      {
        merchant: "Lookfantastic",
        note: "Flacon 50 ml non parfumé",
        price: "18,11 €",
        checkedAt: "2026-08-02",
        offer: "Prix ancien daté : vérifier le tarif actuel",
        href: "https://www.awin1.com/cread.php?awinmid=7496&awinaffid=990397&ued=https%3A%2F%2Fwww.lookfantastic.fr%2Fp%2Fla-roche-posay-anthelios-uvmune-400-invisible-fluid-non-perfumed-suncream-spf50-50ml%2F13494906%2F",
      },
    ],
  },
  {
    slug: "laneige-lip-sleeping-mask",
    category: "k-beauty",
    addedAt: "2026-08-13T11:45:00",
    brand: "Laneige",
    name: "Lip Sleeping Mask",
    image: "/images/articles/bon-plan-laneige-lip-sleeping-mask-3-versions-yesstyle-juin-2026.png",
    imageAlt: "Laneige Lip Sleeping Mask masque de nuit pour les lèvres",
    teaser: "Le masque de nuit coréen pour les lèvres sèches, décliné en plusieurs parfums.",
    lead: "Un masque lèvres riche à utiliser le soir, destiné aux lèvres sèches ou gercées. Les différentes versions partagent le même positionnement gourmand et nourrissant.",
    idealFor: ["Lèvres sèches", "Soin à appliquer le soir", "Personnes appréciant les textures riches"],
    strengths: ["Format 20 g", "S’utilise en petite quantité", "Plusieurs parfums selon les stocks"],
    watchOut: ["Le parfum peut ne pas convenir aux lèvres sensibles", "La texture riche peut sembler épaisse", "Le résultat varie selon l’état des lèvres"],
    editorialNote: "Notre avis : un soin de nuit pratique pour les lèvres sèches, surtout si vous appréciez les textures enveloppantes et parfumées. Une petite quantité suffit à chaque utilisation.",
    offers: [
      {
        merchant: "YesStyle",
        note: "Laneige Lip Sleeping Mask 20 g",
        price: "11,95 €",
        checkedAt: "2026-08-14",
        offer: "Codes promotionnels YesStyle selon l’opération en cours",
        href: "https://www.awin1.com/cread.php?awinmid=15447&awinaffid=990397&ued=https%3A%2F%2Fwww.yesstyle.com%2Ffr%2Flaneige-lip-sleeping%2Finfo.html%2Fpid.1039417845",
      },
    ],
  },
  {
    slug: "terre-d-hermes-eau-de-toilette",
    gender: "homme",
    category: "parfums",
    addedAt: "2026-08-01T19:16:00",
    brand: "Hermès",
    name: "Terre d’Hermès Eau de Toilette",
    image: "/images/products/terre-d-hermes-eau-de-toilette.png",
    imageAlt: "Flacon Hermès Terre d’Hermès Eau de Toilette",
    teaser:
      "Orange et pamplemousse sur une note minérale de silex, un fond de vétiver et de cèdre.",
  },
  {
    slug: "viktor-rolf-spicebomb-eau-de-toilette",
    gender: "homme",
    category: "parfums",
    addedAt: "2026-08-01T19:12:00",
    brand: "Viktor & Rolf",
    name: "Spicebomb Eau de Toilette",
    image: "/images/products/viktor-rolf-spicebomb-eau-de-toilette.png",
    imageAlt: "Flacon grenade Viktor & Rolf Spicebomb Eau de Toilette",
    teaser:
      "Poivre rose et bergamote, un cœur de piment et de safran, puis tabac et cuir. Taillé pour l’hiver.",
  },
  {
    slug: "azzaro-the-most-wanted-eau-de-parfum-intense",
    gender: "homme",
    category: "parfums",
    addedAt: "2026-08-01T19:08:00",
    brand: "Azzaro",
    name: "The Most Wanted Eau de Parfum Intense",
    image: "/images/products/azzaro-the-most-wanted-eau-de-parfum-intense.png",
    imageAlt: "Flacon noir cranté Azzaro The Most Wanted Eau de Parfum Intense",
    teaser:
      "Cardamome et gingembre, liqueur de bourbon et bois ambrés, vanille en fond. Un gourmand du soir.",
  },
  {
    slug: "hugo-boss-bottled-eau-de-toilette",
    gender: "homme",
    category: "parfums",
    addedAt: "2026-08-01T19:04:00",
    brand: "Hugo Boss",
    name: "Boss Bottled Eau de Toilette",
    image: "/images/products/hugo-boss-bottled-eau-de-toilette.png",
    imageAlt: "Flacon Hugo Boss Boss Bottled Eau de Toilette",
    teaser:
      "Pomme et bergamote, cannelle et œillet, santal et vétiver. Le boisé épicé passe-partout.",
  },
  {
    slug: "armani-acqua-di-gio-eau-de-toilette",
    gender: "homme",
    category: "parfums",
    addedAt: "2026-08-01T19:00:00",
    brand: "Giorgio Armani",
    name: "Acqua di Giò Eau de Toilette",
    image: "/images/products/armani-acqua-di-gio-eau-de-toilette.png",
    imageAlt: "Flacon Giorgio Armani Acqua di Giò Eau de Toilette",
    teaser:
      "Le fondateur des parfums marins : notes iodées, bergamote et néroli, patchouli et musc blanc.",
  },
  {
    slug: "rabanne-1-million-eau-de-toilette",
    gender: "homme",
    category: "parfums",
    addedAt: "2026-08-01T18:56:00",
    brand: "Rabanne",
    name: "1 Million Eau de Toilette",
    image: "/images/products/rabanne-1-million-eau-de-toilette.png",
    imageAlt: "Flacon lingot doré Rabanne 1 Million Eau de Toilette",
    teaser:
      "Pamplemousse et menthe, un cœur de rose et de cannelle, puis cuir et ambre. Il ne cherche pas la discrétion.",
  },
  {
    slug: "yves-saint-laurent-y-eau-de-parfum",
    gender: "homme",
    category: "parfums",
    addedAt: "2026-08-01T18:52:00",
    brand: "Yves Saint Laurent",
    name: "Y Eau de Parfum",
    image: "/images/products/yves-saint-laurent-y-eau-de-parfum.png",
    imageAlt: "Flacon dégradé bleu Yves Saint Laurent Y Eau de Parfum",
    teaser:
      "Bergamote et gingembre, sauge sclarée et genévrier, fève tonka et cèdre en fond.",
  },
  {
    slug: "jean-paul-gaultier-le-male-eau-de-toilette",
    gender: "homme",
    category: "parfums",
    addedAt: "2026-08-01T18:48:00",
    brand: "Jean Paul Gaultier",
    name: "Le Male Eau de Toilette",
    image: "/images/products/jean-paul-gaultier-le-male-eau-de-toilette.png",
    imageAlt: "Flacon buste à la marinière Jean Paul Gaultier Le Male Eau de Toilette",
    teaser:
      "Menthe et lavande, cannelle et fleur d’oranger, vanille et fève tonka. Le masculin sucré fondateur.",
  },
  {
    slug: "dior-sauvage-eau-de-toilette",
    gender: "homme",
    category: "parfums",
    addedAt: "2026-08-01T18:44:00",
    brand: "Dior",
    name: "Sauvage Eau de Toilette",
    image: "/images/products/dior-sauvage-eau-de-toilette.png",
    imageAlt: "Flacon Dior Sauvage Eau de Toilette",
    teaser:
      "Bergamote de Calabre et poivre de Sichuan, puis l’ambroxan qui a fait sa réputation.",
  },
  {
    slug: "bleu-de-chanel-eau-de-parfum",
    gender: "homme",
    category: "parfums",
    addedAt: "2026-08-01T18:40:00",
    brand: "Chanel",
    name: "Bleu de Chanel Eau de Parfum",
    image: "/images/products/bleu-de-chanel-eau-de-parfum.png",
    imageAlt: "Flacon bleu nuit Chanel Bleu de Chanel Eau de Parfum",
    teaser:
      "Un boisé aromatique tenu : citron et menthe, gingembre et muscade, santal et encens en fond.",
  },
  {
    slug: "nuxe-prodigieux-le-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-01T18:12:00",
    brand: "Nuxe",
    name: "Prodigieux Le Parfum",
    image: "/images/products/nuxe-prodigieux-le-parfum.png",
    imageAlt: "Flacon Nuxe Prodigieux Le Parfum au dégradé orangé",
    teaser:
      "L’odeur de l’Huile Prodigieuse en parfum : fleur d’oranger, magnolia et vanille sur un fond de bois de coco.",
  },
  {
    slug: "guerlain-la-petite-robe-noire-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-01T18:06:00",
    brand: "Guerlain",
    name: "La Petite Robe Noire Eau de Parfum",
    image: "/images/products/guerlain-la-petite-robe-noire-eau-de-parfum.png",
    imageAlt:
      "Flacon Guerlain La Petite Robe Noire Eau de Parfum au bouchon cœur",
    teaser:
      "Une cerise noire gourmande adossée à la rose et à l’amande, sur un fond de patchouli et de fève tonka.",
  },
  {
    slug: "chloe-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-01T17:58:00",
    brand: "Chloé",
    name: "Chloé Eau de Parfum",
    image: "/images/products/chloe-eau-de-parfum.png",
    imageAlt: "Flacon Chloé Eau de Parfum et son ruban beige",
    teaser:
      "La rose sans la lourdeur : pivoine et litchi, un cœur de rose fraîche, un fond d’ambre et de cèdre.",
  },
  {
    slug: "burberry-goddess-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-01T17:45:00",
    brand: "Burberry",
    name: "Goddess Eau de Parfum",
    image: "/images/products/burberry-goddess-eau-de-parfum.png",
    imageAlt: "Flacon doré Burberry Goddess Eau de Parfum",
    teaser:
      "Une vanille en trois textures — infusée, crémeuse et brûlée — relevée par la lavande et le cacao.",
  },
  {
    slug: "mugler-alien-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-01T17:20:00",
    brand: "Mugler",
    name: "Alien Eau de Parfum",
    image: "/images/products/mugler-alien-eau-de-parfum.png",
    imageAlt: "Flacon violet et or Mugler Alien Eau de Parfum",
    teaser:
      "Jasmin sambac, bois de cachemire et ambre blanc : l’un des sillages les plus tenaces du rayon.",
  },
  {
    slug: "rabanne-lady-million-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-01T17:14:00",
    brand: "Rabanne",
    name: "Lady Million Eau de Parfum",
    image: "/images/products/rabanne-lady-million-eau-de-parfum.png",
    imageAlt: "Flacon diamant doré Rabanne Lady Million Eau de Parfum",
    teaser:
      "Un floral chypré solaire : néroli et framboise, fleur d’oranger et jasmin, patchouli et miel en fond.",
  },
  {
    slug: "valentino-born-in-roma-donna-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-01T17:08:00",
    brand: "Valentino",
    name: "Donna Born in Roma Eau de Parfum",
    image: "/images/products/valentino-born-in-roma-donna-eau-de-parfum.png",
    imageAlt: "Flacon clouté Valentino Donna Born in Roma Eau de Parfum",
    teaser:
      "Jasmin sambac et bourgeon de cassis en tête, vanille bourbon et bois de cèdre en fond.",
  },
  {
    slug: "prada-paradoxe-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-01T16:58:00",
    brand: "Prada",
    name: "Paradoxe Eau de Parfum",
    image: "/images/products/prada-paradoxe-eau-de-parfum.png",
    imageAlt: "Flacon triangle Prada Paradoxe Eau de Parfum",
    teaser:
      "Un floral ambré autour du néroli et du jasmin, dans le flacon triangle rechargeable de la maison.",
  },
  {
    slug: "jean-paul-gaultier-la-belle-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-01T16:54:00",
    brand: "Jean Paul Gaultier",
    name: "La Belle Eau de Parfum",
    image: "/images/products/jean-paul-gaultier-la-belle-eau-de-parfum.png",
    imageAlt: "Flacon buste Jean Paul Gaultier La Belle Eau de Parfum",
    teaser:
      "Trois notes, pas une de plus : poire juteuse, vanille et bois de santal, pour un sillage sucré et lumineux.",
  },
  {
    slug: "carolina-herrera-good-girl-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-01T16:48:00",
    brand: "Carolina Herrera",
    name: "Good Girl Eau de Parfum",
    image: "/images/products/carolina-herrera-good-girl-eau-de-parfum.png",
    imageAlt: "Flacon escarpin Carolina Herrera Good Girl Eau de Parfum",
    teaser:
      "Jasmin sambac et tubéreuse en pleine lumière, cacao et fève tonka dans l’ombre. Un parfum du soir très tenace.",
  },
  {
    slug: "dior-miss-dior-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-01T16:42:00",
    brand: "Dior",
    name: "Miss Dior Eau de Parfum",
    image: "/images/products/dior-miss-dior-eau-de-parfum.png",
    imageAlt:
      "Flacon Dior Miss Dior Eau de Parfum et son nœud couture argenté",
    teaser:
      "Un bouquet de roses de Grasse porté par la pivoine et l’iris, adouci par le bois de santal et le musc blanc.",
  },
  {
    slug: "chanel-coco-mademoiselle-eau-de-parfum",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-01T16:30:00",
    brand: "Chanel",
    name: "Coco Mademoiselle Eau de Parfum",
    image: "/images/products/chanel-coco-mademoiselle-eau-de-parfum.png",
    imageAlt: "Flacon Chanel Coco Mademoiselle Eau de Parfum vaporisateur",
    teaser:
      "L’oriental frais de Chanel : orange et bergamote, un cœur de rose et de jasmin, un fond de patchouli et de vétiver.",
  },
  {
    slug: "sol-de-janeiro-cheirosa-62-perfume-mist-90ml",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-01T16:05:00",
    brand: "Sol de Janeiro",
    name: "Cheirosa 62 Brume Parfumée 90 ml",
    image: "/images/products/sol-de-janeiro-cheirosa-62-perfume-mist-90ml.png",
    imageAlt: "Flacon Sol de Janeiro Cheirosa 62 Brume Parfumée 90 ml",
    teaser:
      "L’odeur qui a rendu la marque brésilienne célèbre : pistache et caramel salé sur un fond de vanille et d’héliotrope.",
  },
  {
    slug: "kayali-yum-boujee-marshmallow-81",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-08-01T15:40:00",
    brand: "Kayali",
    name: "Yum Boujee Marshmallow 81 Eau de Parfum Intense",
    image: "/images/products/kayali-yum-boujee-marshmallow-81.png",
    imageAlt:
      "Flacon Kayali Yum Boujee Marshmallow 81 Eau de Parfum Intense 10 ml",
    teaser:
      "Le gourmand assumé de Mona Kattan : guimauve rose et vanille fouettée sur un départ fruité de pomme et de citron.",
  },
  {
    slug: "la-vie-est-belle-eau-de-parfum-lancome",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-07-30T18:51:00",
    brand: "Lancôme",
    name: "La Vie Est Belle Eau de Parfum",
    image: "/images/products/la-vie-est-belle-eau-de-parfum-lancome.png",
    imageAlt: "Flacon La Vie Est Belle Eau de Parfum 50 ml de Lancôme",
    teaser:
      "Un iris gourmand devenu iconique, adouci par la poire et réchauffé par la vanille, le praliné et le patchouli.",
  },
  {
    slug: "opium-eau-de-parfum-yves-saint-laurent",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-07-30T15:11:00",
    brand: "Yves Saint Laurent",
    name: "Opium Eau de Parfum",
    image: "/images/products/opium-eau-de-parfum-yves-saint-laurent.png",
    imageAlt: "Flacon Opium Eau de Parfum 50 ml d’Yves Saint Laurent",
    teaser:
      "Un oriental au caractère chaleureux et épicé, l’un des sillages les plus reconnaissables de la parfumerie.",
  },
  {
    slug: "libre-eau-de-parfum-yves-saint-laurent",
    gender: "femme",
    category: "parfums",
    addedAt: "2026-07-30T18:51:00",
    brand: "Yves Saint Laurent",
    name: "Libre Eau de Parfum",
    image: "/images/products/ysl-libre-eau-de-parfum-50ml-officiel.png",
    imageAlt: "Flacon Libre Eau de Parfum 50 ml d’Yves Saint Laurent",
    teaser:
      "Une lavande florale moderne où la fraîcheur aromatique rencontre la sensualité de la fleur d’oranger.",
  },
];
