export type ProductTestGuide = { platform:string; name:string; universe:string; places:string; deadline:string; status:"Campagne"|"Programme permanent"; image:string; imageAlt:string; articleHref:string; applyHref:string };
export const PRODUCT_TESTS_GUIDE_2026: ProductTestGuide[] = [
  { platform:"Free Cosmetic Testing", name:"Cosmétiques gratuits à tester", universe:"Beauté", places:"Nouveaux tirages chaque semaine", deadline:"Programme permanent", status:"Programme permanent", image:"/images/articles/test-produit-free-cosmetic-testing-2026.jpg", imageAlt:"Cosmétiques proposés par Free Cosmetic Testing", articleHref:"/article/test-produit-free-cosmetic-testing-cosmetiques-gratuits-2026", applyHref:"https://www.free-cosmetic-testing.com/fr/produit-a-tester" },
  { platform:"Kiabi Community", name:"Robe vichy femme", universe:"Mode", places:"Profils sélectionnés par Kiabi", deadline:"Campagne ouverte lors de la vérification", status:"Campagne", image:"/images/articles/test-produit-kiabi-robe-vichy-femme-aout-2026.webp", imageAlt:"Robe vichy femme à tester sur Kiabi Community", articleHref:"/article/test-produit-kiabi-robe-vichy-femme-aout-2026", applyHref:"https://community.kiabi.com/app/11/channel/test-produit-v2-2606/details/4838" },
  { platform:"Philips Product Tester", name:"Produits Philips", universe:"Maison et high-tech", places:"Selon les campagnes disponibles", deadline:"Programme permanent", status:"Programme permanent", image:"/images/articles/test-gratuit-philips-product-tester-2026.webp", imageAlt:"Programme Philips Product Tester", articleHref:"/article/test-gratuit-philips-product-tester-2026", applyHref:"https://philipsb2c.my.site.com/producttesterprogram/s/?language=en_US&locale=fr_FR" },
  { platform:"Sampleo", name:"Campagne Barilla", universe:"Alimentation", places:"Profils sélectionnés par Sampleo", deadline:"Ouverture annoncée autour du 17 août", status:"Campagne", image:"/images/articles/test-produit-barilla-sampleo-aout-2026-v2.webp", imageAlt:"Campagne de test produit Barilla sur Sampleo", articleHref:"/article/test-produit-barilla-sampleo-campagne-aout-2026", applyHref:"https://www.sampleo.com/fr/campaign/barilla" },
  { platform:"Tester des Produits", name:"Bande élastique fitness", universe:"Sport", places:"16 testeurs", deadline:"Tirage le 9 novembre 2026", status:"Campagne", image:"/images/articles/test-produit-bande-elastique-fitness-16-testeurs-2026.jpg", imageAlt:"Bande élastique fitness proposée à seize testeurs", articleHref:"/article/test-produit-gratuit-bande-elastique-fitness-16-testeurs-2026", applyHref:"https://www.testerdesproduits.fr/details-produit/567/bande-elastique-fitness" },
  { platform:"Tester des Produits", name:"Plaid polaire doux", universe:"Maison", places:"12 testeurs", deadline:"Tirage le 2 novembre 2026", status:"Campagne", image:"/images/articles/test-produit-gratuit-plaid-polaire-doux-2026.webp", imageAlt:"Plaid polaire doux proposé à douze testeurs", articleHref:"/article/test-produit-gratuit-plaid-polaire-doux-2026", applyHref:"https://www.testerdesproduits.fr/details-produit/566/plaid-polaire-doux" },
  { platform:"TRND", name:"GrandLait des P’tits Candia", universe:"Famille et alimentation", places:"250 familles", deadline:"Candidatures ouvertes lors de la vérification", status:"Campagne", image:"/images/articles/test-produit-grandlait-des-ptits-candia-trnd-2026.jpg", imageAlt:"GrandLait des P’tits Candia à tester avec TRND", articleHref:"/article/test-produit-grandlait-des-ptits-candia-trnd-250-familles-2026", applyHref:"https://www.trnd.com/fr/projets/grandlait-des-ptits/infos-sur-le-projet" },
  { platform:"TRND", name:"Protections contre les fuites urinaires", universe:"Hygiène", places:"500 femmes", deadline:"Candidatures avant le 9 septembre 2026", status:"Campagne", image:"/images/articles/test-produit-always-discreet-trnd-500-femmes-2026.webp", imageAlt:"Protections contre les fuites urinaires à tester avec TRND", articleHref:"/article/test-gratuit-protections-fuites-urinaires-trnd-500-femmes-2026", applyHref:"https://www.trnd.com/fr/projets/plus-de-protection-plus-de-confiance-blog/infos-sur-le-projet" },
];
