name = "bonsplansmania-newsletter"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 7 * * TUE,SAT"]  # mardi et samedi a 7h UTC (9h France heure d'ete)

[[kv_namespaces]]
binding = "SUBSCRIBERS"
id = "dfee15b944c84dabacef57e92345f4b8"

[vars]
SITE_URL = "https://bonsplansmania.fr"
FROM_EMAIL = "newsletter@bonsplansmania.fr"
FROM_NAME = "Bons Plans Mania"
